// Convert the engraved source into aligned ASCII tone layers. The bitmap is a
// build input only; the page renders letters, not an image of letters.
import { writeFileSync } from 'node:fs';
import sharp from 'sharp';

const COLS = 100;
const ROWS = 60;
const FONT_SIZE = 4;
const CELL_WIDTH = FONT_SIZE * 0.6;
const names = ['detail', 'body', 'highlights'];
const source = new URL('../assets/puppet/chrome-hand.png', import.meta.url);
const pixels = await sharp(source.pathname)
  .flatten({ background: '#000000' })
  .resize(COLS, ROWS, { fit: 'fill', kernel: 'lanczos3' })
  .greyscale()
  .raw()
  .toBuffer();

function encode(mirror = false) {
  const layers = [[], [], []];
  for (let y = 0; y < ROWS; y++) {
    const rows = ['', '', ''];
    for (let x = 0; x < COLS; x++) {
      const value = pixels[y * COLS + (mirror ? COLS - x - 1 : x)] / 255;
      let glyph = ' ';
      let layer = 0;
      if (value > 0.055) {
        const ramp = 'iltvzxcakdmw';
        glyph = ramp[Math.min(ramp.length - 1, Math.floor(value ** 0.85 * ramp.length))];
        layer = value > 0.57 ? 2 : value > 0.23 ? 1 : 0;
      }
      for (let i = 0; i < 3; i++) rows[i] += i === layer ? glyph : ' ';
    }
    rows.forEach((row, i) => layers[i].push(row));
  }
  return layers.map(rows => rows.join('\n'));
}

// Four visible fingertip contact points, from the outer to the inner edge.
const fingertips = [[0.353, 0.838], [0.539, 0.895], [0.728, 0.829], [0.886, 0.575]];
const width = COLS * CELL_WIDTH;
const height = ROWS * FONT_SIZE;
const serialize = layers => `{\n${layers.map((text, i) => `  ${names[i]}: \`${text}\``).join(',\n')}\n}`;
const output = `// Generated by scripts/generatePuppetHands.mjs.
export const HAND_LEFT = ${serialize(encode())};
export const HAND_RIGHT = ${serialize(encode(true))};
export const HAND_WIDTH = ${width};
export const HAND_HEIGHT = ${height};
export const HAND_FONT_SIZE = ${FONT_SIZE};
export const HAND_TIPS = ${JSON.stringify(fingertips.map(([x,y]) => [Number((x * width).toFixed(2)), Number((y * height).toFixed(2))]))} as const;
`;
writeFileSync(new URL('../src/components/ambient/puppetHandArt.ts', import.meta.url), output);
console.log(`Wrote ${COLS} × ${ROWS} ASCII hands with three registered tone layers.`);
