// Generated by scripts/generatePuppetHands.mjs.
export const HAND_LEFT = {
  detail: `                                                                                                    
                                                                                                    
                                                                                                    
                      lv     v   t                                                                  
                  t               l                                                                 
               lv              t   t                                                                
             tvvv               v   t                                                               
           t  tlllv              v   t                                                              
              l   lv                  t                                                             
              vll  t                   t                                                            
                tl lv               t    l                                                          
         t       tllt                     l                                                         
          tvt      tt           v     lt                                                            
      t  vtv  t    v  lt    tttv              t                                                     
      t   t    t    tll llll                                                                        
            v l       l  ll                                                                         
        t     t t       l   v                         v                                             
                tt     lvt  v                            t                                          
                  ttl       lv                     v                                                
              l    v   v t  vt                               v   tv  t                              
                  tt   t  l                                            tl                           
                 ttt   t ll                             v tt     tt        l                        
                   l     lll  vl                         lvv       lt        t                      
                      v v l   ttt               v v        t v       vtv      v                     
                         tll  v ttv           vv t          l           vl      vl                  
                    l     t v t  lt  ll    v t t                tt        t        l                
                             t  tll    t    tlvt t    v       l   tv      t  vt     t               
                     t      l    t  l       v tllv     t        tvv     vttt   l      l             
                            t    t lt         t        tt        t    lt  l     t     l             
                            v lvvt tl                   tv        l        t      l    t            
                           t lt  l   t  l                t         l              tl    t           
                            v     tv   vl                 t         l          lvt       t          
                                t   v                      lv     v             t t       v         
                           t       t      t       ttlttll    ltv     t                l             
                          t           v  tlv                          t                    l        
                         vl       t      v t              l  v  vt     l                v l         
                       l tt   t  v        ll                      lv                                
                         t             l    lv    l             t lt    v                           
                       l t                  l                t     t                                
                       l tl v   v       l  ttv                    llv                               
                           tt               vt     t          l    ttv tv                           
                        v tl     l        l v       l          v  ttt     l                         
                           l              t  tltv               lt t                                
                                             l  t    t               tltt  v                        
                                  l        t  l l                l   l  l                           
                           v t      l           lv    v               l l   l                       
                              t      l          lt                l   vt    v                       
                            t vl             l  ttv t  l           t   vt   v                       
                             l  t     v        v vt     l           v  t v                          
                               v vv            t  tv                    tt  v                       
                                l                 l l    t                                          
                                  v   l            tt                  lttl                         
                                                 l  v                                               
                                                     tt                                             
                                                         t                                          
                                                     ltl                                            
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    `,
  body: `                                                                                                    
                                                                                                    
                                                                                                    
                        zxacz zac                                                                   
                   x        czzccx                                                                  
                 x            z zaz                                                                 
                 zz            z  ax                                                                
            zv     x            x   x                                                               
          c cv      c            cv  x                                                              
         x   c      z              zc x                                                             
        vvz    z     x             a z  z                                                           
       zx xz    x    zc            xzaxzvz                                                          
       zxz   x   xv  vzx     cxv zzzcv  vzv                                                         
       zv   xv a  c     vxxv    x      cccxc x                                                      
        cz   vx v  c        zc             a    z                                                   
       aa  x   zv a xx     zz                     zz                                                
         x   c   zv  x    vv c                       c                                              
           v   z  x c     zv z                    xx    c                                           
             z  cv    zz zvv  c                   x zzx    z                                        
               a z        zz  x                  ac   cxc   c      vv                               
                zz  z      xzvva                       zx     zzxc    c                             
                    cvc    zxvvz        c                v  c   z  c     az                         
                    zvzx    cz  xc             x     ac z   xzx zzv  x      c                       
                    c  c    xc   vzxc c        z v zca  cvz x c zzccx   x    a                      
                    z xzc   zx z   c zv         z a      xz  z  cx     c  vxxa                      
                       va  v       cc  c cv v   xxxc      xzxcxz  x      c  vx    z                 
                     x  x c v       c   zc        cxzv vc    c      vzzzx  vv  c   x                
                      a  c   z  c xv vxc          zaxzv       cv   zzzzz    xcz c    z              
                      zcx  c x  z v  z x  axxv cccc  xx        aa       zz vzzcx z   v              
                       ccxac z        axx    c                   c          xccccz vc c             
                        ccv    ac     xa xcxzz            x                  vxzcx                  
                        vcvv a  v   vzx  z  a              z      xc              xx                
                         z vx    vxx  cvzzxc    zxa   ax     xxzcx ca            c v                
                         cc     z   vax  v z    z        x         xc            vzx v              
                        va x   c            c             xcxxvzxa c               v  cvvcz         
                        x  z           xc   z    v         z  zv  zz  c              vxz x          
                        x  xav         z c  vc              vcxz    c  x                            
                       zc vacc  v         v   a               ax    z                               
                        z zzx           x x  vzca z            ax   vc                              
                        c  v                  zzx z           c cz   x   x                          
                        xx   c  a        v v  ccvc               az   z  v                          
                            zx             z vzcx                    zaczc                          
                          c zx   z          z       x             c vzccx c                         
                         v xva   x         c     z                 az                               
                          z vzcc x           c   va  c                   x c                        
                            z zzz  z        x z   c               z  x   z                          
                            cv xa   x          z  xxxav                 zca                         
                             x  v    c        ac   x x                x  c                          
                              xz x   a          x  zzc a             x      z                       
                                z     x          v  zc  x            z                              
                                 xvx  x         xa   z                x  vzc                        
                                   zvv           xc  z   z                                          
                                                  zc  c  c                                          
                                                   xc    x                                          
                                                    zcxzc                                           
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    `,
  highlights: `                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                    akdmwwwd                                                                        
                  adddmmwwwwda                                                                      
                   amwwwwwwwwmk  a                                                                  
                    dmwwwwwwwwwk  kk                                                                
           m         dmwwwwwwwwwd  ak                                                               
          wdk        adwwwwwwwwwmda  a                                                              
           awwa       kmwwwwwmmmmdm   ak                                                            
            kwwd       dmmddmmmmmmd                                                                 
              mwm       akddk                                                                       
                wm               kdkmmk     k                                                       
       w         mm           dmwmdkakkkkka dwwk                                                    
         dk        k         kwmmmmmdddmmwwwmkdmwk                                                  
          kwd      ad         kmmwwwwwwwmddmwwdkakkwm                                               
            kwk    m          dwwwwwwwwwwmmddmmmkk  admd                                            
              dm               dwwwwwwwwwwwmmddmmd     dmmd                                         
                m a  ak        kmwwwwwwwwwwwwmddk  kka   akd                                        
                     kk         dmwwwwwwmkddmmmwmkdmdkk  dkdmk    addd                              
                                kmwwwwwk dmwwwkmwwwwwwwm     aka    dwwmd                           
                                  kkkmmddwwwwwk dwmdd  a       a      kmwwwd                        
                     a               a kwmwwwwk       dw       k         kmww                       
                     m              k  kwwwwma     kkmwwm     ak  ddddk       ka                    
                     km  a              k           akkkma         adddmd     kdka                  
                      ma k k  da   a      kk             kkkd            a      wwk                 
                       ak ma  mw        wwaa            kwwwmk                   wwma               
                         kk   kw      d md         kd    kwwwmd                   dwa               
                                         mmkk kkdmdmwdkd  dwwwwmk                    a              
                                              mamwwwwwwmk  dwwwwwma                 kwwd            
                              md          ak amddwwwwwwwwk  dwwwmk                  kwwmd           
                          a  dwm     a      dwda   kkk  ama                         aadddm          
                            dwwk kk    aa   mwdd          ka    awd                 a  addk         
                            www dwa    kk    wwmk                 k ka              aa              
                            dmkawd           dwmw           d       mw                              
                               kd       k     wwma                   wm                             
                              ka        kk     wmm           k       dwd                            
                             kda         d       m            d       wwa                           
                             dmd         ka      k             m      kdk                           
                              wm          a       a            dk                                   
                         k    wwd                mwk            da                                  
                         a    dwm          a     awm                     d                          
                          k   kwm           k     mwd             k      km                         
                           k    a           d      wm             kma     m                         
                                 dk          m     mwd             mw     dk                        
                                 mwd         ak                    awd     k                        
                                 awwm                 a             kk    wk                        
                                  kdm                 m               m   wm                        
                                   kwm          a     wm              mk  km                        
                                    dw                dwk              da                           
                                                      kmk                                           
                                                       ww                                           
                                                       dw                                           
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    `
};
export const HAND_RIGHT = {
  detail: `                                                                                                    
                                                                                                    
                                                                                                    
                                                                  t   v     vl                      
                                                                 l               t                  
                                                                t   t              vl               
                                                               t   v               vvvt             
                                                              t   v              vlllt  t           
                                                             t                  vl   l              
                                                            t                   t  llv              
                                                          l    t               vl lt                
                                                         l                     tllt       t         
                                                            tl     v           tt      tvt          
                                                     t              vttt    tl  v    t  vtv  t      
                                                                        llll llt    t    t   t      
                                                                         ll  l       l v            
                                             v                         v   l       t t     t        
                                          t                            v  tvl     tt                
                                                v                     vl       ltt                  
                              t  vt   v                               tv  t v   v    l              
                           lt                                            l  t   tt                  
                        l        tt     tt v                             ll t   ttt                 
                      t        tl       vvl                         lv  lll     l                   
                     v      vtv       v t        v v               ttt   l v v                      
                  lv      lv           l          t vv           vtt v  llt                         
                l        t        tt                t t v    ll  tl  t v t     l                    
               t     tv  t      vt   l       v    t tvlt    t    llt  t                             
             l      l   tttv     vvt        t     vllt v       l  t    l      t                     
             l     t     l  tl    t        tt        t         tl t    t                            
            t    l      t        l        vt                   lt tvvl v                            
           t    lt              l         t                l  t   l  tl t                           
          t       tvl          l         t                 lv   vt     v                            
         v       t t             v     vl                      v   t                                
             l                t     vtl    llttltt       t      t       t                           
        l                    t                          vlt  v           t                          
         l v                l     tv  v  l              t v      t       lv                         
                                vl                      ll        v  t   tt l                       
                           v    tl t             l    vl    l             t                         
                                t     t                l                  t l                       
                               vll                    vtt  l       v   v lt l                       
                           vt vtt    l          t     tv               tt                           
                         l     ttt  v          l       v l        l     lt v                        
                                t tl               vtlt  t              l                           
                        v  ttlt               t    t  l                                             
                           l  l   l                l l  t        l                                  
                       l   l l               v    vl           l      t v                           
                       v    tv   l                tl          l      t                              
                       v   tv   t           l  t vtt  l             lv t                            
                          v t  v           l     tv v        v     t  l                             
                       v  tt                    vt  t            vv v                               
                                          t    l l                 l                                
                         lttl                  tt            l   v                                  
                                               v  l                                                 
                                             tt                                                     
                                          t                                                         
                                            ltl                                                     
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    `,
  body: `                                                                                                    
                                                                                                    
                                                                                                    
                                                                   caz zcaxz                        
                                                                  xcczzc        x                   
                                                                 zaz z            x                 
                                                                xa  z            zz                 
                                                               x   x            x     vz            
                                                              x  vc            c      vc c          
                                                             x cz              z      c   x         
                                                           z  z a             x     z    zvv        
                                                          zvzxazx            cz    x    zx xz       
                                                         vzv  vczzz vxc     xzv  vx   x   zxz       
                                                      x cxccc      x    vxxv     c  a vx   vz       
                                                   z    a             cz        c  v xv   zc        
                                                zz                     zz     xx a vz   x  aa       
                                              c                       c vv    x  vz   c   x         
                                           c    xx                    z vz     c x  z   v           
                                        z    xzz x                   c  vvz zz    vc  z             
                               vv      c   cxc   ca                  x  zz        z a               
                             c    cxzz     xz                       avvzx      z  zz                
                         za     c  z   c  v                c        zvvxz    cvc                    
                       c      x  vzz xzx   z ca     x             cx  zc    xzvz                    
                      a    x   xcczz c x zvc  acz v z        c cxzv   cx    c  c                    
                      axxv  c     xc  z  zx      a z         vz c   z xz   czx z                    
                 z    xv  c      x  zxcxzx      cxxx   v vc c  cc       v  av                       
                x   c  vv  xzzzv      c    cv vzxc        cz   c       v c x  x                     
              z    c zcx    zzzzz   vc       vzxaz          cxv vx c  z   c  a                      
              v   z xczzv zz       aa        xx  cccc vxxa  x z  v z  x c  xcz                      
             c cv zccccx          c                   c    xxa        z caxcc                       
                  xczxv                  x            zzxcx ax     ca    vcc                        
                xx              cx      z              a  z  xzv   v  a vvcv                        
                v c            ac xczxx     xa   axz    cxzzvc  xxv    xv z                         
              v xzv            cx         x        z    z v  xav   z     cc                         
         zcvvc  v               c axzvxxcx             c            c   x av                        
          x zxv              c  zz  vz  z         v    z   cx           z  x                        
                            x  c    zxcv              cv  c z         vax  x                        
                               z    xa               a   v         v  ccav cz                       
                              cv   xa            z aczv  x x           xzz z                        
                          x   x   zc c           z xzz                  v  c                        
                          v  z   za               cvcc  v v        a  c   xx                        
                          czcaz                    xczv z             xz                            
                         c xcczv c             x       z          z   xz c                          
                               za                 z     c         x   avx v                         
                        c x                   c  av   c           x cczv z                          
                          z   x  z               c   z x        z  zzz z                            
                         acz                 vaxxx  z          x   ax vc                            
                          c  x                x x   ca        c    v  x                             
                       z      x             a czz  x          a   x zx                              
                              z            x  cz  v          x     z                                
                        czv  x                z   ax         x  xvx                                 
                                          z   z  cx           vvz                                   
                                          c  c  cz                                                  
                                          x    cx                                                   
                                           czxcz                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    `,
  highlights: `                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                        dwwwmdka                    
                                                                      adwwwwmmddda                  
                                                                  a  kmwwwwwwwwma                   
                                                                kk  kwwwwwwwwwmd                    
                                                               ka  dwwwwwwwwwmd         m           
                                                              a  admwwwwwwwwwda        kdw          
                                                            ka   mdmmmmwwwwwmk       awwa           
                                                                 dmmmmmmddmmd       dwwk            
                                                                       kddka       mwm              
                                                       k     kmmkdk               mw                
                                                    kwwd akkkkkakdmwmd           mm         w       
                                                  kwmdkmwwwmmdddmmmmmwk         k        kd         
                                               mwkkakdwwmddmwwwwwwwmmk         da      dwk          
                                            dmda  kkmmmddmmwwwwwwwwwwd          m    kwk            
                                         dmmd     dmmddmmwwwwwwwwwwwd               md              
                                        dka   akk  kddmwwwwwwwwwwwwmk        ka  a m                
                              ddda    kmdkd  kkdmdkmwmmmddkmwwwwwwmd         kk                     
                           dmwwd    aka     mwwwwwwwmkwwwmd kwwwwwmk                                
                        dwwwmk      a       a  ddmwd kwwwwwddmmkkk                                  
                       wwmk         k       wd       kwwwwmwk a               a                     
                    ak       kdddd  ka     mwwmkk     amwwwwk  k              m                     
                  akdk     dmddda         amkkka           k              a  mk                     
                 kww      a            dkkk             kk      a   ad  k k am                      
               amww                   kmwwwk            aaww        wm  am ka                       
               awd                   dmwwwk    dk         dm d      wk   kk                         
              a                    kmwwwwd  dkdwmdmdkk kkmm                                         
            dwwk                 amwwwwwd  kmwwwwwwmam                                              
           dmwwk                  kmwwwd  kwwwwwwwwddma ka          dm                              
          mdddaa                         ama  kkk   adwd      a     mwd  a                          
         kdda  a                 dwa    ak          ddwm   aa    kk kwwd                            
              aa              ak k                 kmww    kk    awd www                            
                              wm       d           wmwd           dwakmd                            
                             mw                   amww     k       dk                               
                            dwd       k           mmw     kk        ak                              
                           aww       d            m       d         adk                             
                           kdk      m             k      ak         dmd                             
                                   kd            a       a          mw                              
                                  ad            kwm                dww    k                         
                          d                     mwa     a          mwd    a                         
                         mk      k             dwm     k           mwk   k                          
                         m     amk             mw      d           a    k                           
                        kd     wm             dwm     m          kd                                 
                        k     dwa                    ka         dwm                                 
                        kw    kk             a                 mwwa                                 
                        mw   m               m                 mdk                                  
                        mk  km              mw     a          mwk                                   
                           ad              kwd                wd                                    
                                           kmk                                                      
                                           ww                                                       
                                           wd                                                       
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    `
};
export const HAND_WIDTH = 240;
export const HAND_HEIGHT = 240;
export const HAND_FONT_SIZE = 4;
export const HAND_TIPS = [[84.72,201.12],[129.36,214.8],[174.72,198.96],[212.64,138]] as const;
