// Generated by scripts/generatePuppetHands.mjs.
export const HAND_LEFT = {
  detail: `l        l             t
t  i   v                   i
  l        i
   v      t i                 l
       t   t
      l l   v
l      t l   t lt                 l
  v     v                          v
   tt    lt    ll
    l li  l    v   tl     v            l
        l  t  l  l  lvt                  l
       l v i  t    il t                    t
         t            l                       i
               t     i                          vl
             l         l                         t  vi
                    l t                                 i
             t      l   t                                 l
                i   l  ti                 l    l          ll   l
               v l  ll litl                v    l    tv    t     t
                        l   v   t          tt         v           lvl
                   v                                   lt             t
              i         t lt  tl    v               v                     l
                      t t     itt          l         t   tl      t    t     l
               l      t       vl        tt l v    vt        l     t   l
                 l             l    vi      l               i     i   l t      v
                    l   t lt  t t   l        lt   t    l      l   v   vli         l
                   l      t                           v               t t v          l
               v          ll   l      t t v             il l              i            v
                 l      t   l  v           v           t l t           v  i  l          v
                t        ll t         tv  i               l             v  vvlt v       t
               t      vi   tt        lvll  tv         t    ltv             i  tlt         t
              t       tt   l         ti    v                 t                llll         i
             t      t      t         t     t                l             l      l
            v      l                 v     l                   t  t             l t      t   l
         t tl   v  tv     l          v     l           l          i    t   l     l  l         t
                i  v        v        l     l           v           t     t             i l
               v             t    v        i  vt    l  v                 i           t        l
               l              l    t              vt  t         l  i     t                ll
                 l          t t   t            lt    l              t
        t  v              v   l   v         v l                  l  i
           l                  i                      i              v     v
            l v  i           l    v             v    l                       t
        t tl  lv t           t                  l                    t       v
           lv    v           v               i       t                v  v v
           ll    l         t  t      t               l  l             v l  vv
           ll                  t   t            l                  i ttl      l
                                                t                     v     l
            i                 l l     l       v  l   vl                  t  v
                                l   t v       t      li  l           t        l
                                 l                 tti   v            l  t   l
                             l  t                ltv                     li
                              v                  t
                                t  ti          l    v  l
                                                    t
                                                 t




`,
  body: ` z   x    x             av
    c      z            zxc
cz   v  c   x            azcz
  x   v      x             zza
   az   a     v             az z
x    x   c     z                x
 vx   c          x           a
   v      x   z  za            c
     zc       z  c    aa           cx
     v        x   c  zaacx x        cxx
      vz  v    xa      x aa          ax c
        z c a                             x
          xv v   xaac  c                  acxv
          va  z    cx  z                    axaa
           ca  z   czz                    aa  c z vz
            aa zz    v  z                    czzac    av
               xz     z                       aa       azz
              az      a  a               x    z c        z  zxz
              c   c        x a     z      a    c       c  c c
              cxz    z z  a  x z   z             c      v   xx
              vx z  v  c ca v c c  ca      zc     c   a  a c  xx   x a
               c  xv     z         x       zzx    cz c   czc     aaa  ccac
               z  x       zc     z  a    az z     czx      zz   c zc
                cza  c    z     c    z    c   z  x   a    zx x   z  xc aax   x
                z c xz       az c     z   c   x  x xx  a       c   xcc x z
                zx z   c x   x     c z     zc      c    z    z c         c       z
                zaz    xca a a  z  a    a     z   x      zca       z               ax
                 v    z  z    x x      z          a         x       c c    zzxa       c
               a  a             a   x  vx            z  x               za      aca    c
              xx       a       z    x   cz  c        c vxv z z           vz      xc      x
             cc          za   x     c    vv   a                             xz   v      cx
            x        z      aac             a x       v     x          c x        cx     cx
           za a      zz      z                x       a      c   v     ca       c   x   x  v
          x         xz       z                z     a        zx  c a   zz a          z      x
             c   ac         xz    c           za    x         zxax c  x x z        x   z  a  c
         xav a a ax       v  x   cz         a zc    vx         vv      ac vz       x  z   vzxac
            z   x v       x     cx xx       x      z a           x  c   x  x          xcxzxaaa
            a             cv   z  z z       zvx zc  ax z          x a
              az          a        zx       cz   x    cc         x z     a
          x    ca           a       x           x   x  c          a         v
        z z c                     x c         z z   c  a          z  a   z
        v    z                      a        ac     c              zzz   az
         a  cx             c   x  zzc        z       z             x     az
         ax   xva          v   v   xa          z a                 c   zx   ac
         xa   xz             c x   x           a z  c z            za        a
         x     aa               z    a        ca v   zx x           a   xxxxza
          azzaax            a    zzvz         x  v   cx             xx z c z av
                            va   acxza          x x a                acv      z
                             acv z x            z  zc  x                v   x
                             xxx      x        ax     cxc              cc   x
                              a     x v        ca   a zz z
                                z a  z         z  z z c  c
                                 vv              xa      x
                                                z      aa
                                                  xvzccz




`,
  highlights: `  kmd      mwwwwwwwwwwm
     wd     dwwwwwwwwwww
      ww     wwwwwwwwwwww
mk     mwd    mwwwwwwwwwwwm
wwm      wm    dwwwwwwwwwwww  k
 kwwk     ww    dmmwwwwwwwwwwwkm
   mwm    dww     mwmmwwwwwwd awwk
    kwwd   wwk     dwwwwwwwwwmk kww
       dw  wwd    wwwk  dwwwwwwwwdk
        dk dww  ww          kwwwwwwm
         k  ww          d  mwwwwwwwwm  k
             w         kwwwwwwwwwwwwwwwdkd
                        wwwwwwwwwwwwwwwwwd
                kww     mwwwwwwwwwwwwwwwwmmd
              k kww     kwwwwwwwwwwwwddwwd  kk k
              m  wwk     wwwwwwwwwwwwwawwwwmk     dwwm
              m  wwd     dwwwwwwwwwwwwmkkkmwwm  adwwwww
                 mww      dkdwwmwwwwdwwwd  dww   mkkkmwwd
                   m  k     d kwkkm kwwwww  mww  kwwk   dm   wwwk
                  kd  k    k  m  ww mwwwwww  kwwm dwwk   kdk  mwwk
                m w  ww      m   ww  wwwwwd  mdmwd aww    k kk  kwk m
                wd  wwd     mw  wmm  wwwwwd   kwwm    wwd   wwwwk   ww
                kk wwm   k  wk    dm wwww    kwwww    dwm    wwm    kd wwwwk
                   ww  kwd kwk   wwwd kd    m  wm   k mwwm    dww  a      www
                   m  wwwwkkw    dwd   wdd     ww    wm wwwk    wd        wwwwk
                  m  mw     k    ww   wwwwk    wwm  kwd  dmwk   ww kwk    dwwwwwk
                    dwm     w k  ww kwww amwwd kww mww      wwwwwwm wm     dwwwwwwd
                k  kww dk   kw   wwwkk     wwwkaww wwk       kmwwwwm w         mwwwwwm
                k  wwdww     dw  www        wwmwwwwmw        dwwwwwwwkw       kd   wwww
                 dwwmww      km wwww         wmwwwwmw         wwwwwwwwww           wwwwk
                wwwmww       m mwwww         w wwwwwww        wwwwwwwwwwd         mwwwww
             a mwwmww          wwwwwk        k wwwwwww        dwdkwwwwd m           wwwww
               wwwww        w dwwwmmd       mk wwwwwmw         dm kmwwd  m           www kd
           d kwwddw        aw mwwwkmk       kw dwwwm wm         w   mwk  w       k    mwm ww
          m   mm           m  dwwm wk       kw  mwwk am             mk   d        a     md ww
              w            m  mww  dk        m  wwwk  w             mmk             ka
         kw  ww  m         d  kk             m  dda   d         k    wwm  w
         dw  wm wk              dm                               k   wwwm wk
         wm kw  w          w   kww                kww             k  wwww ww
         w  dwd            w   kww k         d   dww  w            m dwwwmkw
         w   wkdd          ww  kww m         w   www  m            d  wwk  mk
         m     kw          dw  kww k             www  wk              mwd  kw
                m           w   ww            m  mwwa wm            k kwm  mm
             w              m   dwk           w   wwd dw            d
             w  d           d   mmk d         w   dd   d
          m  wk             kw   km d             kmk  w
                             k       k         w  dwd  wk                 w
                                               w   a   wd                 wk k
                                  w  k         d        d             kk  mw d
                                  wm d                                    km
                               m  dw k               m  k
                               d   wk           k    w  k
                                                m    ww k
                                                 dd  mw





`
};
export const HAND_RIGHT = {
  detail: `                                                                            t             l        l
                                                                        i                   v   i  t
                                                                                        i        l
                                                                     l                 i t      v
                                                                                        t   t
                                                                                       v   l l
                                                                 l                 tl t   l t      l
                                                                v                          v     v
                                                                                   ll    tl    tt
                                                            l            v     lt   v    l  il l
                                                          l                  tvl  l  l  t  l
                                                        t                    t li    t  i v l
                                                     i                       l            t
                                                  lv                          i     t
                                              iv  t                         l         l
                                           i                                 t l
                                         l                                 t   l      t
                                    l   ll          l    l                 it  l   i
                                  t     t    vt    l    v                ltil ll  l v
                               lvl           v         tt          t   v   l
                             t             tl                                   v
                         l                     v               v    lt  tl t         i
                       l     t    t      lt   t         l          tti     t t
                             l   t     l        tv    v l tt        lv       t      l
                    v      t l   i     i               l      iv    l             l
                 l         ilv   v   l      l    t   tl        l   t t  tl t   l
              l          v t t               v                           t      l
            v            i              l li             v t t      l   ll          v
           v          l  i  v           t l t           v           v  l   t      l
           t       v tlvv  v             l               i  vt         t ll        t
         t         tlt  i             vtl    t         vt  llvl        tt   iv      t
        i         llll                t                 v    it         l   tt       t
                  l      l             l                t     t         t      t      t
      l   t      t l             t  t                   l     v                 l      v
     t         l  l     l   t    i          l           l     v          l     vt  v   lt t
          l i             t     t           v           l     l        v        v  i
     l        t           i                 v  l    tv  i        v    t             v
        ll                t     i  l         t  tv              t    l              l
                               t              l    tl            t   t t          l
                               i  l                  l v         v   l   v              v  t
                         v     v              i                      i                  l
                      t                       l    v             v    l           i  v l
                      v       t                    l                  t           t vl  lt t
                        v v  v                t       i               v           v    vl
                       vv  l v             l  l               t      t  t         l    ll
                     l      ltt i                  l            t   t                  ll
                       l     v                     t
                       v  t                  lv   l  v       l     l l                 i
                     l        t           l  il      t       v t   l
                      l   t  l            v   itt                 l
                         il                     vtl                t  l
                                                  t                  v
                                            l  v    l          it  t
                                               t
                                                  t




`,
  body: `                                                                          va             x    x   z
                                                                         cxz            z      c
                                                                       zcza            x   c  v   zc
                                                                      azz             x      v   x
                                                                    z za             v     a   za
                                                                   x                z     c   x    x
                                                                      a           x          c   xv
                                                                    c            az  z   x      v
                                                               xc           aa    c  z       cz
                                                             xxc        x xcaaz  c   x        v
                                                           c xa          aa x      ax    v  zv
                                                         x                             a c z
                                                      vxca                  c  caax   v vx
                                                    aaxa                    z  xc    z  av
                                                zv z c  aa                    zzc   z  ac
                                            va    cazzc                    z  v    zz aa
                                          zza       aa                       z     zx
                                     zxz  z        c z    x               a  a      za
                                       c c  c       c    a      z     a x        c   c
                                      xx   v      c             z   z x  a  z z    zxc
                              a x   xx  c a  a   c     cz      ac  c c v ac c  v  z xv
                          cacc  aaa     czc   c zc    xzz       x         z     vx  c
                                cz c   zz      xzc     z za    a  z     cz       x  z
                      x   xaa cx  z   x xz    a   x  z   c    z    c     z    c  azc
                          z x ccx   c       a  xx x  x   c   z     c za       zx c z
                  z       c         c z    z    c      cz     z c     x   x c   z xz
               xa               z       acz      x   z     a    a  z  a a acx    zaz
             c       axzz    c c       x         a          z      x x    z  z    v
            c    aca      az               x  z            xv  x   a             a  a
          x      cx      zv           z z vxv c        c  zc   x    z       a       xx
          xc      v   zx                             a   vv    c     x   az          cc
         xc     xc        x c          x     v       x a             caa      z        x
        v  x   x   c       ac     v   c      a       x                z      zz      a az
       x      z          a zz   a c  xz        a     z                z       zx         x
      c  a  z   x        z x x  c xaxz         x    az           c    zx         ca   c
     caxzv   z  x       zv ca      vv         xv    cz a         zc   x  v       xa a a vax
      aaaxzxcx          x  x   c  x           a z      x       xx xc     x       v x   z
                               a x          z xa  cz xvz       z z  z   vc             a
                          a     z x         cc    x   zc       xz        a          za
                       v         a          c  x   x           x       a           ac    x
                          z   a  z          a  c   z z         c x                     c z z
                         za   zzz              c     ca        a                      z    v
                         za     x             z       z        czz  x   c             xc  a
                      ca   xz   c                 a z          ax   v   v          avx   xa
                      a        az            z c  z a           x   x c             zx   ax
                      azxxxx   a           x xz   v ac        a    z               aa     x
                     va z c z xx             xc   v  x         zvzz    a            xaazza
                     z      vca                a x x          azxca   av
                       x   v                x  cz  z            x z vca
                       x   cc              cxc     xa        x      xxx
                                          z zz a   ac        v x     a
                                          c  c z z  z         z  a z
                                          x      ax              vv
                                           aa      z
                                            zcczvx




`,
  highlights: `                                                                             mwwwwwwwwwwm      dmk
                                                                            wwwwwwwwwwwd     dw
                                                                           wwwwwwwwwwww     ww
                                                                         mwwwwwwwwwwwm    dwm     km
                                                                     k  wwwwwwwwwwwwd    mw      mww
                                                                    mkwwwwwwwwwwwmmd    ww     kwwk
                                                                  kwwa dwwwwwwmmwm     wwd    mwm
                                                                 wwk kmwwwwwwwwwd     kww   dwwk
                                                                 kdwwwwwwwwd  kwww    dww  wd
                                                                mwwwwwwk          ww  wwd kd
                                                            k  mwwwwwwwwm  d          ww  k
                                                          dkdwwwwwwwwwwwwwwwk         w
                                                          dwwwwwwwwwwwwwwwww
                                                        dmmwwwwwwwwwwwwwwwwm     wwk
                                                    k kk  dwwddwwwwwwwwwwwwk     wwk k
                                              mwwd     kmwwwwawwwwwwwwwwwww     kww  m
                                             wwwwwda  mwwmkkkmwwwwwwwwwwwwd     dww  m
                                           dwwmkkkm   wwd  dwwwdwwwwmwwdkd      wwm
                                   kwww   md   kwwk  wwm  wwwwwk mkkwk d     k  m
                                  kwwm  kdk   kwwd mwwk  wwwwwwm ww  m  k    k  dk
                               m kwk  kk k    wwa dwmdm  dwwwww  ww   m      ww  w m
                              ww   kwwww   dww    mwwk   dwwwww  mmw  wm     dww  dw
                        kwwww dk    mww    mwd    wwwwk    wwww md    kw  k   mww kk
                       www      a  wwd    mwwm k   mw  m    dk dwww   kwk dwk  ww
                     kwwww        dw    kwww mw    ww     ddw   dwd    wkkwwww  m
                   kwwwwwd    kwk ww   kwmd  dwk  mww    kwwww   ww    k     wm  m
                 dwwwwwwd     mw mwwwwww      wwm wwk dwwma wwwk ww  k w     mwd
              mwwwwwm         w mwwwwmk       kww wwakwww     kkwww   wk   kd wwk  k
             wwww   dk       wkwwwwwwwd        wmwwwwmww        www  wd     wwdww  k
            kwwww           wwwwwwwwww         wmwwwwmw         wwww mk      wwmwwd
            wwwwwm         dwwwwwwwwww        wwwwwww w         wwwwm m       wwmwww
           wwwww           m dwwwwkdwd        wwwwwww k        kwwwww          wwmwwm a
         dk www           m  dwwmk md         wmwwwww km       dmmwwwd w        wwwww
        ww mwm    k       w  kwm   w         mw mwwwd wk       kmkwwwm wa        wddwwk d
       ww dm     a        d   km             ma kwwm  wk       kw mwwd  m           mm   m
              ak             kmm             w  kwww  m        kd  wwm  m            w
                         w  mww    k         d   add  m             kk  d         m  ww  wk
                        kw mwww   k                               md              kw mw  wd
                        ww wwww  k             wwk                wwk   w          w  wk mw
                        wkmwwwd m            w  wwd   d         k wwk   w            dwd  w
                       km  kww  d            m  www   w         m wwk  ww          ddkw   w
                       wk  dwm              kw  www             k wwk  wd          wk     m
                       mm  mwk k            mw awwm  m            ww   w           m
                               d            wd dww   w           kwd   m              w
                                            d   dd   w         d kmm   d           d  w
                                            w  kmk             d mk   wk             kw  m
                         w                 kw  dwd  w         k       k
                      k kw                 dw   a   w
                      d wm  kk             d        d         k  w
                        mk                                    d mw
                                           k  m               k wd  m
                                           k  w    k           kw   d
                                           k ww    m
                                             wm  dd





`
};
export const HAND_WIDTH = 240;
export const HAND_HEIGHT = 240;
export const HAND_FONT_SIZE = 4;
export const HAND_WRAPS = [{"x":29.76,"y":169.2,"rx":11.28,"ry":3.36},{"x":75.6,"y":188.88,"rx":12.24,"ry":3.6},{"x":122.88,"y":196.8,"rx":12.24,"ry":3.6},{"x":172.56,"y":180.48,"rx":12,"ry":3.6}] as const;
export const HAND_TIPS = [[29.76,174.56],[75.6,194.48],[122.88,202.4],[172.56,186.08]] as const;
