// Generated by scripts/generatePuppetHands.mjs.
export const HAND_LEFT = {
  detail: `      t        lt             v tt                                                                  
    t  t        lt              l     l                                                             
   vlvt vt     i  v         l    v     t                                                            
       l        lii          l i    v t                                                             
     t l i       tllv         t    t    t                                                           
    t    il       lvt          vl  ltv lvl                                                          
     i t           lttv         vl         i                                                        
            l v  itv tv          vl v   tvv                                                         
          i         itt              i       t                                                      
        ll    v      i  tv                i                                                         
         itl tt vl    l  l      t  t   l   tiv                                                      
           ivtlt  t    tl v        v  llt  vv t                                                     
            i  i   l    ttil         tv  v    l  t                                                  
                         lv  l  l     tlt t v  l t t                                                
                     li  l l  l          tl      llv l                                              
             t li l   t ll    vli         ttv        tll                                            
              l i     v t   il  tv        vtvt        v  t                                          
                       t t    ltlt           vt         t  l                                        
                   v     tvttl  tlt           tt v    iillv  l                                      
                     tl       l  tlv          vtt       vlll     l                                  
                    l  ll  lt vi l v                 l       l v   vtv  l                           
                   ii    tt       v               v t t      l      v     l                         
                          tl    ll  l                t      iiti tt tll      t                      
                         t v  i     tl   v        iill       ltt v lt  llt     t                    
                         li l       t  i i  t         v  t tvtitl   v     l      t                  
                        v t v        tl   l      lt t  v  t vltt      l     i      vt               
                          t  l l   i  i        v  tl   it     v    lllvlli  ltvt    vvv             
                            vl    ill   t   v  ll           il    ilv tt  vi l  l    t i            
                            t t     tilt    llll     tltt  l     v         litl  v    tl            
                          ttil  l il  l       vt  t l    tit                       l  l             
                          lt  t         iv   t    i  l  t t l                 t   l t               
                          lllt    l   v         vlt     t  t v                   t tt               
                         t      t lll   lll        t        t t      v            tt v              
                          lt     ll  lt    i          ili    t l lv               l                 
                        lt        l      i                    t li                  v  t   t        
                        v iv           i    v     l           v l                       t           
                       tvl  lv            l t               l l lt      i                i  l       
                       ivl    t t         v      i l          l     tt                              
                        l      t        l       t             l      l                              
                         tl    v         t         v           v  v       l                         
                          l    t          t lvt l   l              t  i    i                        
                       i       v          l l v                     tlt                             
                         v     vt          v    l    t                li  t                         
                           l vtlt                v                l  ii     t                       
                         lv     v           t v  i    v             t lt  l                         
                             tt  t             tli   t              v  l i   t                      
                          l lv     i                                      v                         
                           i   v   t          ivt l                  l   i    v                     
                              t l   l            t l i  l                tt   v                     
                                il              t l t    l               l                          
                               l lt                i t                  i v l  t                    
                                 tl                 i     i                v   l                    
                                   i                vi    v               i tl i                    
                                                    v                       lt                      
                                                     v il                     i                     
                                                       t                                            
                                                         i                                          
                                                                                                    
                                                                                                    
                                                                                                    `,
  body: `    aa           x      ccz                                                                         
                  x      cav   x  v                                                                 
  z    v           x      xv  a a  z  z                                                             
   c    xxz        vx      az    a z   x                                                            
           x         c       z   az z  x                                                            
     x      z        va       z   z                                                                 
          z  v         a       x   zvxz  vv                                                         
         x a        z  xc       x    x     a v                                                      
           a vz        vzzc       cv  x    z                                                        
            va            xcx      ccz v    xx                                                      
               a          c    a    c c  cx   z                                                     
                vz         xc    xz      xx    z                                                    
             aa  z          x  azv  z  zz a cz  z                                                   
             x cc  a       zz    x a       x cz   v                                                 
              c xz  x     x    zvz     xv  zaacxz   v                                               
                    cz       v   x      az   c  xxx     z                                           
                 ax z  x          c      c    x   cc x  v                                           
                 v  v     z       vc       xv  vc   cacx  a                                         
                  c                zc       cz  v a  z     xz                                       
                   c       cz       za       c   zc  a a    caxxx                                   
                   z              z zxa      azzzzzzv a a zx  v vxz   cz                            
                       z      zv c   zxc cz     ax   v   c    a      x   a                          
                       zac    z      vc z x      x     ca x            v    a                       
                       c        v     x z             x  cazx     x  cz   a   a                     
                      x    v   z     z    ac    z  c v x         xx  a   z  zzvzx                   
                           x     v      cz  x      c    a              z   x  z   a                 
                           az   zzx     ax z v       z     avc            vz       x                
                         cz           z   x       v  xzzxa z  ac        zz    ax    a z             
                         zzz    c        x v        z          zz         z    ca c                 
                         z          z    a   x       zaac   a   xz           zacvzz cc v            
                                v     zc  aaz            z       cv              v     vx           
                              aa       x   xxz     zxa   xc   a   az            v       xc          
                          x z         xc   vc  cz   xaaaz      c   xz                 c  xz         
                         x      v      cz   a             c     v   vz             vvz   ac         
                           x   axc     xa   z    x         c      z  vz                  x          
                            a a  x       v   a              xc   zz  zzx              xa  za        
                           x   a             vv  xc          x a  zzzcz                    a        
                           xc           c    v c  c            vz     a                             
                       z xxc  z              z    c             zz    a  z                          
                       xv     c           vvz a  x                    z                             
                       zz                  z     a              z      c                            
                        a  c               a   xza  x            x     zxxvz                        
                           x  c             a    x                a x    a z                        
                        xc  c                c       c             xv   z ca                        
                            xxx                   c                  a   z z                        
                          x                       zac x              xz   x                         
                           z      z            x  z  xx              cca                            
                             v    z                 cz z                c  v                        
                             a     z            x   v                 v a  z                        
                               z   az            x      a              cv   a a                     
                                c   x            x    c  z                                          
                                   c                  v  z               v   c                      
                                    v              z   c                   c                        
                                                     a    z                   a                     
                                                      c   x                                         
                                                         az                                         
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    `,
  highlights: `                  mwwwwm     w                                                                      
     wk            dwwwww    mw  a                                                                  
                    dwwwwm     w  k                                                                 
    d                dwwwww     m                                                                   
    m     k           dwwwwwk                                                                       
       kk  d           kwwwwwd                                                                      
        mw  d           dwmwwwd                                                                     
          w  d           kwdwwwd      dd    w                                                       
            k              kdwwwwk     ww   w                                                       
                             wwwwwk     wk                                                          
                           ddkd      m                                                              
                             wwwd                                                                   
                  k          mm   wm       d                                                        
              m   d               k dd                                                              
                   k              dwwwk                                                             
              k  d                kwwwwm      dk   mw                                               
                     w             mwwwww      kdk  k                                               
                  k  wd             dwwwwwk      mwm     k                                          
                     kk              dwwwwwd       ww                                               
                                      mwwwwww      mw k                                             
                                       mwwwwd          w                                            
                                        d  wwwmk       dw      mmkkd  dkw                           
                               k       k   wwwwwm     k  w              kwww                        
                        w      m       w  wkkwwwd      wd                  www                      
                       dk                    mww    d   d             dwd                           
                         d             d     mwm         k              kwd    wkm                  
                         m             w  w   m          dw                     kww                 
                           d   kd      w   d              m                      kww                
                               w          m                 ddd                    wwk              
                              mw          wwk                wwm                                    
                               k              dd      kd     kwww              dd    ww             
                                              km      wd       www                   mww            
                             kwm             wm          kdd    mkd                    wk           
                            kwwm             wwdk          ww      k                    k           
                            dww              wwwm           wm     wm                dk   k         
                             w kw       m     wwmm                  k                               
                          k     k       ma     wm                      w                            
                          k  d           w    k                        wk                           
                            ww           d    wk d             k       ww                           
                           kww                 m  w             ad     wwm                          
                           kwwk                d  wm             ww     wwk                         
                            wwm                   ww              wm                                
                        k   mw                    wwm              w    m                           
                                            d     mww                    w                          
                               k             w     wwd                      k                       
                               ww            km                            mw                       
                              kkww            d    m                       kwk                      
                            k   mw                 w  d               mw    wk                      
                                 mw                   mm               w    dd                      
                                  w                  dmw                     w                      
                                   m              d    ww                d   wk                     
                                    k             kd   dm                 m   m                     
                                                        wd                    w                     
                                                        dd                                          
                                                         w                                          
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    `
};
export const HAND_RIGHT = {
  detail: `                                                                  tt v             tl        t      
                                                             l     l              tl        t  t    
                                                            t     v    l         v  i     tv tvlv   
                                                             t v    i l          iil        l       
                                                           t    t    t         vllt       i l t     
                                                          lvl vtl  lv          tvl       li    t    
                                                        i         lv         vttl           t i     
                                                         vvt   v lv          vt vti  v l            
                                                      t       i              tti         i          
                                                         i                vt  i      v    ll        
                                                      vit   l   t  t      l  l    lv tt lti         
                                                     t vv  tll  v        v lt    t  tltvi           
                                                  t  l    v  vt         litt    l   i  i            
                                                t t l  v t tlt     l  l  vl                         
                                              l vll      lt          l  l l  il                     
                                            llt        vtt         ilv    ll t   l il t             
                                          t  v        tvtv        vt  li   t v     i l              
                                        l  t         tv           tltl    t t                       
                                      l  vllii    v tt           tlt  lttvt     v                   
                                  l     lllv       ttv          vlt  l       lt                     
                           l  vtv   v l       l                 v l iv tl  ll  l                    
                         l     v      l      t t v               v       tt    ii                   
                      t      llt tt itii      t                l  ll    lt                          
                    t     tll  tl v ttl       llii        v   lt     i  v t                         
                  t      l     v   ltitvt t  v         t  i i  t       l il                         
               tv      i     l      ttlv t  v  t tl      l   lt        v t v                        
             vvv    tvtl  illvlll    v     ti   lt  v        i  i   l l  t                          
            i t    l  l iv  tt vli    li           ll  v   t   lli    lv                            
            lt    v  ltil         v     l  ttlt     llll    tlit     t t                            
             l  l                       tit    l t  tv       l  li l  litt                          
               t l   t                 l t t  l  i    t   vi         t  tl                          
               tt t                   v t  t     tlv         v   l    tlll                          
              v tt            v      t t        t        lll   lll t      t                         
                 l               vl l t    ili          i    tl  ll     tl                          
        t   t  v                  il t                    i      l        tl                        
           t                       l v           l     v    i           vi v                        
       l  i                i      tl l l               t l            vl  lvt                       
                              tt     l          l i      v         t t    lvi                       
                              l      l             t       l        t      l                        
                         l       v  v           v         t         v    lt                         
                        i    i  t              l   l tvl t          t    l                          
                             tlt                     v l l          v       i                       
                         t  il                t    l    v          tv     v                         
                       t     ii  l                v                tltv l                           
                         l  tl t             v    i  v t           v     vl                         
                      t   i l  v              t   ilt             t  tt                             
                         v                                      i     vl l                          
                     v    i   l                  l tvi          t   v   i                           
                     v   tt                l  i l t            l   l t                              
                          l               l    t l t              li                                
                    t  l v i                  t i                tl l                               
                    l   v                i     i                 lt                                 
                    i lt i               v    iv                i                                   
                      tl                       v                                                    
                     i                     li v                                                     
                                            t                                                       
                                          i                                                         
                                                                                                    
                                                                                                    
                                                                                                    `,
  body: `                                                                         zcc      x           aa    
                                                                 v  x   vac      x                  
                                                             z  z  a a  vx      x           v    z  
                                                            x   z a    za      xv        zxx    c   
                                                            x  z za   z       c         x           
                                                                 z   z       av        z      x     
                                                         vv  zxvz   x       a         v  z          
                                                      v a     x    x       cx  z        a x         
                                                        z    x  vc       czzv        zv a           
                                                      xx    v zcc      xcx            av            
                                                     z   xc  c c    a    c          a               
                                                    z    xx      zx    cx         zv                
                                                   z  zc a zz  z  vza  x          z  aa             
                                                 v   zc x       a x    zz       a  cc x             
                                               v   zxcaaz  vx     zvz    x     x  zx c              
                                           z     xxx  c   za      x   v       zc                    
                                           v  x cc   x    c      c          x  z xa                 
                                         a  xcac   cv  vx       cv       z     v  v                 
                                       zx     z  a v  zc       cz                c                  
                                   xxxac    a a  cz   c       az       zc       c                   
                            zc   zxv v  xz a a vzzzzzza      axz z              z                   
                          a   x      a    c   v   xa     zc cxz   c vz      z                       
                       a    v            x ac     x      x z cv      z    caz                       
                     a   a   zc  x     xzac  x             z x     v        c                       
                   xzvzz  z   a  xx         x v c  z    ca    z     z   v    x                      
                 a   z  x   z              a    c      x  zc      v     x                           
                x       zv            cva     z       v z xa     xzz   za                           
             z a    xa    zz        ca  z axzzx  v       x   z           zc                         
                 c ac    z         zz          z        v x        c    zzz                         
            v cc zzvcaz           zx   a   caaz       x   a    z          z                         
           xv     v              vc       z            zaa  cz     v                                
          cx       v            za   a   cx   axz     zxx   x       aa                              
         zx  c                 zx   c      zaaax   zc  cv   cx         z x                          
         ca   zvv             zv   v     c             a   zc      v      x                         
          x                  zv  z      c         x    z   ax     cxa   x                           
        az  ax              xzz  zz   cx              a   v       x  a a                            
        a                    zczzz  a x          cx  vv             a   x                           
                             a     zv            c  c v    c           cx                           
                          z  a    zz             c    z              z  cxx z                       
                             z                    x  a zvv           c     vx                       
                            c      z              a     z                  zz                       
                        zvxxz     x            x  azx   a               c  a                        
                        z a    x a                x    a             c  x                           
                        ac z   vx             c       c                c  cx                        
                        z z   a                  c                   xxx                            
                         x   zx              x caz                       x                          
                            acc              xx  z  x            z      z                           
                        v  c                z zc                 z    v                             
                        z  a v                 v   x            z     a                             
                     a a   vc              a      x            za   z                               
                                          z  c    x            x   c                                
                      c   v               z  v                  c                                   
                        c                   c   z              v                                    
                     a                   z    a                                                     
                                         x   c                                                      
                                         za                                                         
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    `,
  highlights: `                                                                      w     mwwwwm                  
                                                                  a  wm    wwwwwd            kw     
                                                                 k  w     mwwwwd                    
                                                                   m     wwwwwd                d    
                                                                       kwwwwwd           k     m    
                                                                      dwwwwwk           d  kk       
                                                                     dwwwmwd           d  wm        
                                                       w    dd      dwwwdwk           d  w          
                                                       w   ww     kwwwwdk              k            
                                                          kw     kwwwww                             
                                                              m      dkdd                           
                                                                   dwww                             
                                                        d       mw   mm          k                  
                                                              dd k               d   m              
                                                             kwwwd              k                   
                                               wm   kd      mwwwwk                d  k              
                                               k  kdk      wwwwwm             w                     
                                          k     mwm      kwwwwwd             dw  k                  
                                               ww       dwwwwwd              kk                     
                                             k wm      wwwwwwm                                      
                                            w          dwwwwm                                       
                           wkd  dkkmm      wd       kmwww  d                                        
                        wwwk              w  k     mwwwww   k       k                               
                      www                  dw      dwwwkkw  w       m      w                        
                           dwd             d   d    wwm                    kd                       
                  mkw    dwk              k         mwm     d             d                         
                 wwk                     wd          m   w  w             m                         
                wwk                      m              d   w      dk   d                           
              kww                    ddd                 m          w                               
                                    mww                kww          wm                              
             ww    dd              wwwk     dk      dd              k                               
            wwm                   www       dw      mk                                              
           kw                    dkm    ddk          mw             mwk                             
           k                    k      ww          kdww             mwwk                            
         k   kd                mw     mw           mwww              wwd                            
                               k                  mmww     m       wk w                             
                            w                      mw     am       k     k                          
                           kw                        k    w           d  k                          
                           ww       k             d kw    d           ww                            
                          mww     da             w  m                 wwk                           
                         kww     ww             mw  d                kwwk                           
                                mw              ww                   mww                            
                           m    w              mww                    wm   k                        
                          w                    wwm     d                                            
                       k                      dww     w             k                               
                       wm                            mk            ww                               
                      kwk                       m    d            wwkk                              
                      kw    wm               d  w                 wm   k                            
                      dd    w               mm                   wm                                 
                      w                     wmd                  w                                  
                     kw   d                ww    d              m                                   
                     m   m                 md   dk             k                                    
                     w                    dw                                                        
                                          dd                                                        
                                          w                                                         
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    
                                                                                                    `
};
export const HAND_WIDTH = 240;
export const HAND_HEIGHT = 240;
export const HAND_FONT_SIZE = 4;
export const HAND_TIPS = [[85.44,206.64],[136.32,220.8],[184.56,212.64],[216.48,145.68]] as const;
