// Generated by scripts/generateSigil.mjs — run it again rather than editing.
export const SIGIL_LEFT = `                           jlxktltlj    lzi             
                             vz        idi       l      
                              aj tltl  zv        z      
                              zv    jltvz       zi      
                              vzi        tvj    v       
              j               z z          lt  lj       
            itkzl             izlj    ij    izlz        
              xv              jktatvtlt       wltvzlj   
              i          jltltlxltkt   jltlj xi  jvtit  
                j              v  jl       lxi     vj   
                 xi            z   tl      zi           
                  zi           v    zl   izi            
                   zl  jl      jl    zl lz              
                    jlzl        z     tvt               
                      lzi       v    jvt                
                  tlzltlzvti    x  lti           v      
               tlt zi      tltixmzvj         j   tl     
             izi  jv      jlzvxmwmzlt        iz   z t   
                  v            jmtlj          iz  vzi   
                  z             d  lzi         vtaxi    
                                a    tlt       xlt      
                                x      izltltltv        
                                v         ltl it        
                                z           jvxi        
                                v              jvtl     
                          ji   lz  lt             jltl  
                           jltljktlj                    
                                z                       
                                v                       
                               lt                       
                               z                        
                               v                        
                               z                        
                               v                        
                              iz                        
                              z                         
                              v                         
                             vj                         
                             z                          
                            jl                          
                            v                           
                            z                           
                       jlj jv                           
       l                 ltktltlti                      
       jkj  it             z                            
         v iz              v                            
        i vz              lt                            
      j z di              zl                            
      vjljv               vz                            
  jltltktkz               zv                            
   ji   kdaj              kx                            
  tlzvzktkwi         itltkwmxltl                 lti    
   tltltvzvwvtlj  itltlzvdmwkzvti           itltl       
         iz tatitljitlti atv    tltltlzltltvxvj         
         ti ljaxvtlj  v ix z           tv     lzl  j    
    jltltlzlzvj       zlxv v            jvj    izvxi    
             z        id z                kj  lz  lz    
        t    iz      lzltv                 ktlt    izi  
         tltltlzvtltkt  kt                vzv        z  
               kj jvt   zi             itvx zi          
              lj zk  tltkdltlti      jljlz              
              zlzvjlt   zv              t               
             taj z   t  vz                              
           lzij  iz t   zv                              
        ltl       v itltktktl                           
       ij         tk    z z                             
                  vzv   v v                             
                 ltktl  z z                             
                ltvj tv vjv                             
                jvj   j  kt                             
               j         d                              
             ltv         vt  l                          
            iz z         zv  z                          
       l    x  v   ltltktkxl v                          
       z    v  z      izv lj z              i           
  jltltkzl  z  v      z z  kzktlti        jlxlt         
      izatltkj jl lti vzijvx                v           
     lxvzltltvxvdlj jixkzktktltlj           j           
   jkzi        jvt    vdi  jl            j              
   v             vj  izv    z           zi   i  j  lt   
                  k  z z    v         izi    z  vtlj j  
                   kxi lj j z     jvtlt      v vditvti  
                   zvj  v v v      jkzltvti  xkzkzvjlt  
                   i vt ziz jl   izl   ltkxazkjlzl      
                      itizv  z tvt       z jadvjv       
                        jkwkzatijl       v vxijkt       
                      itldmwmdltl          zk  x        
                   ltltlxkwizktltl        jmtlxltltltl  
               tltlj  izlzv  xvj  ltltltltazlzvtltltlj  
           itvti    tvtlt z  v lzi      zk   itlzi      
         tlt     tvxvzi   l  z   tvj  lzk        tvj    
         itltvxkzlj          v     lzkjij          i    
   tltltltltlwi              zi      jlzi               
            tkj               z         tkti            
            v l         ij  ltktlti      jvjvtl         
           vj            ltlj z           jv   ltlti    
          ix                  v            tl      ji   
       itvtat                 z            id           
   tltlt  v lt               ti           ixiz          
          z  lzi             v           vz  v ij       
          v    zlj           z        ltlj   dlt        
          j      i           v      jlj     ziz         
                             z             zl v         
                             v           lzi  t         
                            iz         tvj              
                            z                           
                            v                           
                            z                           
                           z                            
                           vj      izi                  
                           zlxi  jvtv                   
                      jl   v ldlzl  z                   
                        ltktvzkwkti v                   
                          xvjltlxltkj                   
                i        jkzl   iz z                    
         itlj  lj    lj   xi     ktl                    
            iziz  izl     v      dl                     
              ja lz      it     jk                      
               jat       z   z jv                       
                x        v  tkzl                        
               tiz   tltldlzmwkt                        
              tijlz    itkxvzaj                         
   ji         ixvtlzvtkzlz   z                          
    jltltltltltlxitktl  tv   i                          
            itltvtvz    vz                              
     ltltltlt     zv    ja                              
    lj            vz     w jl                           
                  zaz    mzl                            
                  lxlxvzlzv                             
                   atvtlzkdltlt                         
                   tv    zv                             
                    jv   vz                             
                    izv  zv                             
                     itltkxlti                          
                         zv                             
                         vz                             
                         zv                             
                         iz                             
                         zv                             
                         vz                             
                         zv                             
                        tijv                            
                  ltltljv  z                            
                       vtltv        ji                  
                       z   z        v                   
                      zi   v       lt   j               
                     jl    jv     izi   v               
                     v      z     xit   z               
            l       v       v    xlz   jl               
        zitvj z jltkj jltltlxltldidkzltaxltl lz         
   jlti kz   tvti vj    l   v ldawlzlxvdazlzvj          
      tvx    v   vj     z   xizlx jkzkdajvxl            
        lt  lx   j      v   vzlj   z   x z tl           
  ji     vj   z         z jlxv     v   v v              
   tltltltkj  vj       zmwvtv     iz  vj z              
          tltltvtltlzvzawmxvdvtlt x  lzltltlt           
                        k   v   itlxlti                 
                        z   z     zi                    
                        v   v                           
                        t   z                           
                       ti  tktitlj                      
                        jlt zij                         
                            v                           
                            z                           
                            v                           
                            z                           
                            v                           
                            z                           
                            v                           
                           vj                           
                           z                            
                           v                            
                           z                            
                           v                            
                           z                            
                          jl           ltl   l  z       
                          v          jltlzkt z  v       
                          z               jvzv lj       
                          v                 idlx  it    
                          z                  vti ld     
                          v                 ixv vtv     
                          z                 zatkzkzltl  
                          v                jkzv   ixvt  
                      j   zltltlt         jaxijltvxiz   
                      itltvt             zkzlti vz tlj  
                           v           izl       v      
                           z   j     tkz     ti  z      
                           v   v   lxv        tvjv  ti  
                           x  ldizvt            vt jv   
                           vjlwmdl               lzv    
                          lxldvwkzlj             jv     
                   itltltljvzi m vtitltl        tl      
         jltltlzktlt     tlzi  tk izl   ltlt  izl       
               vj      lzl  z   jvt jlzi   itad         
              ltl   izvj    v     izltlzatkxvj          
       l      x  izlt   tltlxltltlj     z jltltltlti    
       jltltlxvzlj          v           v               
      jltltltk v            tl        tvt               
     jl      z z             z  itltlzvx                
             v v             v        xi                
             j tl      jl    z       zi                 
                xltltltl     iz      i                  
               zlzi           v                         
           itlzi  ti          z                         
          ij       ti         it                        
                               k                        
                               ti                       
                                z                       
                                v                       
                                xv      z               
                          iti   vtl     vti             
                            tltlz zi   lxi              
                 t             jkz xlzv v               
                tkti            z zazi lj               
                 t              v  jv  x       j        
                                z   z ti      tl        
                                v   vjv      tv         
                          j     z   zktlt   tl          
                          itltlzvtltmtltltizl           
                               v   kt  itlzvt           
  lti                          z jvj      ltvtvj        
    tlti                    z  ktv          jv iz       
  i    tvti                 v idl            z   t      
  jvti ltltlzvtl          tlwmxk             v          
    ixaj    v  jltltltltltltmw z             jl         
   vzvz     z               zkzktl            t         
  ij ti     i          ji   ljaj jltlti                 
      j                 z     zvzi    tltlt             
                        it    v  tltltltltvxvj          
                        tktltlz   j                     
                         tl  tltlti                     
                          z  v                          
                          v  z                          
                     vtijiz jv                          
                       jljlxkj                          
                           vz                           
                           xv                           
                           a                            
                           x                            
                t         tk                            
                v    j    vz  itltl                     
                z    itltldkzvj                         
                v      tvwaj                            
       l        z    vti vdvj                           
     t z        lj tlj   zv lt                          
     ltv         vzl     vt  lt                         
      ld         xvtltlj x    v                         
       ixi       iz     ja                              
        vxvtltltltktltltkxlj                            
    tltlj         jl i itvtltlzi                        
   ti              zijldlz                              
                    z ti v                              
                    ixv  z                              
              z  itltat  v                              
             zizvj jk vj z z                            
             kj    l   ljk v                     vj     
             zitltltlj  lxiz                   jv       
        ti  tltlzv       vdat                 tv        
         zl vtmzv    tlzkwmwmtlt             tvti       
          jlzktk  jltvxvzkwatlj            lzi  tlt     
   jltltlzvzawmzvxktlt jvxvz  itlti      tlt      izi   
       lzkjltadaz     zktizv      tltltlzl     lti  t   
        vxktl  jkzljvdvj  vt            itltltlj        
      jkdl    jlzaxvj     z                             
     jvditvzvtl           v                             
  jltltv                  ti                            
       z                   z    l                       
       it             jltltktltl                        
        i                  z                            
                           vj                           
                            v                           
                            z                           
                            v                           
                            jv                          
           j        lj       z                          
           izi     vt        v                          
             zi   vj         jl                         
        j     zi k   itltlj   z                         
        lt     zvtktlj  v     v                         
         vj    vxl i    z   t z                         
          lt   z        v   ixv                         
           lt  v    z   zi   id                         
            lz z  lzazvzvd jl vt                        
          tvtidl    z ti ixktlzvtltl                    
         jv   izi      jlxljljkxl                       
   idl   i      zi        jlxiz z                       
    idv          zkj     j   tajv                       
      tkzi   ltlti lt    itltlxkxlti                    
        lxkzlj      izi       v v                       
        tvj           jvj     dit                       
      lzi               vt    az                        
    jlj                   zljiwl                        
    l                     itkwmzlj                      
                             awv                        
                              mjltlti                   
                              xv    tltlj               
                              v vt      itltl           
                             it  itlj       jvxv        
                        ltltlxltlti itltltltlt          
                             v                          
                             z                          
                             v                          
                             z                          
                            z                           
                            v                           
                            z                           
                           jv                           
                           v                            
                           z                            
                          jv                            
                          v                             
                          z                             
                          v                             
                         lj                             
                       t z     tlt                      
        j             jl v      zv                      
      ltatl           v lxltlti izv                     
       idizi         iz jl    tvtaz       tvt           
        i  z         z  v        jkt  vdkxvt            
           lz  ltl   v  z      itlzvzat         jlt     
          izvzlj  ltlz  v         vwl         izl       
          j         tktlxltltlj    a        tlt         
                     z  v          x     tlti           
                     lj z          v  jldi              
                      v v          dlzi it              
                      zlz     jltlt      v              
                      iwmtltltl          j              
                    jlxmwati                            
                       xmtlj                            
                       vdl izlti                        
                       zvtl v  jltlt                    
                       v  jlxi      tltlti              
                   ji  z   tizltltltitltlxv             
                    tltktltkti     ij                   
                       z   z                            
                       v   v                            
                       jl vj                            
                        z z                             
                        v v                             
                        z z tltlt                       
                        ktkt                            
                        z z                             
                        v it                            
                        ti v                            
                         z z                            
                         v v                            
                         jljl                           
                          z z                           
                          vjvj  l  j                    
                          jktktlxlti                    
            v              z zi v                       
          tvwlt            lj x z      iz               
            ljv             v iza   itlxvxltl           
             v        jltltlxltvxitkzltldat             
             xi             v   axlj    vjktl           
             vjv            jl  zk      z jv            
             z               z tijv     v  z            
   ldkzltltltk               a v  jk   it  i            
   t tv      x               dit   jv  t    i           
  ti  jlti   itizi           kx             jl          
   zi    tlti vx            ixv              ti         
    zvtltltijltati      tvtvwmwltvt           z jvt     
    ixl          jltltltltltkwmti            jktl       
   vzvj                      awlzvzi      jlxlj         
  lj  vj                     zkdijltvzvzltl izv         
       izi                   vtlzaj   jlzvzvj jvt       
                             j zvtktltltltltktltvtltlt  
                               vz jvt        v          
                               wi   izl      z          
                               v   i  jkzi   v          
                         jltltvwltlj   z tlzkx          
                              zv       vtltljktlt       
                              vz     jlz    v           
                              zv   ij jv   lt           
                           jltkxltljljv   it            
                              zv    jkx                 
                              vz  ltlx                  
                              zvtlj  i                  
                              vz                        
                              xl                        
                              a                         
                              d                         
                             tkj                        
                            jatktltlti                  
               j             z z          i             
               v      z     jl lt       jlxl            
                kj    v     v   k         v             
                 vj    vtlj z   tl                      
            ltltltkz   x    v    z                      
                   itltlx  it    iz                     
                       jkzlxltltltlj                    
                         v v i     kj                   
                         jvz z      k                   
                          tk v       i                  
                           diz                          
                          tldmz                         
                         tktmwmxvt         jl           
                          z  k  jltltlt     z           
                          k  z    i   itktltvzltltlti   
                          z  v   lt      v   vj         
                          v  t  iz       z    v         
                      tlt xi    z       ja    z         
                        itvjltlzl     izad    v         
                          z    k   izlzvjv    z         
                          v   it   jlti vj  izk         
                          z   z         jlzlt z         
                          v   v        zvj   jv         
                          z  lt              i          
                          vtlxltltlt                    
                          z  v                          
                          v  z                          
                          z  v                          
                          v  z                          
                          zi v                          
                           z z               jltlj      
                           v v   ij   jvj  itl          
                           ziz    lzi   ltlt  iz        
                           ixktltltvxl   lx   z         
                           jkzktltljizl   iz zi         
                            z z     tlzi   ixl          
                            ljv     i  z   taz      i   
                             vjl       v  tl vzl   vj   
                             z z       z zl  z t tvj    
                             v lt      vxi   it ti      
                        i   ixijati   lz      at        
     lti   lz  it       jltljlzijv   lt     tvj         
     z jvxkjv  z              v  tijl    jlti           
     ljixvtlxltv           i  z  ldi   lzl              
  itltaz  lzvjv            z  vjlj jlzlj                
       vj  izaz           jkjvxltltl                    
        vt   taj        ltmwmxmj     ti     l           
      tltitl  jaxlj jlzvzltaxiz       zi  jk            
   tltltvzkxaxvtvzkzlj     z tkj       xitlti           
          jvt              l  zvzlj   tvt               
         zl                   vz  itvzvtltlti           
  jltlzlzi                    tv      jvj               
      ixi                tltltaxltlj    vj              
  jltltk                      zv         kj             
      v                       vz         zk             
      j                      ltv        jltl            
                           j zvzltlj    l  j            
                           itkz                         
                             zv                         
                             vz                         
                             zv                         
                             vz                         
                             tk                         
                              x j tlt                   
                           jlzatlti                     
                             vz                         
                             zit                        
                             v v                        
                            lt ti                       
                            z   z                       
                            v   lj   jlj                
                            z jltktltl                  
                       jltltktltltv                     
                            z     ti                    
                           ti      zi      ji           
                           v        zi      z jltlti    
                           z         zi     ixl         
                           k          xvtltvtkxi        
                           z   z      ij   tlzlj        
                           v   kj           zvtv ij     
                       j   z  vwaj         jktaxvtlt    
                       itltktvwmwmdktltltltljvz         
                           z tlwvtkxkxlzltltlwvtltlj    
                          tkz  vx    lzaxvtvtltltltlti  
                        itkd   jizi     vjlwkz          
                    jltvj  k      tlti  dkzvtldv     i  
             jltltldaj     d         tltktlzkt zatltlj  
                   ax      aj          it   xv v vj     
                   zv      zv          z   tijvx  vj    
                   vxi ltltkdltlti         k  tvzvjl    
                   zvtltlj zv             vj            
                   vxvtltltvz                           
                    vj     zv                           
                    zitltltld                           
                     t      atl                         
                            d                           
                           ja                           
                           vz                           
                           zit                          
                          jv v                          
                          v  z                          
                          z  v                          
                   ti    zi  z                          
                    jltltktl v                          
                        vj   z                          
                       it    v                          
                      idlj  iz                          
                      z  itltktltl                      
                     xi      z                          
                    zi       v                          
                   zi        z                          
        j         zi     i   v                          
        v        ti      z   z                          
        zi               v   v              jv          
         z             jkxi vj               z     j    
       ltlz          ltkwmdvdltlti           iz   zl    
    izl   izl      jltltmdlzk                 v it      
     itltltltvtvtlti   k v ixlj               xmzlt     
              it    k vj z  v lzi           lzijv itlz  
              z     jkt  l  z   tlt      itlj   j       
              v     lxi    tl     itljltlj              
              z    lt z    v         idlj               
            itvx  lt  vj   z         zi izlt            
               kzvt  ijv   v       iz      itlzi        
               jktvzi lxltlxltlt               jltlj    
               vzltltltlxlx                             
             jvz  ltlj  v v                             
            tl iz       z z                             
          izi   vj      vzi                             
         vz      k       a                              
       tvj        k      z                              
     izl          jk    zv                              
    lz             zatltkxlt                            
                   k vj zv                              
                  lzvtlzvz                              
                 vt    idv                              
               tv       ati                             
            jlti        d                               
           ji           a                               
                  tltltlxlt                             
                       zv                               
                      jvz                               
                      v v                               
                     it z    ij                         
           t       jlxltktltlj                          
           v        ti  z  i                            
    ltltltkx       jl   v  z                            
         ljv            x  v                            
           ti           v  x                            
            z          ixlwmxlti                        
            vj          ixmwk                           
   it        v      tltlza awvtlj                       
    itltltltltktltltijvz z zvx  itlti     l             
                  tvzi   v v ldl    jltltvt             
     jltltltltltkt z     zij   tvzi    tkxkxvj          
               iz  v i    xltltv vxkxvzltltlzi          
               z   ti ltltv        tvti      j          
               vj   z     z         jatltlt             
              lzv   kj    lj       jvz    i             
        jltltljld tvjk     v         lt                 
             tazvxi   k    z         jv                 
         itlti   lj    kj  vj  itltltvz                 
                            v        zi                 
                            z        vzl                
                            lj      iz jvti             
                             v      j     tlti          
                             z                          
                              z                         
                   tvj    ij  v                         
                 itl      z   ziz    i                  
               jvzltltlj tl   vz     ti                 
  j           tl       itkt   x       di                
  izi        tl          zlt  mt      a                 
    zi      zltltlti    ti itlwi     vz                 
     tvj   tl      jltljvtltltkdltltvwl                 
       vt jv   ij      lz     z zltlxmtvzkt             
        izk  zlt        v    tktkxkzvd    i             
    tlzvtlzvzi          tijlziz   xkzlz                 
   t  v     lzi          wvtltkj jvz jajit              
      z       tvj        v    zitlxltktvxvzlj           
      l         ltl      jl   v  z   j  ltixiti         
        z         jvti    z  vx xi       i  z           
        v            jlti  z zvzi           l           
        z               jlzlxkd                         
  itltvjv                 lzmwmti                       
     izlz            ltltlxvxkxi                        
        vj    i  tltlj tlt tlzvjlt                      
         vj   xvti  jlzi izl vt  vzlj                   
          vtltv  tlzi  tvt   z  lt  vzlj                
          tkzvxaxltltltij    v  z    v itltlti          
         tlzlxi         ltltlxlxlt   z       jltltlj    
   itltlti  jv               vjl     v                  
   j        v                zv      zl                 
            z               ziz   jlzvtvj               
            v               vzi izltlt  ltltlti         
         izvxi             ixktlj  iz                   
    ltltlj tijltltltlj    itkdltltvz                    
  jlj    ltlz              vjl    t                     
            v              zv                           
            z              vz                           
            l             vjv                           
                          z z                           
                          v v                           
                          z z                           
                         ti v                           
                         v  ti                          
                         zitlxltltlj                    
                     it  v   v                          
              i       vj z   z                          
              jk       v v   it                         
               jv    tlxvxltltkj                        
                zl     ktv    tl                        
               zltl ita  z     z  i          j          
              j   tl vj  v   ijit tl         v          
                   tvz   zl   itatid t      vzvj        
                    ja   vz      azvxktltltlt  vt  it   
                      vj zv        dmj    lzlzaxvt x    
                       lzaz        atltltkt j  izadi    
                     jltlwmxltlj  kj  itvzvzltltldi     
                     itlzmwmdvzkzaxvxvzvt      izltlti  
                         zatlxvj    v         lz     t  
                         izvj jvzvzlt       jvt         
                          v vzv   izkdvti  zv           
                          z   dlt     jlzkdkzi          
                          v  tl itltltltltltltltlti     
                          z  v                          
                          v  z                          
                      tltlzvtktlt                       
                           z zijltlj                    
                          jktkti                        
                           z z                          
                           ljv                          
                            vz                          
                            zv                          
                            vx            i             
                             mj    lj    vxv            `;

export const SIGIL_RIGHT = `             jvt    itltlxkti                           
      t       jaj        vz                             
      v        zv  tltl id                              
      jv       vzlti    zv                              
       z    izl        jvz                              
       it  lt          v v               i              
        vtvj    ij    itvj             tvxlj            
   itvzltm       ltlzldlxi              zk              
  ljlzi  jk itlti   lxltktltlti          j              
   iz     jkt       ti  z              i                
           jv      tl   v            jk                 
            jvj   tv    z           jv                  
              vt tv    ti      ti  tv                   
               lzl     v        tvti                    
                lzi    z       jvt                      
      z           jlt  k    jlzvtltvtl                  
     tl   i         izvwkjltl      jv ltl               
   l v   vj        ltvwmwkzvti      zi  jvj             
   jvz  vj          itlwi            z                  
    jkdlz         jvt  a             v                  
      ltk       ltl    d                                
        zltltltvj      k                                
        lj tlt         z                                
        jkzi           v                                
     tlzi              z                                
  tlti             lt  vt   ji                          
                    itlxitlti                           
                       v                                
                       z                                
                       lt                               
                        v                               
                        z                               
                        v                               
                        z                               
                        vj                              
                         v                              
                         z                              
                         iz                             
                          v                             
                          ti                            
                           z                            
                           v                            
                           zi iti                       
                      jltltlxlt                 t       
                            v             lj  ixi       
                            z              vj z         
                            lt              vz j        
                            tv              ja v i      
                            vz               zitiz      
                            zv               vxlxltlti  
                            kx              idax   ji   
    jlt                 tltkwmxltlj         jmxlxvzvtl  
       tltlj           jlzvxmwazvtltlj  itlzmzvzltltl   
         izkzltltvtltltl    zld jltljitljldl vj         
    i  tvt     zl           v kj z  itlzkdit jl         
    jkzvj    izi            z zktv       izvtvtltlti    
    vt  vt  ix                v aj        v             
  jvj    ltlx                 zltvt      vj    l        
  v        zvz                lx  lxltlzvtltltl         
          jv kzlj             jv   lzi ix               
              vtiti      jltltaxltl  xv it              
               l              zv   ltizvtv              
                              vz  l   v idl             
                              zv   l vj  ijvt           
                           tlxlxltlj z       tlt        
                             v v    xl         ij       
                             z z   zvz                  
                             v v  tlxlt                 
                             ziz zl izlt                
                             lx  i   izi                
                              a         i               
                          t  lz         zlt             
                          v  zv         v vj            
                          z tkxlxltlt   z  k    t       
           j              v it zvj      v  z    v       
         ltkti        jltlxvx  v v      z  v  tvxltlti  
           z                kzijvz jlt ti ixltldvj      
           i           itltlxlxvxkji itazkzltltvzkt     
              i            ti  jaz    lzi        jvxi   
   lt  i  j   jv           v    zvj  iz             z   
  i itlz  v    jvj         z    v v  x                  
  jlzljaz z      ltlzi     v i it jkx                   
  ltizvxvxk  jlzltvxi      z z z  izv                   
      tvtixvdkxlt   tvj   ti vjv lz j                   
       zizadi v       lzl v  zvjlj                      
       lxijkz z       tijldvxmxi                        
        k  xv          tltawmwatlj                      
  tltltltktlwi        tltlxvjmxktltlt                   
  itltltlzvtvdltltltlt  izk  zvtvj  itltl               
      jvtlj   xv      jvt z  v ltlzl    jlzlj           
    izl        xvt  izl   v  t   jvzkzl     ltl         
    j          ijixvt     z          itvxkzltlj         
               jvti      jv              jmtltltltltl   
            jlxl         v               ixl            
         tlzizi      jltlxlt  ij         t z            
    jltlt   zi           v itlt            iz           
   ji      tl            z                  kj          
           aj            v                 ldlzlj       
          vjkj           jl               lt z  ltltl   
       ij z  vz           z             jvt  v          
        lta   itlt        v           itv    z          
         vjv     iti      z           j      i          
         z tv             v                             
         l  jvt           z                             
              izl         vj                            
                           v                            
                           z                            
                           v                            
                            v                           
                  jvj      iz                           
                   zlzi  jktv                           
                   v  tvtat z   ti                      
                   z jlxmxvzlxlt                        
                   ixltktltizk                          
                    v vj   tvxi        j                
                    tlx     jk   it    it  itlj         
                     ta      z     tvj  vjvj            
                      xi     lj      vt di              
                       zi v   v       ldi               
                        tvxl  z        k                
                        lxmwvtatltl   vjl               
                         idvzkxlj    vtijl              
                          v   vtvxlzvtlzkj         ji   
                          j   zl  tlxljktltltltltlti    
                              vz    vzlzltlj            
                              di    zv     ltltltlt     
                           ti m     vz            it    
                            tvw    vdv                  
                             zvtvzktkt                  
                         ltltaxvtlzld                   
                             zv    zl                   
                             vz   zi                    
                             zv  zvj                    
                          jltkxltlj                     
                             zv                         
                             vz                         
                             zv                         
                             vj                         
                             zv                         
                             vz                         
                             zv                         
                            zijl                        
                            v  zitltlt                  
                  ji        zltlz                       
                   z        v   v                       
               i   lt       z   jv                      
               z   jvj     zi    ti                     
               v   ljk     v      z                     
               ti   vtk    z       z       t            
         vt tltkdltvxajatltktltlti ixlti v izljv        
          izvtvdazktvtmdat z   t    iz jlzl   vx jlti   
            tkzidaxvxi ktvjk   v     iz   z    kzl      
           tl v k   v   itvz   z      i   kt  lt        
              z z   z     zkti v         v   iz     ji  
              v iz  vj     zlzmwv       iz  ixltltltl   
           ltltltvt  k ltlzazkwmdvzvtltlzltltl          
                 jltktlj   z   x                        
                    jv     v   v                        
                           z   z                        
                           v   l                        
                      itljlxl  jl                       
                         ijv lti                        
                           z                            
                           v                            
                           z                            
                           v                            
                           z                            
                           v                            
                           z                            
                           iz                           
                            v                           
                            z                           
                            v                           
                            z                           
                            v                           
       v  t   tlt           ti                          
       z  v lxvtlti          z                          
       it zvzi               v                          
    lj  ktaj                 z                          
     at jlz                  v                          
     zlz zkj                 z                          
  tltvxvxldv                 v                          
  lzkj   zvxi                z                          
   vjkzltijkdi         ltltltv   i                      
  itl vz jltvxv             lzltlj                      
      z       tvj           z                           
      v  jl     vxl     i   v                           
  jl  zizl        zkt   z   z                           
   zi lz            lzvjat  k                           
    zvt               tawmtiz                           
     zi             itvxmzatkt                          
      tl        tltljlz w jvzitltltlj                   
       tvj  ltlt   tvj xl  jvtl     ltlxvtltlti         
         adlj   jvti lzi   v  tvt      iz               
          izkxldvtltvj     z    izvj   tlt              
    jltltltlti v     itltltktltl   ltvj  k      t       
               z           z          itvzktltlti       
               lzl        tl            z xltltlti      
                kzvtltlj  v             v v      ti     
                jk        z             z z             
                 jv       v    ti      tl i             
                  j      vj     tltltltk                
                         z           jvtv               
                         v          jl  jvtlj           
                        lj         jl       ij          
                        x                               
                       jl                               
                       v                                
                       z                                
               v      zk                                
             jlz     tlz   jlj                          
              jkt   jv vtltl                            
               z zvtk vxi             l                 
               it jvdv v            jlxl                
        i       k  zi  z              l                 
        tl      jl v   v                                
         zl      ziz   z                                
          tl   ltlxv   v     i                          
           tvjltltlwltlzvtltlj                          
           lzvtlj  lx   z                               
        izlzlt      izi v                          jlt  
       vj zi          zlx  v                    jltl    
      l   v            taj z                 jlzl    j  
          z             xkwmtl          tlzvtltlt jlzi  
         ti             v mwltltltltltlti  z    idkj    
         l            tlxvxv               v     vzvz   
                 jltlti idit   ji          j     jl ij  
             ltltl    jvzv     v                 i      
          izkzltltltltl  z    lj                        
                     i   vtltlxl                        
                     jltltl  tl                         
                          z  v                          
                          v  z                          
                          zi vjijlz                     
                          ixktiti                       
                           vz                           
                           zk                           
                            d                           
                            k                           
                            xl         l                
                     tltlj  vz    i    z                
                         izvxatltlj    v                
                            idmzl      z                
                           izaz jlz    v        t       
                          lt zv   itl it        v l     
                         lt  lz     tvz         zlt     
                         z    k itltlzk         at      
                              di     vj       jkj       
                            itkxltltlxltltltlzkz        
                        jvtltlzlj j ti         itltl    
                              vtatijv              jl   
                              z jl v                    
                              v  zkj                    
                              z  ldltlj  v              
                            v v iz xi izvjv             
     iz                     z xit   t    ix             
       zi                   vjkt  itltltljv             
        zl                 ldaz       zvtltl  jl        
       jlzl             ltlwmwmxvtl    zvwlz tv         
     ltl  jvt            itldmxvzkzlti  xlxvti          
   jvj      ltl      jltlj  vzkzi ltlxkzvwmdvzvtltlti   
   l  jlt     tvtltltl      zvjlxv     vdadltixvt       
        itltltlj            lz  izazitvxi  tlxkz        
                             v     izkdvti    taxi      
                             z           tlzvzljazi     
                            jl                  zltlti  
                       t    v                   v       
                        tltlxltlti             lj       
                            v                  j        
                           iz                           
                           z                            
                           v                            
                           z                            
                          zi                            
                          v       it        i           
                          z        lz     jvj           
                         ti         iz   jv             
                         v   itltlj   x jv     i        
                         z     z  itlxlzv     lt        
                         v l   v    j tkz    iz         
                         zkj   z        v   lt          
                         aj   jv   v    z  lt           
                        lz ti azvzvdvt  v vt            
                    tltlzvtlxkj jl v    tajlzl          
                       tkxititkti      jvj   zi         
                       v vjkti        jv      j   taj   
                       zidl   i     ixv          zaj    
                    jltkxktltlj    lt jltlt   jvxl      
                       z z       jvj      itvxkt        
                       lja     izi           izl        
                        vd    lz               jvt      
                        tmjitv                   iti    
                      itvwmxlj                     t    
                        zmd                             
                   jltltiw                              
               itltl    zk                              
           tltlj      lz z                              
        zkzi       itlj  lj                             
          ltltltltlj jltltktltlt                        
                          z                             
                          v                             
                          z                             
                          v                             
                           v                            
                           z                            
                           v                            
                           zi                           
                            z                           
                            v                           
                            zi                          
                             z                          
                             v                          
                             z                          
                             it                         
                      ltl     v l                       
                      zv      z ti             i        
                     zvj jltltkt z           tldlt      
           lzl       vdlzl    ti vj         jvjaj       
            lzkxaz  lxi        z  v         v  j        
     lti         ldvzvtlj      v  z   tlt  vt           
       tvj         tmz         z  vtlt  itvzvj          
         ltl        d    itltltktlxl         i          
           jltl     k          z  v                     
              jati  z          v it                     
              lj jvta          z z                      
              z      ltlti     vtv                      
              i          tltltlwmj                      
                            jldmwkti                    
                            itlwk                       
                        jltvj taz                       
                    ltlti  z tlzv                       
              jltltl      jkti  z                       
             zktltljltltltvjl   v  ji                   
                   ij     jlxltlxltl                    
                            v   v                       
                            z   z                       
                            iz ti                       
                             v v                        
                             z z                        
                       ltltl v v                        
                            lxlx                        
                             v v                        
                            lj z                        
                            z jl                        
                            v v                         
                            z z                         
                           titi                         
                           v v                          
                    i  t  iziz                          
                    jltktlxlxi                          
                       z jv v              z            
               vj      v k it            ltmzl          
           tltkzktlj   dvj z             zit            
             ldatltvxljkzltktltlti        z             
           tlxiz    itkd   z             jk             
            zi v      xv  ti            ziz             
            v  z     zijl v               v             
            j  lj   xi  z d               xltltltvxat   
           j    l  zi   lja               k      zl l   
          ti             kx           jvjlj   jlti  jl  
         jl              zkj            kz jltl    jv   
     lzi v           lzltmwmzlzl      jldltijltltlzv    
       tlxi            jlwmxltltltltlti          tkj    
         itkti      jvzvtmd                      izvz   
         zvj tltvzvzltijaxv                     iz  it  
       lzi izvzvti   idvtlz                   jvj       
  ltltlzltlxltltltltlxlzv i                             
          z        lzi vz                               
          v      tvj   jm                               
          z   jvxi  j   z                               
          kxvtl v   itltmzltlti                         
       ltlxitltlz       zv                              
           z    vti     vz                              
           lt   zi ij   zv                              
            lj   zititltkxlti                           
                 kxi    zv                              
                  ktlt  vz                              
                  j  itlzv                              
                        vz                              
                        tk                              
                         d                              
                         a                              
                        ixl                             
                  jltltlxldi                            
             j          v v             i               
            tkti       lt ti     v      z               
             z         x   z     z    ix                
                      tl   v itlz    iz                 
                      v    z    k   vxltltlt            
                     vj    lj  ktltlj                   
                    itltltltktvxi                       
                   ix     j z z                         
                   x      v vzi                         
                  j       z xl                          
                          vja                           
                         vwatl                          
           ti         lzkwmwlxl                         
           v     ltltlti  x  v                          
   jltltltvzltlxlj   j    v  x                          
         iz   z      lt   z  v                          
         z    v       vj  l  z                          
         v    di       v    jk ltl                      
         z    advj     tvtltizlj                        
         v    zizvtvj   x    v                          
         xvj  iz jlti   lj   z                          
         v ltvti         v   v                          
         zi   izv        z   z                          
          j              lt  v                          
                    ltltltktlz                          
                          z  v                          
                          v  z                          
                          z  v                          
                          v  z                          
                          z jv                          
      itlti               v v                           
          tlj  izi   ij   z z                           
        vj  ltlt   jvt    vjv                           
         v   kt   tkzltltlxkj                           
         jv vj   tvjitltlxvxi                           
          tkj   jvtl     v v                            
   j      vdl   v  j     zit                            
   iz   tvz tl  z       tiz                             
    izl l v  tv v       v v                             
      jl lj   jkz      lt z                             
        ld      vt   jldijkj   j                        
         izl     lt   zijvtitlti       lj  vt   jlt     
           jlti    tijl  z              v  zixkzi v     
              tvt   jat  v  j           zltktlzkjit     
                itvti itiz  v            zizvt  vdltlj  
                    tltltkzixi           vdvj  iz       
           t     jl     iwkwmwlt        idl   lz        
            xi  jv       vjkdltvzvti itkdi  tljltl      
           jltljk       ixl v     itvxvzlzkdkxvzltltl   
               lzl   itvzv  t              lzi          
           jltltlzvzlj  vz                   tv         
               izi      zl                    jvtvtlti  
              iz    itltkdltltl                jkj      
             ix         zv                      xltlti  
             xv         vz                       z      
            tlti        zlt                      i      
            i  t    itltvzv i                           
                         vxlj                           
                         zv                             
                         vz                             
                         zv                             
                         vz                             
                         xl                             
                   ltl i k                              
                     jltldvti                           
                         vz                             
                        ljv                             
                        z z                             
                       jl lt                            
                       v   v                            
                iti   it   z                            
                  tltlxlti v                            
                     zltltlxltlti                       
                    jl     v                            
           ji      jv      jl                           
    jltlti v      jv        z                           
         tkj     jv         v                           
        jkxlzltlzk          x                           
        itvtl   ij      v   v                           
     ij zlzv           ix   z                           
    ltlzkdlxi         idmz  v   i                       
         vzitltltltlxawmwmzlxltlj                       
    itltlzmtltltvtkxkxlzmtl v                           
  jltltltltlzlzkdvt    kz  vxl                          
          vxmtiz     jvji   axlj                        
  j     zatlzvxa  jltl      x  izlti                    
  itltldv lxvtlxltl         a     idatltlti             
     iz z zk   lj          id      kd                   
    iz  kzijl   v          zv      zv                   
    tizvzl  x         jltltaxltlt jkz                   
            iz             zv itltlzv                   
                           vzltltlzkz                   
                           zv     iz                    
                           atltltljv                    
                         tld      l                     
                           a                            
                           di                           
                           vz                           
                          ljv                           
                          z zi                          
                          v  z                          
                          z  v                          
                          v  jv    jl                   
                          z tlxltlti                    
                          v   iz                        
                          z    lj                       
                          vj  itaj                      
                      tltlxltlj  v                      
                          v      jk                     
                          z       jv                    
                          v        jv                   
                          z   j     jv         i        
                          v   v      jl        z        
          zi              z   z               jv        
    i     v               iz jkxi             v         
    tv   vj           jltltazawmxlt          vtlt       
      lj z                 xvtawltlti      tvj   tvj    
     ltvwk               itkj z x   jltlzlzltltltlj     
  vtlj zijvt           jvt z  v iz x    lj              
       i   itlj      ltl   v  t  lxi     v              
              itltitlj     tl    jkt     z              
               itaj         z    v lt    v              
            ltvj jv         v   iz  lt  kzlj            
        jvtlj      vj       z   zij  lzvx               
    itlti               ltltktltkt jvzlxi               
                             ktktltltltvz               
                             z z  itlt  vzi             
                             v v       vj tl            
                             jvz      iz   jvj          
                              d       x      vz         
                              v      x        izl       
                              zv    xi          tvj     
                            ltkxltldv             vt    
                              zv iz x                   
                              vzvtlzvt                  
                              zaj    lz                 
                             jld       zl               
                               a        jlti            
                               d           ji           
                             ltktltltl                  
                               zv                       
                               vzi                      
                               z z                      
                         ij    v lj                     
                          itltlxltkti       l           
                            j  v  jl        z           
                            v  z   ti       kxltltlt    
                            z  k            zit         
                            k  z           jl           
                        jltkwmtkj          v            
                           xmwkj          iz            
                       itlzmd dvtltl      z        lj   
             t     jltlj  kzv v vzijltltlxltltltltlj    
             lzltlti    tat z z   jvzl                  
          izkxkxl    jvzl   ijv     v lxltltltltlti     
          jvtltltvzkxkz zltltk    j z  vj               
          i      jlzl        zltlt jl   v               
             ltltldi         v     v   iz               
             j    vzi       it    ix   zvt              
                 lt         z     xizl atitltlti        
                 zi         v    x   jkzvdl             
                 vzltltlj  iz  ix    it   jltlj         
                 jv        z                            
                tvz        v                            
             jlzi vj      it                            
          jltl     i      z                             
                          v                             
                         v                              
                         z  ij    izl                   
                  j    vjv   v      tlj                 
                 jl     vz   tl itltltvzi               
                ja       k   lxlj       tl           i  
                 d      lw  ltv          tl        jvj  
                 vz     jmtlj jl    jltltltv      jv    
                 tmzltltaxltltlzitlti      tl   izl     
             lxvzlwktltv v     vt      ij   zi lz       
             j    azvxkxlxl    z        ltv  xvj        
                 vtvxk   vjvtijl          jvzvtlzvtl    
              ljidi vzi ixltlzm          jvt     z  l   
           itvzkzlxltktljv    z        izl       v      
         jljkjlt  i   v  z   ti      tlt         t      
           v  j       jk kz  v    jlzi         v        
           t           jvzv v  jlti            z        
                         axktvti               v        
                       jlwmwvt                 zizltlj  
                        jkxkzktltlt            vtvj     
                      ltizvtl ltl itltl  j    iz        
                   itvz  lz tvj jvti  jlzk   iz         
                itvz  lt  v   lzl  jvtl  zltlz          
          jltltlj z    v  z    ijltltltkdkzvxl          
    itltlti       v   ltktktltlt         jktvtl         
                  z     tiz               zi  jltltlj   
                 tv      zv                z        i   
               izlzvti   vjv               v            
         jltltlt  ltltvj jvz               z            
                   vj  itlxkj             jkzvj         
                    vzltltaxlj    itltltltijl itltlt    
                     l    tiz              vtlt    iti  
                           zv              z            
                           vz              v            
                           ziz             t            
                           v v                          
                           z z                          
                           v v                          
                           z jl                         
                          jl  z                         
                    itltltktljv                         
                          z   z  lj                     
                          v   v iz       j              
                         lj   z z       xi              
                        ixltltkzktl    zi               
                        tl    zlx     tv                
          i          j  v     v  dlj tltv               
          z         tl ljij   z  iz tl   i              
        izvz      l ajldlj   tv   vzl                   
   lj  lz  ltltltlxkzvd      vz   di                    
    k lzkdvtvt    iwa        zv iz                      
    jadvj  i lxltltld        vdvt                       
     jatltltvzvzlj  ix  itltkwmtlti                     
  jltltvj      lzvzkzkdvxvzawmwvtlj                     
  l     vt         z    izktldv                         
         lzi       ltvzvzi izvj                         
           zv  jlzaxvj   zvz z                          
          jvxaxvti     lta   v                          
     jltltltltltltltltlj tl  z                          
                          z  v                          
                          v  z                          
                       ltlxlzvtltl                      
                    itltijv v                           
                        jlxlxi                          
                          v v                           
                          zit                           
                          vz                            
                          zv                            
             j            kz                            
            zkz    it    iw                             `;
