'use client';

import { useEffect, useRef } from 'react';
import { SIGIL_LEFT, SIGIL_RIGHT } from './sigilStrip';

/**
 * Cyber-sigilism rails — hollow-outline thorn work crawling up each side of
 * the viewport. The strip is generated by scripts/generateSigil.mjs.
 *
 * Motion is two things added together: a slow constant drift so the rails are
 * alive when the page is still, plus a parallax term tied to scroll position
 * so they surge as you move down the page. The sum is taken modulo one tile
 * height, which is why two stacked copies are enough for a seamless loop no
 * matter how far you scroll. The two sides run opposite directions.
 */

const DRIFT_PX_PER_SEC = 14;
const PARALLAX = 0.45;

type SigilText = typeof SIGIL_LEFT;

function InkLayers({ text }: { text: SigilText }) {
  return (
    <>
      <pre className="font-mono text-[6px] leading-none text-zinc-400/[0.18]">{text.detail}</pre>
      <pre className="absolute inset-0 font-mono text-[6px] leading-none text-zinc-300/[0.36]">{text.body}</pre>
      <pre className="absolute inset-0 font-mono text-[6px] leading-none text-zinc-200/[0.58]">{text.highlights}</pre>
    </>
  );
}

function Rail({ text, side }: { text: SigilText; side: 'left' | 'right' }) {
  const shiftRef = useRef<HTMLDivElement>(null);
  const tileRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const shift = shiftRef.current;
    const tile = tileRef.current;
    if (!shift || !tile) return;

    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)');
    if (reduced.matches) return;

    const dir = side === 'left' ? -1 : 1;
    let raf = 0;
    let last = performance.now();
    let drift = 0;
    let h = tile.offsetHeight;
    const resize = new ResizeObserver(() => { h = tile.offsetHeight; });
    resize.observe(tile);

    const frame = (now: number) => {
      raf = requestAnimationFrame(frame);
      // clamp dt so a backgrounded tab doesn't jump the rail on return
      const dt = Math.min((now - last) / 1000, 0.05);
      last = now;

      if (h <= 0) return; // rails are hidden at this breakpoint

      drift += dt * DRIFT_PX_PER_SEC * dir;
      const raw = drift + window.scrollY * PARALLAX * dir;
      // wrap into (-h, 0] so the second copy always covers the viewport
      const y = ((raw % h) - h) % h;
      shift.style.transform = `translate3d(0, ${y.toFixed(2)}px, 0)`;
    };

    raf = requestAnimationFrame(frame);
    return () => {
      cancelAnimationFrame(raf);
      resize.disconnect();
    };
  }, [side]);

  return (
    <div
      aria-hidden
      className={`sigil-ink pointer-events-none select-none fixed inset-y-0 -z-10 hidden lg:block overflow-hidden ${
        side === 'left' ? 'left-5' : 'right-5'
      }`}
      style={{
        maskImage:
          'linear-gradient(to bottom, transparent, black 14%, black 86%, transparent)',
        WebkitMaskImage:
          'linear-gradient(to bottom, transparent, black 14%, black 86%, transparent)',
      }}
    >
      <div ref={shiftRef} style={{ willChange: 'transform' }}>
        <div ref={tileRef} className="relative"><InkLayers text={text} /></div>
        <div className="relative"><InkLayers text={text} /></div>
      </div>
    </div>
  );
}

export function SigilRails() {
  return (
    <>
      <Rail text={SIGIL_LEFT} side="left" />
      <Rail text={SIGIL_RIGHT} side="right" />
    </>
  );
}
