// Generated by scripts/generateSigil.mjs — run it again rather than editing.
export const SIGIL_LEFT = `                             z  a                       
                             v ix                       
                              vzv                       
                              zkzl                      
       t     jvtlt            vd x     t        lj      
    j zi     ltajvj           zv m    tl  jv  jvtizi    
    ixatvxktkj zvtk  zi       az dl   v    z  kjvxi     
     azkzkzljitkjkxv v        wv vdltldltl itvtk v      
   jlx  vt     zltmdlx  izkxlxmxkzmzlzkt jlzvdajvxvzlj  
     azvj      iz tmwixitl   azajlwl azkzl  wmziz jkdlj 
     ziz     jltkxldmtvdlti  wkz tax d j jvtmz tltkjl   
            tvxkzkzkwmz   tltmtv  dmjk     mwvzltlt     
           jljl  zlxawv     kw jl lw j    kwkzvzi izl   
            t    l v mwktltvwmz zixmdltltvwmjv      j   
           jkt     z xmxl lwmzlzkzidad  ldmt z          
                   v  wlxvwidv vwl azaxlxkw  v          
                   zi kwvwa axltmtvdvjmxvwl lt          
                    tvzmxmtvwatadktmdvxaxmtlt           
                     zlzmx zkw tmjiwvtiwmxkz            
                    ti iwax tmzkzadm ljmd  v            
                    vj xawk lwatatmwi mdm  z            
                     v mxixaxmdizkwkdatvwv v            
        vz  l       ixvwat tlwkzvzad  ltawiz      i     
        z zvj      vtlwajizixazidltm    xmxvz   jvti    
      izv ktl     vjidmtlz tmzitvx wl    wmjiz   tlz    
        jaj tkj   zvzmdvt jvda kdi mx    vwkziz  lxldl  
         jvj zvtldajkxaj  vjawljktlwl     adixkzktlti   
      jltltkxldl  zvzm  jk  zm  z tm      zlz xlzvtltl  
             zi  jmxkt jk   iwi v vw       xizk         
             v   lzmt tv     mxkwlwv       izkt         
             dazvtlditl      zazkjmj                    
             vtkzvdaz     jv  wvzvd                     
             tk  tvz      vz  kdldi                     
           lzi ktl i      zvj ja m        t             
         jvtizvj         jktk iwlt       tvj            
        zvzvzi           kt w zlz      itvzlz           
      ldvtkzkwvj        iw  atv a      tlj tv           
      j   x zajv        xa  zmj j     zizk izl          
          v izktv       mz   wi      jvzlz z            
    jltltiz z  md      iw   jmx      kdi vjvjltltlj j   
         taxat tmj     zm   vxm      wk idaxltltlji vz  
        tkx jaziwk     ad   zvw     tmjvdl  tvj  lxvzvj 
       tix   zatkw     dkjlzv m     awlxk     v    ti i 
         awvxltkdmz    azlxkzlwlti iwadv                
         jvzmt  idm    dvzizk m    xmj                  
           it   ziwa   vxkzatvw   zmxlt                 
               zi mwvt jmzktvwv izawi v                 
               v  xmxawkwax xmxmwvwm  z                 
               ti iwmz tmxazlwk lwmz  v                 
                z  mdljkwkxidaw zvwl vj                 
                ixkwm vwk md tmx dmdlt                  
               vzlwawmxmxkdktiwvzmxmxvzi                
              vj xm aw dvdlzvzm kw xm  x          v     
              z  mdajmza vzvt wiwixawl it        vj     
          v  tijawvj jmwlzvtl mwv  zawi v  ti  tkxvzvzi 
   lt ji  zitvxkwmzltltmwk  jkwktltldmxvxljlzltv   i lj 
     tlzkzkdltktmz     daz  izm     iwktktkzvzktltlj    
   it    kxi  tmd      vwv   aw      kwl  jlti          
    itltkjv itvwi      tmz  iwk       mxlj          i   
    jvtkxlxkxvwk    j   wvj zmt       tmtlz   tlj  ix   
  ltizajkxazlxmj     tltaxkdvwi        wmtiz   xvtiz    
  jaz zvdvxatmx         za iza         lwvta   v kzi    
  ltltkxmzv kwi         vw  at          md jkzltv       
       ltvzvzk          zaj w           tkxltvjltltltlj 
        kdmdkj          vzv a            xidldizv       
        zkxat           z dvz            ixlxmxazi      
         jlj            v kz              idl iz        
                        z xv                  j         
                        vjad                            
      tlzl               vxv                zlt         
      vzizl              zvx               xijvz        
       ixkxi             vzk              zlwl          
       xvtmx   j         xvxi             awvj  lt      
   ij  vx zmj  v         mzvz            vwi vjltktlti  
  itltldmt dk lj        idljm            wvjkzlzlj  it  
    jlzmdazkwlz         xv vwi      ji  xmtlz   jmzlzvj 
  itlzitkzkzmwv         mtlxaz       z jmz zi  jawad    
        jijvzmz       tlwvxaxmtlj    vjawawltljltkjit   
             dm        zaz jaw        awkzkwktl         
             vwv       aw   dmt    itlwmj  ldk          
     jvxawltkzmw       wk   vwv    j zmxv  jlzvj        
    zktkj tlxlzmz      mxi  xmd      mwixvtl   vz       
    ijvz    v lwmzltltawvj  kdmzltltawatv       kt      
     l lj   ti kwmj jmwm lzktawmz  vwmj z      ixl      
        l    z jmdvtaw d zkzidajmtltmd  v               
             izixmjvwl mzixvjmd xmjkwljv                
               zvwkwmzlwlxkdvwmxkwvwmzl                 
                tawmtlxmj dv awk mwmxi                  
               tl mwit wkxizvwv vzmx xi                 
              jv  wmw  awlxkxmt jmwa  z                 
              v  zmxawkdmx jmwaxmxmw  v                 
              z  mwltitkwv izmzktlxmz z                 
              v iwmt   datvxkwvtv lwa v                 
              jvxmj    m vtizvd jvjkwlz                 
       j      izmw     wizizlxmzltkzmxl                 
     i v     ltlwv     m ldkjvdvj  iwmtvj               
   jldvxizaxkxldm      wi i  xa vj  lwvzkz     zl       
   ld tkdltvzizmx      mz    ax  lt  mwktlzltvzi        
    v v izizvjlw       da    wl   lzizmtmdi   it        
  tltlxltlzv  wk       vw   tm      zvwv vxktltl        
          vz zmj        mj  kw       jawi vxi ltltltl   
          jmtkx         dv  wk        jkwkzvjvj         
        lzvzazl         ld jmz         xidvxltvt        
         kjvtl           m vzv         izlxktltlxl      
         j               zlxiz           tv  jatlt      
                          zvzi           i    xl        
                          vzkz               jlt        
                          z dv          z               
          l                zkx          lj  izi         
          z  a    z        vxvj          v   mzkti      
          kxkdi  ti        xvjk          z jvdmwi       
   itltlj zkdix  v    jl   mj w       tltkjktadltltlj   
        itlxkxvx z      ltkwltadl        zadkdktktvj    
            xvwmzv        xktvjm         awmtlj jl      
         tktvtldmd        mzljvwl       iwa lt   ti     
       izlz  vzvwmj      lwv  jmd      iwmzvzltlt       
        idvtltltkwa      dm    xm      wmdvti   iz      
        tlj    lzawatltlzmwl  jawatltlwmd z             
          i    z jmxkj dawitvzl mtmtixkwi v             
               it zmtvdm a vzktiw zmdlwk lt             
                vtiwmdmxlwazaxvzmjlwmwmzvt              
                 lxkwmx xmx xa lwvtlwmzvz               
                 zi vwkz dmxvtawa ixmw  v               
                 v  wmwktawazlzmzvdmdmt z               
                 tlzmxvzkwmxi vwazltkwmjl               
       iti      jvxmwv   mxvzvzvw   jkwazlj             
      idk      tl kwl    wvtljv m     mwvjvj     j      
       idlj   jvzawk     mz zv  w     jmdkzk  jvz       
   tljltkzktltkzldajij   wk  j zm      zkwidlxkt        
    zv  zlzktlzvzlz  ltltmwltltkd     tlwitm kjktlti    
    ltltlj    vdlz       xmj t wl     idazaxiti         
                         vxk vtm       idvxvxiti        
                         ziwldaz        vti iwv         
                         vjkdawl           it t         
                         z  kdl                         
                         v  za                          
                        lz  it                          
                        dit                             
                        a v                             
       lj               xvz                             
     zkjvzl izi        jvxv                             
      jkxkj tvdi       vjkjv            zvzl            
    ij wmxk v id       w diz           xixvz            
   itixmxmwiz  it     ja vzv          tvdk   itlzltlj   
   tlwldvjawi   ktlzvtadijmz      ij  mwizvxkt  izl lt  
     vjizlxmj zvj  it wlj wv       v lwlzaj jkj   jkxk  
      i izidmxlt     jmjktaxv      z waxvdltljlzltvtk   
         izvwl       vdv lxmz      ixmzlzidl   iz jvjl  
     jlti   aw       daj  kwv      jmdatizizi   i       
   izl  jvtkjmx      mxltlzmwltlt  kwvtlxltlt           
   j       xvwmz    iwlj  iwa     lwvzlzlzlzkj          
   izl     v lwktltlwmzl  zmwltltlwmtlt     jl          
    l      z  mwajiwad tlzizmwi idmx jv                 
           it tmtkwkza lzvjvwvwixawi v                  
            lziwazmtvwljatvxm md wk it                  
             ixkwmxldm lxv kwvxmxmzvz                   
             ti awiziwltvz wmz wmzvj                    
             v  dmxi mdatvxmdizmw  k                    
             z  mdmzldmzvzmwk kwmj jl                   
             v vwvzkdawl idmxaxvwk  z                   
             z wmtltiwaxixkwktlxmw jl                   
    t z z    itmzvt jmtldlxadij zmtv                    
    vjmdkj tvxmwv  jmw z tidm    wmt       jvtlti       
   vxkjat jazlwv  jvzm izv aw    lwvdv   itldi lt       
  ldlzvtazazkwm  tv lw  v  da     mwvzv    ja vti  ti   
  jvtldltvzlzmx ti   mt    md     zmjlwv izvxvtvzvti    
          ajadvz     wv    wa      wk  xvzaxltl  jv     
        jvxkzk       vw   zmz      kxl v  ti            
       zkzajvj       jm   axv  x   jkzaj jlz            
       l   lj         dv  wvj ta    zlxvxatktitv        
                      ld taz  kzi    ji ijit jkj        
                       m ktv  xix            ij         
                 jl    zix z tk m          tvz    l     
                tljv    zv v mt dl      jizvtvtlzvtl    
             jazvwkzi   aj ziw  lw      izawvx zvjkt    
             vtldkjax   t jlxa   mj      vwv vzlj z     
             xl lt xm     v mz   dk      dm  zvtlxltlj  
         itltltlzv  wl    ziw    vw      mt tkt         
                 xvtkd    vzm    tm     lwlzvtltlj      
             lzlzvzixmj   zad  l  wi    wmtvdl   vz     
           tl    jkdlwk   vda vxi mz   jmzvt      ij    
           i       itvw   zaz z z wl   kwlj             
                    vxmz  vxaxizvjm    wajl             
                    z wmj zvwaxkzaw   xmt z             
                   z  vwazvzmxl vdktltmw  v             
                   vj jmdvwawajixmxkwkwa  z             
                    v  wmw zmdvdvda lwmt jv             
       l            ti kwlzawvz xawixawi v              
       z             zlwmzlwa lx  md wmwv       l       
       v              xmdmzax zkjiwvzmzmxvj     zi      
    itiz           tvtmxvwldvzizizazawiwm vt    vzvxlj  
  jlj tk          jl vwlzadaz zkj dkwizawi lj  ixvj tl  
        k         k iwmz jmwvjvjl awl  xmdl v lt        
        jv        xlzmwltltmwl  jawktltvwmtldkzltltltl  
  iti    jkj jltlzatmwi    xmj   jm     lwvtazi   vt    
    tltltltvdljlzlz wk  tltkwvtltaw      mwizvjltlj     
             ti   vzmj     jmz  iwa     idmzkz          
                   md       wkt xaz       wajitlti      
                  iwl       kxlziwi       vwvzi         
     i  zvt    izvwa        tm itm         mdizl        
  vjvdkjvzi    xitmt         w  vx         zmzvx        
  jkdlwaj j   zltkd          kz di          wk lxvtltlj 
  vtmz  ltltlza iwi          ta m           lwi v vjit  
  jkxazvtltl  z wa            w x            ad z  azkj 
     ji       vxkt            adl            zlwi  jl   
             ixlx             zm              xitkj t   
            vz zi             ldi              zlt      
             iti               az                       
                            i  xv                       
                     v      zl  z                       
                 z   tijl   vz  v                       
      jlzaxl    jv    zit   zv  z                       
      vz  v    jat    vz    kx  v             ij j      
      jv  ti    zldi vxltltkxvt z            izmzk      
       zvzizvj  v ldlxvxl  witm v lt   z    ltvdaxv     
  tltlzvxlxkjk  xv vtiji  ta  wiz z    v   izvzvtktlt   
      lj jkzaxatk vj      azltvdkdl    jl idmxvzi       
          tltmwlzvj       wvtltmzitltl  xldmz x         
           tl awlx       zmxltkwktltijlzizmzlzi         
        jltltvzmwkj      aw    md      vzmdlzvtltlt     
      itl  jlzvdmda     iwkj  ixmtltltvdmwati    jmx    
      j       tizmxmtltmdmtltlzawkdi ldlwijv      t     
              vj watatmz w jkxlzm vwvxiwk lj            
               v iwvzmw  mtlzvjaw jmwvdm iz             
               jvtawkwizvwl kx dmdljmxmdkt              
                 kzkwkjvjmdvzlzmw tizmt z               
                lj xmwv  xmxaxawv  zmwk it              
                ti mxvdadkwa  dmzaxazkwizi              
                 xkwkzi  xmtvzmwa  jldmdkj        v     
               vzvwmj   tmzkxvdvwvj  idmzvzi     idixi  
              vjlwmj     w jvxlxmtlt   wmziz    vwadax  
       vj t  lzkdmz      mz ta vw  lt  ldaxkt  kwaxvzi  
        lzatkdlzkx       wv  z xmx  izi ktvjktkdvt  l   
     itltat zvtvzi       kw jv mziz   zljk kxi   ltlt   
       jvt  vdkzkt       jmjv lw  izi  tvjvtl           
      jmtvxltvzlt         xkw xk    ti   lt             
      vjvti   vz          iwmdm      jlt  lzi           
      t jkzi               kxlz        itlj zv          
       tl                  zax            ltltvj        
                          tlzv               itlz       
                          vjlj                          
                          zv                            
                         jaz                   j   j    
                    j    vzv                   vz  v    
               ji  z zi  zvz                vtlwkxvz    
    j tvtvt    v   lj x  vdvz        it    ktvtlj di    
    v ktkdvx  lt    v v  dv a         v   vxadltijv     
   lxkwlwmwmj z   tvjixltmt w         jvtvwazktltvtlt   
  izvxmwmjvwktv   lxlj   w  kz         xlxmtlwi         
    zix tvzkwiz tlj  i  zmtlxmzi       vjmzlzv          
   ti l  x tmxvzlti  jltmdvtiwi        zaxizl           
   i      zvzmd         wk  zaz        awvt             
            ixmz       zmx   wa       vwk   ltlti       
      jltlj  vwm       kwv   kw      iwmtkzlj   tv      
    izi   izvzawk     lwkz  izmzltltlxmxiz              
    j       z  mdatltvdmxktitiwvdi ixkw  v              
            it zmjkjiwid zkxi m vwix wv lt              
             v  wkjkwl azatvtlw  md xm iz               
             jvjlwvdmxlwkxazktmxvzmdmdvz                
               ldadmtidmxida lwvz dmxit                 
               ti mwix xmxvjawm izkw  lj                
               v  wmx  lwkwkzmdi kwmz  v                
              lj tmzvdkzmdv kwkxaxixm  z                
              jl mwlti iwvditmx  izkwljl                
               ziwkj   xvxkzvtm    jmwi                 
               idm     azlziz w     jmdvt               
             zaxmt     dv kd  m l    dmtvx      vj      
     v      xkzmw     jmxltatvwl     iwlzlxi izvj       
     jlzi ixazlwl      da  z zm       aw tkzvtv         
    tltvzazm  dm       vw  vjad       jax zitvzlt       
      vj jld xvt        mj  vwl        xitv     ixltlt  
     ld j  mdix         dk  xm         ixlzv   i  tl    
    ixltvxvdkti         iw  az          izi   vz  lzi   
     lj                  mj wv                 vdlt x   
                         tvjkz                it    v   
                          xvjv                      z   
                          vz jl                         
                          jv  z                         
                              k                         
             izi             vx       xi    jlj         
            ixltl  j         zk      xl    jvjvt        
      jltlxkzizvxitl         kdi    zkj t  kzvj t       
     jltltkxaxmtaxv         lxvx jltvxl izlwi vtktktl   
         izvjvdkwmz         xlzm       vzvwltkwvtvxkt   
      ijvt zv vzvwm        jm vdl       idmzizitvdkwkt  
       axvtkt  lzkwv       kxldlw       jmxvz  v kxijv  
      vjktlti     kw     j wvtvzmj      kw jltlzljk     
      jvdv        xax    izmxlxvwati   iwkzl            
       t   jltltvxidmj    kw  v kw     wmtktltltl       
          jmt    vtkwmtltlwmj zixmtltlxmxlx     ti      
           j     zi lwv  zmzvzvtlwk  tmd  v             
                  z  mxvzmd jvwl mxkzlwi lt             
                   tvxmjmzaxizktvwiwldmtvj              
                    jvwmwiwv vd jmtkwmzi                
                   jl  wkzkwkxkxawltmz tl               
                   v  tmwlzmxkdvwajmwk  z               
                   z  awvxvwajvxmdkzaw  it              
                   v iwv idazkdlda  tmz ti              
       t           jvdm kxmxkxvxlwi  zmtl               
       k   ij     tktmtvjiwv mzi m    wlzi      j       
  i l  jv   vzi ixatkwv  zax zl iw    kwlzkt  lzi       
  jvtlzvwl   izlzvtkwl  zixa v  zm     mzltvtlj         
    awl  jvj tijatlxm  zi iwiz  mx     xk ldlj          
    tvzitltktlzizvtmz zi   mw  iwi     iwi kjlxvtlj     
      i        jkxvzizi    tm  xk       mzldi lz  i     
              zlzkzkj       wi mj      vdaxmxlzajiti    
            izi  zl        jkxlx      iz  ltvzadizlj    
           vz jlti     lz  v vz               tl        
         jvjltl        zv  z tv                         
        zatlj          kx jv  j                         
       tl             lzvtv                             
                      di mz           j  lt             
                     jm  wv           lt jlxi           
                     kx  vd            kzkzlx           
        lti          wl  zmj        itkzv   it          
       kdatv        tm   vwv        x zkzi   v          
        kwlxi       ad   zkd       tvdlzlzkxvtltlti     
   lxkzvw dkx       wv  jlzm       awlzati vzaj   ti    
 jvt  kxkxlwmj      mz zm vw      lwmzlt   j jlxvzvj    
    jmt jljkwa      wvjlxi m      wmt x        it  v    
    kxi  tv awl     azvjkzvw     xmwvzi         i       
          jvxmwvj   dkxkdkdatljlzmwv                    
            vdmxltvzkwvjvzmdadkjkwkjl                   
           v lwadmzvzmxizkwltlwmdmj z                   
           z  mwmz  vwkzaxmx  ldmw  v                   
           it dmzlt dazkdvdm vjkwmtkj       j           
       t   tadmwm lxmz xk lwkz wmwmxvj      iz          
   ltltv  zl mwkwktiwljmzitm iwmxmwl vjltltvjv          
      ix jv kwlzmw  mtlxlziw jmwvjmw jl     lx          
    jltvzv iwatvjmd w  ax  m mwizvzmz z     jl  j       
   tv   kxldmdl  jmdmtvzizvwmwltlzmwm v     kjitv       
 l ltltltkdmwvtltltlwajv ixmt     jmwmxlj jk awkj ti    
 tlj  ltltmwv      jmd z  ad j     jmwltlzazawkdkti     
   izktlzawa        xmzktvwkti      tmwitl   ixkx       
  ltkwvt wmj        lwkz zmt         dmz zi    wvt      
  tvtkxlwmt          mtazlw           wmxlz  lxvxltltl  
  itlxlzmd           xvjvzk           lxmtatkzvtk       
     vzaxi           ld zat            kjkdltltlxltlj   
    ldltv             m vw              kjltkj  l       
  jktixv              dmwaj             jvtlt           
    ltl               lxmt                              
                       aw                               
                       za                               
                       vxi                              
                       zvz                              
                       itv                              
                         jl                             
                          z  l                          
        i         i       vjiz                          
       vjkzi     lj        vzv                          
   tldldvzatlj   z         zvz         t                
    ji vxkzvxvj jl         vdlz jlj    it   jvtvt       
   jltltmzlzlwajvtlzi      xv mtl izlj  k  jktktl       
        zatkzvwaz     jltltmxlwl     vxiz  axvxlxadvti  
    itltatvzktmwkj        ldvtvd   tlj xvtkwadmwl kt    
       lxazljlzawv        wvzktmj ti    wiwkjlzkdkzmjl  
       zlzvj  itmw       jmz zvwk i     awmtvt  vdvdkt  
        tltltlzlzmd      kw  v aw      iwmj     zvj j   
       ji      zldmdltltvwmj zizmj     wmxkzvtltlwlj    
               v iwmx  vwmxvzvzvwmdltldmdiz      it     
               jv vwvzkwidvtvdk ajmxlzawi v             
                tvtmwkwatmdlxkwkwlxmxlwv lt             
                  vtmwm vwatvdvjmdldmwmzvj              
                 lj zmdv vwkzvwaw zlwm lt               
                 z  mwmwvzmdvzkwatlwmwi v               
                 v vwmtvzkwvt xmdkdkdmx z               
    lxltvt       jlwmj   xkxvxlwmt jlwm v       i  j    
    tixltvz     tadmj    azitizvwlz  iwkt      izkxkti  
     d  lzi   idltmx     dv vx zm iz  kwkwv   itidvxlt  
     vj   tltlxlzaw      ad    kwl izi mwvtv   iza ix   
      vz    ltkjvwv      tmtltlwmxvj tlzmzldkxvtitlt    
    jltldltl ixvtk        wl   mt zi  jvwatvjvtlxk   i  
        iz   jvtvj        vw  lw   zl   vzlxl    zltlj  
                           mj dk    tvj  lxvj   t       
                           tkjaz      lzi  zv           
                            zvjv        tvtijvt         
                            lx z           tltkzi       
                             i v              jlzi      
                               z                        
          j                  vjl                        
        vjktv                dv               ltvt      
       lxmwvzi               az              lzvwkz jl  
       xltvxkx    i         lxv         vj  ixkd jmtad  
   ltlxixl vtmx  iz         dvd          v  xmjv  xlxv  
  lz tvtktvz tmj z          aza          z jmj zvxltvj  
  zkdl  tv vzvxa v         ldlxv         ltaxvzv l      
  iz xazkdvtajvwlz         da lw  itltl   awljv         
  z jltkzkjltkwmwv         mzl mtvtk v ltvwazv          
        ldi  ji mx        vdatvdv  jlj   xm             
       vjv      xmj       dkt jaw    k  jmz             
        lzvtlj tiwk    jltmwltlxmt    i kwizitltltv     
       lt tl izktkwl     lwk   iwv     lwkzkt      l    
               z tmwvtltldmx   zmdltltvwmj z            
               lj xmdi iwadkzizlxmwi iwmx jl            
                vj wkxlwvzazlxv vzvwlzkw jv             
                 vzawidm vwvjkjldv mdiwazv              
                   jmdmzvdm vzv adktmdmt                
                  tljmwizvwitkziwvziwmjlz               
                 jl  wmz  mdktvwm  xmwi it              
                 v  zmxmzlwmtlzmwlzmxmx  v              
                 z  mwltlzmxv vxmzltlwm  z              
                 vjlwktlt wazizaw    vwl v              
     zkjlt        awm   ixatkxkzmz    awkj              
     v mxlzvj   tl mt    vd z z dv    tmjvt       z     
     tmjlzix  lxvzmw     za idi az     dmtvxv   lzi     
    jitl  tltltvtlwl     vw     wv     lwltljltlj       
       jkt    vzlzm       mt   jmj      axizaj          
       v izvtvz jmt       wk   vw       tmj zldltltlj   
   tltltvtl   v ad        aw   wv        dajvjk  z      
              xktv        zmj jm         ltvzizltmz     
             tvtv         vxk vx          ltvtvzkdl     
                          z d di              z ji      
                          v k k               l         
                          zijaj                         
                           z d                          
                          ja i   v                      
               ti         vdi    z   jvj                
               v        ziwkzitl v   k                  
              lj       jazaza  jlzv vjv   itkt          
        zvzvj z       tatlz w      vxiz  izvtmz         
        lzajkjvtltltlzatldi mj       zvt xlxvzvtvtltl   
  tvzltltlzktkz      it jmz xv        tvxkzlwkdljvt ji  
  iwl  jvtazada         vxitlw         xmdatkj zljkzkz  
  tkdkdl  z tmwi        wvtizmt        mwijvxvtvxvxaz   
  iz zvj   zijmd       jmz  vwkjlti   kwkzv axl v   v   
    zi izltlzvdmz      vwltljawi     lwajvtljktljv  j   
    i iz    izkwmt     daj  izm    jlwmzv      j        
      tkj    vjlwmzltlwmdlj tvwmxltlwmx z               
       j     z  adat wvdv vxi atmtidvw  v               
              z jmjlda azlzktlw jmdlwv lt               
              lt wmxmtidkjktvtmjldmxmtvt                
               lwvwmx xmx zm iwkjiwmzvz                 
               ti lwlzizmxvtadm ltmd  v                 
               v  dmwl lwkzkzmwijmdmj z                 
               tijmxiwazmx  kwmdatvwk v    ti   l       
    ti    tvj   tkwkz zkwkzizmwv itmwkxi  jvz   z       
     zl  tvtltvzvwa itixvxvzktmxltltmd tv ldmt jv       
      tkjv   kjlwmjvz jmzizit wv    zmdljltljlxk        
    itvzkzljlzvzmxvj  kdv lx  mz     datvzl ixkj        
   lxl  tlzawvjadl   vjad    lwv     ktk ktvwl v        
  itvdltkti vzvxv  jv  zm  j xmj      k vdi  tkzltlti   
     lj z  idazk  tv   iwi v mw       jvzl     k  xit   
        axldatl lti     axlxiwv                zltvzvj  
       vzktaj tlt       tmzadkz               jk     l  
    itvx zvjvti          dizmjv               it        
       idvtl             lxlx z               j         
       ti                 kzi v                         
                          zv  zl                        
                           z jldi                       
               i             vjvx                       
          i    z t           zk k             ix        
          zi   v atlj        kw zk            zvz       
           xltlxlzlzi       lwv  w        lzkwatv       
          z  vjk  zvzi      zm   ax      lzldlz z       
       tltltlxi k kzlx      ad   zm      xajit tkzltlt  
           v itkxvz zmt     wv    wl    jmtizaxitaj tij 
         jvdkj  ltazidajltltmzltltaz    kwvxaj tvjltkwl 
       izl vtizlj xktkwi   vw  at da   iwvzkt    i lz   
       j   zvwvtlj zazmx   zm v v ad   xmxvj        l   
         izljvz     jldmj  vwizkjkdv  jmzlj             
         j           z wmt zmdvjvxm  tmw  v             
                    ti kwvdmdmz tmwmwvwa  z             
                    v  jmwazmwlxvdmjlwmt  v             
                    jv  wmtvwkdlzlwktkwl vj             
                     tvzmwidm idl awlwmwaxi             
                    tvzmdmwmwvzazvxaxm mx jl            
                   tl vwixmwa ldvjvwmzvdm  zi           
                   v iwaz zmd zlzizmz jvwat z           
             zi    xlxmdltlwmdi  xmdltltmwvxktltltktlj  
     l      jajitlzatmwi   vwl    wv    jmzvdltkzi      
     jltltltkzktltlzlwl    zmd   zmj     xm v ij j      
           lj     jlwk     vxaz tkw       wadaj  v  j   
           z    izlzmj     ziwixldv       lwk vzizkwa   
           v    x zmx  ltltktmtltmj        mdltvtljkt   
        itvx   tvtkw       z zk ld         tmz zatvtlti 
      tlt zvxltk lwv       v  d xl          xvzvt jkjv  
    ltltkxltlx tvzk        zi a k           ixizv vtvt  
             vzvtvt         z tlx            itl ixit   
             z xktl         v  xl                       
         i   ixkzv          z  a                        
         jvzvzlxi           v  d                        
          tlj   z       tv  z  i       l                
                        vz  it     z   jkzv             
      jvtv              zv   v     itvzvxatl            
    l azvtv             vz   z      v ldvxv             
  jlxlwawmxi            dk   v     ij zmtvz   jltltlt   
   t jazvjad           tvzv  z      v mz zvzltlz        
  jltlwlz jmj          aj d  v      zlw tkj    l        
       xktlxk          w  m  z       wvtlt              
       ijvjlwiz       ta  dv v      zmjlt               
         jvzmdv       advzvdiz    ltmwvj                
            jmz jltl  wltlxmtktltl lwv                  
             dajvxi lxmz  vwvz     wadltltlti           
       lti  xlwazlzvxawl   mdv    jmxljvtltlzmzlt       
     zv  tvzv md   tida    xmz    mwkzk     itm  tl     
    ji     vjldmzltltmdi  jawktltkwv it     j w         
           jv iwaj  kwltltvjmwi lxm  z     jazv         
            x  awkjvdm  xk  wmdlzmx jl      jl          
            izijmjvwiwizlzvtmjmzlwvzl                   
              zlwaxmjmzvxkzvwvwmwa                      
               tkwmtvwv kd zmxiwmtvj                    
              tl kwltawktixmdizmd  v                    
             jv  wmx zmzadvwa awm  jl                   
             v  jmdadvwajidmwaxvwl  z                   
             z  vwkt zmzijvwatizmd  v                   
             lj wa   kxvxvzkdlt zmjvj                   
              vxmj   dvzijvxm lz wvz                    
             itvw    mzizvjkwl izadlxl     lt           
     tv     kdvwv    wktkxlwmxvt zmzldlj jlt            
      jvt tkzizm     az   zvw zi  dmtixltl              
         t xvjkx     da   vda  zl lwvzkj                
      jlzlxl  wi     lw   zmz   tv mtvzktlj             
   tltija vt xm       mt tlw     jvwajidl kxltltltlj    
   l  jkzlzazkz       xk vxk       ldkx jlza            
  vxltazktkdlz        iw zmj        vtaxl vw            
   ktlda ldvzl         mxiw          lzidvxkzl          
   j  vti              tazl            jlxmxlzat        
                    tl  dk              tkzmzltl        
                     tl az               tazvti         
                      zidv v             ij             
               jl      zv  d                            
               v    t  vz tk         ij       tl        
      vjv  ti  z    izlxktkxl         v       v         
   itkx wkdkj zi  tltkt z x d         zi   vzmt         
    itkzktvdkzv lti   lzvtk a          z jazmxlzi       
       mtvwixaxvj       dat zktlzlj    vzazaxvxltlzvzi  
   jltlzkxawazk         vw tiw xl izvj xlwmta itlzlx    
         ltvwmtl        waxlzmdk     vzvwmjit    kzl    
          k iwmx   jltltmdltlwaz      vwmzvz   jvdit    
           vzkwmt      lwl   kw      iwmdvtvtltvz t     
      ltltltvzmwmj     zmt   tmzltltldmwkj      i       
     it      vjmwatltvwmwvtizlwawv izawijv              
             z jmdvtlwvda vwl azlwvzlwk v               
             lt xmzkwa awvzkzvwvjmwawm lt               
              ltlwmdmtvwazvdl mdkjmwmdat                
               lxvwmxltvwkzlxvw jldmz ti                
               z  mwmt jmwkxvwatidmwm  z                
               v lwaxmdkwmj zmwadktawvz                 
      ija      jvwmxlj jmwkzlxm   lzmwkzi               
      zlzlj   zvxmx  i vdlxvxlwv    zmx jl              
      idi    xizmw    lwmtatl mz     dmdvzi   izi       
      jlz   zlxmwl     kd zl  wl     idmzkdltlt         
       jvdlzajkxk      zm lj tm       vtvzvtlzlj        
  tltltkzljixktkj       wl k kd        vtat   xitltlt   
       w    vzvj        kd z wl               lt ji     
       vj   jl          jmtmza                 ktvj     
       xkzlzk           ixmwmti                z jlj    
     itktv                dvd                  v        
    lzvtit                vwvj                ij        
       ij                  a v                          
                             x                          
        t                    vz                         
      izvxl v               lzv                zi       
       i  taj               zvz                lxl      
          ixvtl             kzv            jlzkdmx      
         lzvzvti            dld         z  ktvxvxv      
  ltltltk v lzvx  v        tv m         v vtkz tkxlj    
        zvzlz tmzlj        aj w         jvwajkzvxltlj   
         xijvzldmz         w  kxltlxltlziwmzadl         
         iwi vjlwk        zajlxm  jv   lzmwltl          
     jltkdatlxvjkw        azktkwi v   l kw tl           
        xitatltkxmx       wvj xmz z    iwkzi            
       zlti lj tlwmj     xmzltkwajlj   dmz  itl         
       i izl lzldiwa     kw   zvwl    zmxktvj jlt       
         jl     ktawvtltlwat  vxmtltltmwltl     l       
         lxi    z jmdl  dmxvtidlwmj jkwk it             
                v  dmzldmdv lzv azmjvwmj z              
                jl lwvzmtazljvxiw wa mx tl              
                 jvzmwmwvdkjkzkjmjawmwkzi               
                  jvjmwltmx zaxiwv mwktl                
                  k  dmzlzmxkjadmjvwm  ti               
                  z  mwmjvwkzkxmd xmwl  z               
                  v lwadmdmdizvwadmzmd  v               
                  z dmxlzlwvzvzmx  lwm it               
                  l mxizlwkdvwkzmt  iwvt      ij        
                 lxmwvt tmzltvz w    awkzi     v  j     
          i     vxlwaj jldv vwi m    jmzvzi   lxltv     
          jlt  vxvdmj jv ax zl iw     watkd  izajitl    
            ltvdvzmw jk  xa v  zm     lwijkdltlxi       
     ij   jvtkjktlwltv   lw z  ad      ad  vjltvtltlj   
    lxltlxlzkjvxlxkzl     mtv  wl      xlzk             
     vx  kxixmjktvz       xm  tm        x di            
      itljkwvzldat        iw  kx        itl             
         lwmzlzv           mt w                         
        ltadlzati         ktkjk                         
      tazljv ij          lx xvj                         
                         za vz                          
           lti          jkxkjv                          
          ixixi         kziw          izvt              
           vzvx        iwv kz         xlxl   i          
  itltlti  z zm        xkz tm        zktv    jl i       
     izlxltk  wk       mtv  wl       mx zitltltldaz     
  izkzl vzizktlw      vw z  ad      lw tatltlzlzlwat    
   lzixaz tlxizmz     da v  zm      wkzizltlj tatlj     
   t t  i   lxvxm    tmxldktlwlj   tmzlxvj  ltlji       
              tlwl    dv kzi m     mxlti      ti        
              ltaw    azvxiz w    lwvz                  
              z jmxi  zaxazlxm   iwa v                  
              v  wmtvzvwvx zmxljldmt z                  
              z  lwadltmdktvwmxmxaw  v                  
              ix  mwv vwawvxad jmwv  x                  
               itkwmjvwajmzlxmtltmzizi                  
       j  lt  izvwlwkzmz xaj watmdmz                    
       vjkz  lt xajawiwadkxvzm vwixmzvt                 
        kd  lj jmdk mzazixvt d wlxkwl lt                
    j    ltiz tmwktl awktvxvjmdv  zaw  v                
   tvxltltvwaxkwk  jltmdl vjvwvtltldmwkx                
      tlzlxizidm      xm  z zm      wmjkxazltlzktltlj   
           t tmj      lwv v md      iwlz  itltlt        
             ax        mzizkwv       kd      i iz       
    k    jvzkwi        dvzkjm        jmzl   kjijizlt    
  j jkt  v lwv        tvwlxadltlt     zmtvtlxvzkzkj     
  kwvtltazvza           m  wl          wktltlj dl v     
  tktktlz jmj           xl m           iwizktvxi  z     
  vzvti vtax            ixiw            kw zizvtlzvtlj  
  jv   lzvxi             kzkj           jkxv iz         
  ij  vzlzi              xv v            zlxvj          
                         vz z             tvzvj         
                         jk vj                          
                          t  v  z                       `;

export const SIGIL_RIGHT = `                       d  v                             
                       kj z                             
                       zvz                              
                      tvxv                              
      it        l     k az            ltlzi     l       
    jvjlzi  zi  tl    w zv           izidlt     jv i    
     jkzix  v    z   ta vd       jv  xlzv ixlxkzldkj    
      z xlzlj tltatltaz zm        z zkxixljitvxvxvd     
  itvzkzidazvti lxvtvwvxkwktkxvj  ktawltv     lz  kti   
 itaxi vjvwm  tvxvd tmtidvd   tljkjmwl vj      izvd     
   tixltl vwlzi i a kdl vxm  jltazlwatkxlti     vjv     
     ltltvzmw     xiwa  zlwltl   vwmxvxvxkzl            
   tvj jvzvxmx    i mt ti mx     zmdktv  titi           
   i      ziwmzltltawkjv vwmzltlxmw z t    l            
          v lwat  adajvxvtvwmt tkwk v     lxi           
          z  mxktkdvd tmz zajmzktm  z                   
          lt tmzkwizazlwltkd dmzmx jv                   
           ltlwkdkzawlxadldmzlwkwvzl                    
            vxkwmjlzmjiwl mxv kwvtv                     
            z  awit wadvxvwl kdmj jl                    
            v  waw jmwldldmt xmdk iz                    
            z zmzldaxmxvjawkdkjkw z                     
     j      vjmdlt  advzvxmtl ldmzkj       t  vz        
    jlzi   vzkwk    wltajvdkjvjidmtlz      izv v        
    vtl   vjiwm    tm kzljvwl vtlwajiz     tlx zvj      
  tatkt  vjvxmz    kw jax dazi lzawvzv   ixl idi        
   jltlxvxkjad     tmtlxitmdiz  idkxidatlzv izi         
  tltlzvtk vtv      wl v  wv  xi  wvzv  tatkxltlti      
         xvjk       mz z jmj   xi lxkwi  jv             
         lxvj       zmtmxkw     zl lwvt   z             
                    iwixvdv      tljatlzvda             
                     azvzm  zi     vdazvxlz             
                     jatax  vz      vzl  xl             
             l        w di izv      j tlx jvt           
            izl       ltmj xlxi         izvjlzi         
           vtvzlj      vtv m lx           jvzvzv        
           zl itl      d zld  mj        izmxvxlzat      
          tvj xvjv     i iwv  dk        zidv k   i      
            v vtvzi      jm   vw       zlxvj z          
   i itltltiziz jax      kwi   mj      aw  v vjltlti    
  vz jitltltkdaj xm      wkz   wv     iwl ldkdl         
 izvzkt  izl  taziwl     mzv   ad     xmjvdi kxl        
 j jl    z     xktmd     w zvtixa     mxldv   kjl       
                zadmj jltmtvxktvd    vwaxltkzmd         
                  iwk    w xvjvza    waj  lwvzi         
                 ltkwv   mzldvxkz   dmjv   lj           
                 z jmdvj zmzlxvwi lzmw jv               
                 v  wmzmwkwk kdmxmdkwk  z               
                 z  vwmt xmtvdkwl vwmj jl               
                 iz tmzv mdajkxmxitaw  v                
                  ltawa kwl aw xmz wmxkj                
                jvzkwkwvzmjlxaxkwkwmdmtvz               
     z          k  wk mx wvzvtaza md wk iz              
     iz        lj tmdkjmjm lzvz dvwidaw  v              
 jvzvzkxl  jl  z jmdv  zmw tlzvtmwi izmdijl  z          
 it j   zltvtitkzkwatltlxmxi  xmwltltvwmxkzljv  ji lt   
    itltlxvzvxlxlxmj     wvj  vda     vwlxltaxvxvtl     
          jlti  tmx      md   zmz      awl  jkx    lj   
   j          itkw       xmj  vwl      jmzlj zixltlj    
   kj  itl   vtlwl       lwv izm   i    xmzkxktkxlzi    
    vjlzk   vjlwm        jmzaxkdltl     iwktvdkxidvjlt  
    jvx z   dlzmt         dvj dv         kwldkzazv vdi  
       zltvxi aw          ld  mz         jmx zvwkxltlt  
 itltltltizltkxl           m idv          xvzvzlt       
       zvjatajk            d zvz          ixawax        
      jvdkwktkj            vza v           ldkxv        
        vj taj              vx z            iti         
         i                  zk v                        
                            adiz                        
         ltv                zkz               tvtl      
        vzijk               kzv              tvjvz      
          tmtv              xvz             jkxkj       
      lt  izmd             jkzk         i   kwlzk       
  jltlxltiz jmz            vzvw         z  iwv kz  ij   
  lj  itvtvxizm            witaj        it xa lwatltlj  
 izvtvwi   vtlwk  ji      jmz zk         vtmxvdawvti    
    admdi  jv vwi v       vdktlw         zmwvxvxljvtlj  
   ljixltitltmdmdiz    itlwkdkzmtl       vwvziji        
         tlxmxvxmd        mdi vdv        wa             
          xat  iwmtlj    lwa   md       zmz             
        izvti  zkwv i    zmz   xm       mwvxltmdkzi     
       vz   tlzkjmw      awk  jkw      vwvtktl ixlxv    
      lx       zldmdltltvwax  izmdltltvwmt z    vzij    
      tkj      v iwmz  vwmdlxvt wmwi iwmx jl   it t     
               z  awltlwidajvxv a mdlzawi v    t        
                zitmxiwk awizkjvw tmziwkjvj             
                 tvwmzmxkwmzaxktmtvwmxmzv               
                  jkwmw xmd za iwktlwmdl                
                 jk kwvz zmzvjkxm ljmw tl               
                 v  dmwi lwkxktmd  mwm  zi              
                 z  mwkwkdmwi kwaxmdkwv  z              
                 v vwktlxvwvj zmxljltmw  v              
                 z dmt zlzmxkzlda   lwmj z              
                 vtmxizi azvjlz w    iwkzi              
                 tkwvxltvwktvjvjm     mwvj      i       
               izlwmj  izazixat w     zmtlt     z j     
       tv     vxvzmt  iz dk  j jm      watkxkdvjkzati   
        jvzltvtlxmw  lt  kd    vw      kwvjvzltaxl at   
        lj   jawlwvjvt   tm    da       mtizvjvj z z    
        tltlxkz zmzv      wl   mz       xm  zvtltktltl  
   tltltlt jkz jmdi       mx  iw        iwv vz          
         izizvxmxi        xm  za         kxlwi          
        lzltkzajk         vwi at         tvdvzvt        
      tktltlxktvj         zvz w           tlzix         
      ltldi  zl           vjktv               i         
        tk    j           jvzv                          
        lti               vxvz                          
               v          za v                          
         jvj  it          kxv                t          
      jlxvw   z          izkz        v    d  v          
       jmwazi v          xizk        jl  jaxkx          
   itltltadlxixltl       m iw   ti    z  kjaxv itltlj   
    izlxlxaxadv        tadltmxlt      v kzkxktlj        
      ti itlwmd         wizlxk        zvwmzk            
     jl   lt dmj       tmzitvw        awatlzlxl         
       ltltvzvwmj      awi  zmt      iwmzvz  vtvj       
      vj   jlzawm      wk    wa      dmxltltlzaj        
             v awmtltldmdi  tmwvtltldmdvt    itl        
             z jmxkjlwlw tvzljmda ixkwi v    j          
             lt xmtawv mjlxvz d wazlwv lj               
              lzvwmwmtiwvzkdvdmtkwawmjlz                
               vzvwmtlzmt dk kwk kwmxkt                 
               z  mwkj dmdlzkwa vxmz jv                 
               v lwawazvwvtvdmdlxmwm  z                 
               tiwmxltvdmz jkwmxvzkwvtl                 
             itvdmxi   mzvzvzkw   zmwkzi      jlj       
      i     izizmw     w zitlzm    tmx tl      xaj      
       vzi  xvxawi     m  zv vw     xmdvzi   itaj       
        lxktajmxv      wv i  xm   ijidatvxltlxvxltitl   
    jltlxix wljmtl     axltltmwltlt  vtvzvtlxvtv  zv    
         jljkdvdaj     tm l iwk       vtaz    itltlt    
        jljkzkzaj       wlz xkz                         
         zmj jlz        vdatmjv                         
         l lj           tmdaxiz                         
                         tax  v                         
                          dv  z                         
                          lj  vt                        
                             lja                        
                             z d                        
                             vzk               it       
                             zkzi        jvj tvzixv     
            tvzv            zixiz       jazl ixkxi      
            vzkjk           vja m       aj z xkwm ij    
   itltvtlj   xazl          zvz di     lj  vjmwkwkjlj   
  lt tvj  lxkzvjmw  ij      vwijadlzvtlx   jmdizatmtl   
  xkxi   ixi idvtmt z       zm itm lj  izv iwktvjiz     
   xlzltvtitltazkdm v      zkdlxiwi     ltkwajvj j      
  tizi vj   tajvtvwkj      vwkt zaz       tmzvj         
       j   jvjvjldawi      zmx  ida       md   jlti     
           ltltktlzmx  ltltmwvtltkw      kwixlzi  tvj   
          ixvtvtvtvzmt     dmj  itmj    vwmzk       i   
          ti     ltlwmtltltmwv  tvwmtltlxmt z     tvj   
                 zi kwaj jmwvjvtl admjidmw  v      t    
                  z jmdkjmzmzizvt dvxmxlwl lj           
                  lj xm aw wkzlditmzlwvdmjvt            
                   vzvwkwkzmx zkt watkwmxkj             
                    izvwm vwm vzltmjvjmd jl             
                    x  mwvjawkzldaw jkwa  z             
                   ti iwmx xmwvzvwatvwaw  v             
                   v  xmzkdkwaj tmdaxvzmz z             
                   ti mwktlxmxkjkdmjltlwm v             
                    zlwv ijadktatlwi lzvwlj    v v l    
       jltlzi       lwm    wajl v mwi  zmwkzl ixawiz    
       lt jatlj   zazmt    md zvj wvzi  zmtvdi ldixkz   
   jl  jlz di    zvzmw     da  z  mt zl  wmxvdvdlzvtat  
    jlzvzlzkzvj zmtiwv     aw    lw   jl kwvtvzltatlzi  
     zi  tltkdvzk  xm      dm    zm     vzadid          
            jl  z tkx      vwv   mz       xvxkzi        
            vti idvxi   k  zkd   wi       izidvxv       
        zljlxldkzktv    dl izm  za         it   t       
        ixi ljij ji    jvx  vdl at                      
         ij            kjk  zlx w                       
     t    vzl          w xl v kjv    ti                 
    tlzvtlzlzvji      ta lw z zv    zitl                
    lxizv kzmdvj      mt  mjv id   jvxmzvdi             
     v itvz zmz      iw   dkti l   kdixatlz             
  itltktlzv  wa      xa   vw z     wk lt tk             
         lxl lw      mz    mjv    tm  zvtltltlj         
      itltlzvtmt     wl    wvz    axlzk                 
     vz   tazlwm    jm  t  adv   iwkjvzvtvt             
    ij      lzvwi   vw jkz daz   xmtaxi    tl           
             itmx   tm v v vdv   mzlj       j           
             tidm    wizvjkdkz  vwkz                    
             v lwk   mdvxkdmzv iwm v                    
             z  mwltlxaz tkwvzvdmz  v                   
             v  dmxmxkwkjidmdmzawi iz                   
             zi lwmt dazazawv mwm  z                    
              z jmdkjmdk vzmdvtmx jl            t       
       t       zmwm aw  kt dmtvwmtv             v       
      jv     izkwvwvzmjixv kdvwawk              z       
  itkzvz    lz wmjmdvdvjvjvzatmzkwlzl           vjlj    
  tl izkj  it jmdvjmxa ixv vdadvtmz ti          xl iti  
        lt z tawk  tmd tizizmwi vwmj x         x        
  tltltltvxatlwmzltlxmdi  tmwltltmwvtk        zi        
    lz   jvdlzmt     wi   iwk    jmwldvtlti ixi    jlj  
     itltizvjmw      mdltlzmxltl  xm vtvtitazltltltl    
          vxvwaj     dmj  vwi     iwvz   jl             
      jltljidm       vdk lxm       aw                   
         jvzmz       jmjvtkx       tmj                  
        tvjaw         wlj wl        dmzvj    lzv  j     
        kzvwv         kz  m         lwljk    jvzixaziz  
 itltlzkt xm          ja vx          axltv   i idmtaxi  
  ljiz z jmt           w dl          jmj dvtltlt  vwlz  
 ixvd  v ad            k m            dm v  tltlzvdkxi  
   ti  jmtv            tad            lxkz       ji     
   l ixljk              wv             ktkj             
      ltv              jat             jv vz            
                       vd               jlj             
                       zk  j                            
                       v  tv      z                     
                       z  vz   tijl   v                 
                       v  zv   ljv    zi    tkdvti      
      i ij             z  kx    vz    ldi    z  vz      
      xvwvj            v lzkxltltkz jatv    jl  zi      
     zkdazlt    v   lt z wljm  tkzktat z  izvjvzv       
   ltlxlzvzvj   z    v vjm  dl  jijlz zk  xixktkzvtltl  
       jvzkwaj ti    taxazltvd      iz xldkdvxi it      
         k vwatk  tltljvwltlzm       izvtmwltl          
         jvtvwvjvtijltlxmxltkwv       ktmd tl           
     ltltlzvtawvz      aw    md      ixmwvzltlti        
    kwi    jldmwazltltlwkj  ixmj     dawazvti  tlj      
     l      zijmtat jaxmdvtltlwawltlwkwvjl       i      
            it xmjkzmz wvtkxi m vwldldm iz              
             vj wazmwi mdizvtlw  mwvzmj z               
              lxawkwitawa kx tmzvjmxmdlzi               
               v lwvjl mwvtvzawizixmxvx                 
              lj xmwv  zmdkdkwk  zmwk it                
              jvjmxvdkdvwa  dmxadazkw jl                
     z        ixawati  dmwvzlwk  jvxmxk                 
  jkjaj     jvzvwaj  izmzazkxvwl   iwmzvz               
  kdadmz    vjvwm   ltlwktkzi m     iwmtiz              
  jvzkdmx  lxkdat  lt  mz dl vw      vwaxvt  l iz       
   t  lzaxlxizlx jvj  kwk v  zm       kxvtaxldvt        
   ltlt   jkx xitv   vjvw zi mx       jvzlzv ldltlj     
           tlzizl  jvj  mt ziwi       lxvxaz  lzi       
             lt   jl    xk mxk         ltvzltkzlwi      
           jvt  lti      wawmj          vz   jlziz      
          zv itlj        vtkx               jvxi l      
        izltlt            kdv                  tl       
       vtlj               zvtl                          
                          itiz                          
                            zv                          
    i   i                   vdi                         
    z  vz                   zvz    i                    
    vzkxmtlz                vzv  jv v  ji               
    ja itlzlx    lj        vzaz  k it   z    lzlzl i    
     zijltadkz   z         d za  z z    lt  kzaxlx z    
   ltlzltlxvdmzlzi         m lwltkjizl   v iwmwmtmxkt   
         jmtlwktk         vx  m   itkt   zlxmziwmwkzvj  
          zvtvwiz       jvwktlwv  j  itl vjmxvzl kjv    
           tvjkdv        jmjlzawlti  jltvzkwl k  t jl   
             lzmd        vdv  xm         awvzv      j   
       jltlt   xmz       dm   kwv       vwkj            
      zl   itvxlwmj      mx   zmx       wmz  itlti      
              vjkwktltltvwvj  vxmt     xmdvzvj   jvj    
              z  mxkj jazmjljlxkwazltldaw  v       i    
              lt zm kjmz w jkxv ajmjixiwv lj            
               vj wk aw  mtlzldvd tmxixm  z             
                vzawawvzkwlxvdkxmtkwazmtizi             
                 ljkwa vzmt dajkwajlwadat               
                it  mxvj wmdizkwk kjmw jl               
                z  vwmx jawvxmxmt  kwm  z               
                v  wkjkdkxmx zawvxazvwl it              
                titmxvj  kwljazmj jltmw ti              
                 jmwi    wlzvxkzk   ixmjv               
               lzawi     m vjvtvd     waj               
      iz      kzlwa    t w  ax za     lwkdv             
       izvj jktvtmj     tmzldltkwi     mwvxk      z     
         zlzvxl md       wv v  da      tmtvdkj jvti     
       ltvzljv kdi       adiz  mz       wa  wvdvzltl    
  ltltkj     zljk        tmz  iw        lzk ati iz      
    tl  j   zvtkj         wk  xa         kjaw  i at     
   jvt  vz   jvj          vd  mj         jlxazkzltkj    
   k ltaz                 zm iw                  it     
   z    lj                vxizl                         
   v                      zizk                          
                         ti vz                          
                         v  zi                          
                         x                              
         iti    jk       kz             jvj             
        lzizi    tk      xv         i  tltkj            
       l izvx  l ixv    jax         tljkzvjvxktlti      
   tlxlxlz jmtvj tkzlti kzkt         zkdlwkdkxltlti     
   lxkzlzmxltmzvz       wvtk         vwmxazizvj         
  lxmxazljvjvwaj       taz wi        wmzvz zv lzij      
  zijkx z  vzkwi       mtatkx       zmxvt  lxlzkd       
     xitvtlti mx      iwvzlzm i     mx     jltlxiz      
            tvxmj   jldmzktkwvj    kdk        zazi      
       tltltlxlwm     mx z  mx    iwajkzltlti   l       
      jl     ktkwktltlwkjv iwmtltlwmxlz    lwi          
             z  awl  xmtlzvzvwv  zmt jv     i           
             lt jmtvxkw tmzi awvzkw  v                  
              izlwatmjmzlxvjkdvwiwkzl                   
                jvwmxlwi az zmjmwmzi                    
               tl vwltmdkxkxmxvxm  ti                   
               v  xmwidmzaxkwvtmwl  z                   
              lj  mdvxawkzidmzkzmd  v                   
              jl vwl  dataxvdaj zmj z                   
               tlwv  jmtkzkxkwkx wazi           l       
       i      jvtm    w jvw zmjizlwlxl     ij   x       
       jvt  lxvtmx    mj tv kdv  zmxldkj jvz   zi  t j  
         itlzltvw     wv  z dkjv  tmxlzvtvj   tmzvtlzi  
          itat xk     kw  vjmj jv  wktldijl izi  tmd    
     itlzktix jmj     jmj  mw   jv vwlzvjvtlxltljvzl    
     j  vt jatvw       xk  wl    jvjvzkxi        j      
    jljidvtkwkdaz      iw jm       ixvxvtv              
    itvjadvzlt  vj      ktkxi        tv  jvj            
        tl               vz z  vt     jlti vz           
                         zl v  zv        tltizi         
                         i  zi kx          itldv        
                             zlzvt             tl       
             lt  i           vw ja                      
           jkti lt           zm  wi                     
           ktvxvx            az  kx                     
          lj   zvxlj        iwv  tm          jlt        
          z   jvxv k        zmz   wl        zldax       
     jltltlzkxvtvtazl       axv   ad       jktmx        
    jl   idvz jldvtmd       wvti  zm       kxa mzvxkt   
    izvzkti i   ltvwmt      mz wv vw      iwmtkxkx  lzi 
    z  lj        k lwm      w jktizm      dmxiti lwi    
       j         jvzmwk     mzvxizvd     tmd zl  jkx    
                    zmwvtitldaxaxkxa   izmwkzi          
                   tixmxixadawvzizmxvzltkwaz            
                   v iwawmtltmxvjkwvzvwadmt z           
                   z  mwat  kwkdvxmz  vwmw  v           
           i       ixlwmxiz wazaxvda ltvwa lj           
          vj      izkwmwm vxmt xk vwkt wmwadl   l       
          zizltltiz tmwkwmj wljvwitmjlxmxmw tv  zltlt   
          kt     ti mwizmwi mjvtktlw  mwvtmx zi kj      
       i  ti     v vwvzvjmw w  kd  m awizldmj zvzlti    
       zljix     z wmwvtltmwmzvjvzlwawi  tawatkx   zl   
    jl ixmd xi itkwmwi     lwkj zidmtltltlzmwaxltltlt t 
     jlxaxmdvdvtltmwi     i ad  v awi      zmwltlt  itl 
       kxkj   tljmwl      jlxmzlxvwk        dmdvtlxvj   
      lzm    jv vwa         lwv vxmt        iwm lzmxlt  
  tltltkzkt  vtkwm           mtvdlw          lwmtkxlzl  
       xlzvxldlwkt           xvzizk           awvtktlj  
   itltktltltaxix            ldv at           jkdvz     
       t  ixltix              mz w             zltat    
           ltlzi             idmwa              zkjlxi  
                              lwkt               tlt    
                               md                       
                               dv                       
                              jkz                       
                              vzv                       
                              zlj                       
                             ti                         
                          t  v                          
                          vjiz       j         j        
                          zvz        it     jvxiz       
                l         vzv         v   itldvzatatl   
       lzlzi   lj    iti vtaz         ti izkzvxkz ji    
       tlxlxi  x  itvj tlw zk      jvtlzidmtvtvwltlti   
  jlzadktkzkd  vjkz     tmtkwltlti     vdmzvxldv        
    lx tmwadmxlzk itl   azlzat        ixmwlxvzldltlj    
  tiwvxaxvtixmjm    jl iwlxvzm        zmdvtitvdkt       
  lxazaz  lzlwmd     j xmzv vwi       mwlj  izvtv       
   i izv     iwmj      md z  mx      awvtvtltltl        
    itmtltlzvxkwm     iwvjv iwmzltltawatv      ji       
     lj      vjawatltawmzvzvzkwmz  kwmj z               
             z jmdvtkwid xazlzajmxvzmz zi               
             lt zmtkwktmxmxktawldmxmwlzl                
              izvwmwatawizazldmz wmwlz                  
               lt wmtv mdmzvxmz zawv it                 
               z jmwmtldmxvzawvzmwmw  v                 
               v kwaxaxawk lzmxvzlwmz z                 
    i  j       z wmti lwmtkzkxk   iwmti       lzltkt    
  jlxkxvj      lxmj  vtmzvjljvd    iwadl     vzltkjl    
  ltkzajlj   zmxmx  vj wv kz za     kwltaj   jvt  a     
   kj dvj   zlzmw jvj tmx    ad      mdvtktltl   iz     
    ltljlzkxatvwvtl izkwmtltlwl      zmzixlt    vz      
  j   xktlzizldmzi  jv lw   tm        xlzkj tltatlti    
  itltv    tktvz   tv   mt  mz        izlzi   vj        
       l   izkt  izl    xa iw                           
           zv  jvt      vdixl                           
         lzijlzl        zizv                            
       jvxltl           v kt                            
      jvti              z j                             
                        v                               
                        tiz                  i          
      lzlt               za                zlxiz        
  ti vxmzvt              vd               jvzmwkt       
  adlwi axkj  iz         zkt         j    kxkzltk       
  zktk  ziwk  z          aza         vj  kwlz tkjktlt   
  izltkzv iwi v          dvd          v iwl vzlxlzl vt  
      t zvzkdlt         zktat         z dkzvz zl  taxv  
         zitmd   tltlj  mt da         vtmzidlzaxvdk vj  
          zvdmzlt z xlzlw tvw         zmwmxltixvxlti v  
             wk   iti  zazldaz        kw ji  jat        
             vwi  x    mdi lxa       iwk      ziz       
     zltltljvjmx j    lwktltmwlti    xmjl itlzvt        
    t      lxvxmt     zmj   xmt     tmxlxvj tl lt       
            v iwmzltltawv   kwatltlzmwl v               
            ti kwmj jmwktvjvxadmj jawk it               
             zi mxvtmzvz zktvdvzmtkxm iz                
              zvdmjaw zatixizmz wajmdvz                 
                lwawlxad zvz wazvwawi                   
               vtiwmjvzmjvxljmzvjmwitl                  
              lj jmwk  wmzlxaw  vwm  ti                 
              z  kwkwvtmwvtlwmtvwkwv  z                 
              v  wmtltvwkz zkwvtltmw  v                 
              z tmz    mdvjvdm ltlxmtiz                 
              ixmd    vwvxkxldkj   wmd        ltixv     
     v       lziwl    za v v az    lw tl   izvtkw z     
     jvt   zkzlwa     vd jaj dv     mwvzkt  kjvtiwl     
       itltitltmt     zm     mz     tmtlzltltl  tlji    
          idvjkd      iwi   lw       wvtvz    lxi       
   itltltatv iwl       mz   xm       lwi vzlzvj z       
      v  xizida        zm   md        ad z   tlzltltl   
     vwltvjvzlt         wi iwv        zlxk              
     taxvzlzlt          kz xkz         zlzl             
      ji v              ja a v                          
         t               x x z                          
                         idijv                          
                          a v                           
                      z   j di                          
                izi   v    jaz         jl               
                  x   z tljvxmjv        z               
          lxlj   ziz zvti  dvdvdi       it              
         vwlzvj  vjkz      m vtldl       v izvzv        
   tltlzlzvzktk lzv       iw jatldvtltltlzixidvt        
  ji lzitaxmtvxkzl        zk vwi lj      vxlxvtltltvzl  
  vxvxitv ixldawk         mtljkz         dadvdlzi  tmj  
   vdkzkzlzkzijmw        lwvjlzm        jmwl v  taxaxl  
   z   z tkd zvxmx   jltixmz  vwi       awijv   izv vj  
   i  zitlxitlzidmt     jmditltmz      vwazvtltvj jv    
        i      zvwmti    wvj  ida     lwmxvj    vj j    
               v kwmtltkwmzl itawmtltvwmtiz    ixl      
               z  mzajlwld jkz zazm ldad  v     i       
               lt zmtawi mtlxvtvd datiwi v              
                lzlwkwatiwlzlxixajlwkwm lt              
                 vzvwmjixmj wv kwk kwmzmt               
                 z  awlt wadlzkwvjvtmt jl               
                 v iwawijmwvxvxmt tmwa  z               
       t   jl    z xmzldawmx  kwvdmjkwijl               
       v   vzi  jkxmwlj zmwvjvxmxv vxmxl   izl    jl    
       zi lwat zl awltltkwlxvzkzkjlj dmzvzltlzl  tv     
        xktitltitawv    zm ljvjvwi vziwmtix   zixl      
        ixkj tvzlda     vw  kt zax  izkwvzvtitvxvzlj    
        z tmzlx xlx     zmt    adiz   tadizmdvtl  tkt   
   jltltvxl  jaz x      iwk i  wv  zi  zkzvz jlxltazlj  
   ljk  x     tvzi       mw z jmj   zl  xvdaj  v it     
  izvzltv                zmjktkd     jlt tldatkd        
  t     xi               vxadvwl       ltl idlxvz       
        lj               ziwvja          jlzizv kzlj    
         i               v ktkt             tlzaj       
                         z jvx                 jl       
                        tv  zv                          
                       jati v                           
                       kziz             j               
        kj             x xv           l v    j          
       vzv            xv mx        itld z   jv          
       zldmxvt        m  zmt       jvtvtktltk           
       v vtatvt      kd   wv      jvzv  xiz  v          
  ltltvxl ljidk      wv   ad      ktvx x jktltltl       
 ijl idljkdvjlwi    tm    zm     lwv vzkxlj z           
 tmxltizl idkzmx    vdltltvwltltidajvdlt  ixazi         
   vt j    lxvzmj   da ld  mz   jmxlxk itvjlz tvj       
   t        izkwk   ad z z wv   kwvdv itlzmzv   i       
             itvwi  zaxixvjmz  iwati     vzitvj         
             z  mwl  wkzizawv lwm v           i         
             v  dmzmwmwl vwawazmx jl                    
             z  lwmtiwazktmwvdmwi  z                    
             iz tmxlxmtvtaxmzlwm  zi                    
             jkdmwmtmd taj wajmwvzl                     
            ti kw wkdkzvdvzmwmwawvzl                    
           jv  wazvwmzizat dmwkjmz tl                   
           v ldmzi vwvjvtv awv vdmj z                   
  itlxltltlxkzmwltltawk  jawmtltawktk    jv             
      jvxltazvwi    zm    tmz   jmwldvtljidi      t     
      i ij z wk     iwv   awv    tmtvtltlxvxltltlti     
   i  z  idadm       mxl vdkz     xmti     it           
   dmxvjvz xmt       zatkjmjv     iwvtvj    v           
   lxitlzltaw        iwltlwlxltlt  kwv k    z           
 jltlzldv vwl         at xv v       mxlzl   kzlj        
  zixi lzvzk          tk a  z       zmt xltkzv ltl      
  lzlz zvjkj           x d jv        xvzl ktltkxltlt    
   ljkj tlj            ktl v         lzlzvz             
                       tk  z         tlxk v             
                        d  v          zvxkj   j         
                        a  z           jktvzvzi         
                t       j  v  zl       v   itl          
             zvxi   v     lj  vz                        
            tldkzvzlj     z   zv              zlzi      
             zkzat z      v   vz             zlzvd t    
   ltltlti   vzlwv ij     z   xa            jkwmdmtkti  
        vtltvzv vw z      v  zvzl           adizvdi l   
        t    ixl mtv      z  a id          iwi vtmtlti  
              ltlzm       v  w  m          xktlxk       
               ltiwv      z za  dl       vjmtizij       
                izmwlt    vjazvzad       zawvzi         
                  zmt tltlxlwktltm  tlti vwi            
           jltltltadm     vzmz  vwkt jkzida             
       ltvwvtltlzitkwi    zaw   tmdkzvtvdmtk  jlt       
     tl  wlj     xvxmw    vwk    dajl   aw zvzl  zv     
         m i     lj zmxltlxmdi  jawltltvwatiz     ji    
         zvdi     v  wkt jmwizltltmx  idmj zi           
          ti      ti kwvtawm  xk  wazixmd  k            
                   tvzmtvwiwlzvtvjmjmziwijvj            
                      dmwmzmzvxkzvwiwkdmtv              
                    izlwmjkwv ax zmzlwmxl               
                    z  awvjawkjlxmdltmx tl              
                   ti  wmd dmzadvwv kwm  zi             
                   v  tmzkdmwajidmzadawi  z             
                   z  awvjldmzijvwv lxmz  v             
                   iziwv ltaxvzkzkx   dm it             
                    vzm vt wkzijvza   iwkz              
           lt     tktadvj tmxizvjvw    mzlj             
            lti itatvwv lzkwmtkxlxm    zmzax     zl     
              tltkjlwa  jv mzv   vd     wvjvxl lzi      
                ixvzmt tv  daz   da     kxizk l         
             itlxvzlw zl   vwv   mt     jm  tktvti      
    itltltltkx tajidmzi     mtl lw       wk lz dijltl   
            dvti kxat       xkz xk       vxvdvtvxi  t   
            mz tkdlz        iwv mj        vtaxlxvdltkz  
          tvxkzajvt          mjkw         tvzat datlx   
        ldvtkwkti            tvdl              jlz  i   
        tltvwvxl              xa  tl                    
         jlzvdl               vd tl                     
             ij             z zajv                      
                            a  zv      ti               
        tl       ij         xl vz  l    z               
         z       z         tkxlxktvj    v  jl  ziz      
         lwvz   jv         a k v lxltl  jv ixaxm kxlj   
       jvtkwvdi v          d xlzvt   jlt zvxazlxvxlj    
  jvzvtltkzkdvdvz    itvtlxv lda       izkdkjmzlw       
    ktvtlj dlwmtk izvj tk mjl mz         xvdmdkxvtlti   
    tvx    ljiwmzvz     xawvtkdm        tlwmzlt         
    ljazi   vzvwmz      vdmtltawltlti   kwmj x          
     l vzltlzlzawmj      mx   tmt      lwmxvz           
       j      ixmwatltltvwl   lwv     iwmwvzltltlt      
              zijmdvj zmdmtvjlzmwmzltldmwiz      lj     
               z xmtvzmtvd tmz dazmtlzawi v             
               lt wmdmwizmzvxvzmd dmxvwk lt             
                ldawmwixaw tazvdmzlwawmtlt              
                jl vwati mzktvxmzltkwmzkt               
                v  wmwajldmzkxmwi lwmw  v               
                 vzmdlxadmwv iwmxawkdmt z               
               jvxmwvt   wktvxmwi itkwmzi      dij      
              ti kwv    zmtkzktaz j  kwkzv   itvtv      
       jvj   jvzawa     vw tldlwmt    mwvjk    jaj      
         ltltaxvwaj     tm  tv ax     tmwktv   vti      
        itvtlzvzlz       wl it wv      xkxidvtazi       
   ltltljk   ldlz        ax x tm       ixlxkjitvxltltl  
     ji lt               tm v ax        izvz    m       
     izlx                 dvwlwi          ti   iz       
    iti v                jlwmwkj           xvtvxk       
        z                  aza                zlxlj     
        ij                izmz                ljlzvt    
                          z d                  ij       
                          k                             
                         vz                    l        
       jv                zvt               z tkzvj      
      tkt                vzv               idl  j       
      kwaxvti            zvx             tlzkj          
      zkzkzlx  v         ata            jlzvzvt         
    itkxl vxlz z         w zl        z  kzvt z xltltlt  
   itltkzvxidmzi         m id        itvwl vtvzv        
         tadvwmjvtltktltkx  m         vwatvzijk         
          tltmwvt   zi  wktidv        xmtiz jmj         
           tl mx t   z jmxlxvd        mxizktldaxlti     
            jvxmj    v vwk izm       kwkxltldljk        
         tlj  vwa   itidmxltvwk     iwmtl it jltv       
       lti izlxkwv    tmzv   mx     dmjatvt tvj j       
       t     tltmwltltlwkz  ldmtltlzmdlx     ti         
             lj xmxi iwmtajlzkwa  tawi v    jkt         
              v iwmziwvd zvt zawatvwa  z                
              tl kw dm mjkzitvdlwvzmt ti                
               jvxmwmdiwixvxixazmwmwvzi                 
                tlxmw zmjkdv kwltmwizi                  
               jl  wmziwadixkwvtvwa  x                  
               v  tmwk awkxvxmziwmw  v                  
               z  awvwadmzvjawawadmt z                  
               lj wmt  kwvzvzmtvtkwa v                  
        ij      lzmj  lwvxmzaxmtvjkw t                  
     i  z     jvxmd    m vzltvwl lzmwkt                 
     zltkt   jvzvwi    w jmz zati idmtkz     j          
    tljidvj  axldm     mj tv kd zi iwazkz  lti          
       jktltaxijmt     wv  z dk  xi mwvzazlt            
   itltlzltiz  ad      ad  v mt   zltmtlxixlzi   ij     
             xvtk      tm  zlw     tvxktkzixvtktltkt    
            ja k        wl  wk       vzlxiwkjkx  kz     
             tlj        kx  mj        ldatvzmxitlj      
                         m lw           zvtvwmt         
                         xixlx         jldvtadlt        
                         izk kt          ij zitvdl      
                          vz dv                         
                          zixkxi          jlt           
              lzvj          mjvx         jkjkj          
          j   tktk         vx zmj        kzvz           
       j ti    zlxv        wl vxk        wv v  jltltlj  
     vdatltltljv kw       tm  zlw       xm  xltktvj     
    ldmtvtvtltldl mt      ad  v mz      mtlxvjvz tvxvj  
     itldl itltvjvxm      wv  z da     vwvjktl vdkjvt   
       jitlt  izktvwl   itmtlxatkwl    wkzkt   j  l l   
        jl      jltkw     w jvx za    tmtl              
                  vzmt    m vjkzvd    mdlt              
                  z dmj   wktvdkdv  jkwi v              
                  v lwatitkwv kzmzvzlwm  z              
                  z  mdkwkwmzlxawltadmt  v              
                  k  zmwi adkzmdmz zmw  kj              
                  jvjvwltlwktvwidmziwmxlj               
                    vwawldm idk vwvxmtmzvj  lt  i       
                 lzvwkjmz wvzkxadmjmdidk lt  vxiz       
                lt tmxktm a lzkjvdvw xawi it  ax        
                z  mdv  zawizkzlxmd tlxmwl vjlt    i    
                kxmwatltlzmziz tawlti  xmxkdmzltltkzl   
   itltlxvtltvdkxiwm      wv v  wk      wajvjktvtl      
        ltltlj  vtmj      aw z zmt      iwl l           
       vj j      ax       zmxvjvw        kd             
    ltvjijix   tvwi        wixvza        jmxvzi    x    
     ixvxvzktlzlwv     ltltadktmzl        zmt z  lxi i  
     z ta itltlxm          tm  w           dvzvdltlzmx  
     v  jkzlxvjmj           w tk           iwi vtlxlxl  
  itlzvtlzvjv mx            mjkj            kdlz jlzvz  
         vj zkxi           ixvx             jkzvt   zi  
          izktv            z zk              jvtvz  ij  
         izvzl             v vz                         
                          iz xi                         
                       v  z  l                          `;
