// Generated by scripts/generateSigil.mjs — run it again rather than editing.
export const SIGIL_LEFT = `                           jlxktltljlxv      j          
                             vz    idl       v          
                              aj   zv        z          
                              zv   lz        v          
                              vzitltatlj     z          
              j               xlx      itlt ti          
            itkzl             izlj    ij  izk itvtlj    
              xv              jktatvtlt     xlj tajltl  
              i          jltltlxltkt  ltltizi     vj ji 
                   k           v  jl      tv       v    
                   tl          z   tl     v        j    
                    zi         v    zl   v              
                     zi lt     jl    zljvj              
                      zk        z     zk                
                       tvj      v    zit                
                  tlxltltvzi    x  lzi     lt           
                vz jv      jlzltmzvj     j  izit        
              jvj  v      jlzvxmwazlt    itvj zv        
              i    z            atlt        vtaj        
                   l            d  izl      jkj         
                                a    jltljltlz          
                                x       jltltv          
                                v           itltlj      
                                z                iti    
                                v                       
                          ji   lz  lt                   
                           jltljktlj                    
                                z                       
                                v                       
                               lt                       
                               z                        
                               v                        
                               z                        
                               v                        
                              iz                        
                              z                         
                              v                         
                             vj                         
                             z                          
                            jl                          
                            v                           
                            z                           
                       jlj jv                           
            tl           ltktltlti                      
             z             z                            
             ititlj        v                            
         j titkt          lt                            
  jltltvjv vjv            zl                            
     j  ixvzk             vz                        i   
     izl  xmti            zv                      jvt   
   tltlzvzkwi             vz                    izv     
  jltltltlxadi       itltkwmxltl              tvt       
          v ldltltltltlxkdmdkxvti        jltlzltlj j    
          z  lxvj tltlt  atv    jltltltlxv      jvxl    
    ltltltvtltatvt    v lx z             jvt  lzv  tl   
         vj   z       zvtv v               lz       jl  
          vz  vj      vx z                  ix          
           itltkj  izvjltv                   iz         
              ltltlzv   kt                  idvj        
             it jvtij   zi            jltltlxi v        
             zlzkzl  tltkdltlti           lzi  j        
           ltaj z tvt   zv               it             
     jltltl  j  v       vz                              
                ti  t   zv                              
                 d  itltktktl                           
                tlz     z z                             
               zltlt    v v                             
             izizl lz   z z                             
              lzi   ij  vjv                             
                         kt                             
                iti i    d                              
        z      vt  vj    vt                             
       zi     vj  iz     zv                             
       v     v    zltltltadl    z                       
  itltlxlti  z    v     vzlj    v           i           
       axltltk    z     di v   it         jlxlt         
     jvdvtltltazi v    zk  zitlxlt          v           
   izvt         zvxltlxkxlzazltljiti        j   j tl    
  vzv            tk   vjkt jl         lj   t  ltlzi     
   v              ti iz z   z         z  k ltvtiz       
  i                z z  v   v        z   jv azvxlti     
                   idi  z j z    itvxlti izkzkz         
                   zvt  v v v     izi  jkwvzizl         
                   i iz tlz jl   vz   jlxkdmx z         
                      izlxv  zitlj   ti v azltv         
                        tkwkzat jl     ijlzvtlxltltl    
                      itldmwmdltl        jkx tl  jvti   
                   ltltlxkwizktltlti     kzvtatlti      
               tltlj  ltlzv  xlt   jltltkxlj  ltv       
           itvti   ltltlt z  v itl     vtv      jvj     
   tlti  tlt jltltvtlzi   l  z   jvzitvjl         i     
      jltltvdatltlj          v      tvzi                
           jaj               zi        jlzvt            
           k l                z           tltltltltlt   
          vj            ij  ltktlti        jv       ij  
         lz              ltlj z             tl          
   tltltlzvj                  v              di         
         v vt                 z            iziz         
         z  itl              ti          jlz  v it      
         v    jlj            v       itlti    xat       
         j                   z               ziz        
                             v             lzi v        
                             z         jltvj   j        
                             v                          
                            iz                          
                            z                           
                            v                           
                            z                           
                           z                            
                           v     lj                     
                           z   tvxi                     
                      jl lzkj tl  z                     
                        ltktawvxv v                     
                          zlzlwktlz                     
            izi    j      kjvt zl v                     
              jvj ti      dvj   zit                     
                vtl  jltl kz    iw                      
                 ajlzl   it     tl                      
                 xl      z   z tl                       
                 v       v  jvzl                        
               zitl  tltldlzmwkt                        
    tltlti     vt zi   ltaxvzk                          
         tltltlzktlxlxvtlz   z                          
               lxlzkti  tv   i                          
   jltltltltltlj  vz    vzi                             
                  di    jmj                             
                  at    lw                              
                  xkzltvjaj                             
                  idkxitlzv                             
                   vxltltkdltlt                         
                    izi  zv                             
                      ti vz                             
                    it   zv                             
                     itltkxlti                          
                         zv                             
                         vz                             
                         zv                             
                         iz                             
                         zv                             
                         vz                             
                         zv                             
                        tijv                            
                  ltltljv  z                            
                       vtltv      z                     
                       z   z      v                     
                      zi   v     lj    i                
                     jl    jv    di    z                
                     v      z   ja     k                
          lj        v       v   vz     x    v           
     itl  zltltlzi vj jltltlxltawatkdawmtlxv            
       jvtkj   xvtkzlj  l   vtvwkxvxvx dvzi             
         lz  lzl vj  i  z   xltatvdlzvtv lz             
   jl     v   v  j      v   kza   v   vz  i             
    jltlj zi  z         z jkdl    z   xv                
        itlzltlz       zmdktv     v  tl itlzi           
              jltltlzvzawmxvdltltlxltvtlj               
                        k   v      z                    
                        z   z     ti                    
                        v   v                           
                        t   z                           
                       ti  tktitlj                      
                        jlt zij                         
                            v                           
                            z                           
                            v                           
                            z                           
                            v                           
                            z                           
                            v                           
                           vj                           
                           z                            
                           v                            
                           z                            
                           v                            
                           z                i           
                          jl             v  z           
                          v        tltltijl v           
                          z        lzltlzvdlxi  ji      
                          v       ij      izv  ja       
                          z                kt  kz   j   
                          v                d jazvti v   
                          z               jaza   lxvx   
                          v               kdv     vd    
                      j   zltltlt        lxktltlxktvtl  
                      itltvt            vdi     vz      
                           v           vz       tv      
                           z   j     zvj tltl   vz      
                           v   v   vxl      jltlx       
                           x   xizkt           jv       
                           vjlwmwl             v        
         jlt             jlxldvwazlj          iz        
           itltvzltltltlti kti m vtitltl     ix         
               di        tlzi  tk  tvj  ltltiz          
              xvj     tlt   z   jvt  izltl lxvt   tl    
       zvj   ti   lzlti     v     izltltkzkxlzltlt      
     ltltlzkzkzltlj     tltlxltltlj      v              
             zv             v           kj              
             vz             tl     itlzkx               
             zv        j     z   jlj   ti               
             itvtltltlti     v        zi                
               di            z       ji                 
             ltitl           iz                         
         tltlj   jvj          v                         
                              z                         
                              it                        
                               k                        
                               ti                       
                                z                       
                                v                       
                                z   zi                  
                            lti v    xvj                
                              zlz  izk                  
                 t      itlti  jajlz z                  
                tkti   ij   jltlxaz  v                  
                 t              vtk  z       t          
                                z tl v       v          
                                v  zlj      vj          
                          j     z  vxltlj  vt           
    iz                    itltlzvtlxktltvjlj            
     izl                       v  jl     ixkj           
  i    tvj                     z jv      tlzlz          
  tl     lzi                z  ktl         v  zi        
   tvtitltltlti             v idi          z   t        
    tkd     jvtltlt       tldaxk           v            
  izizl     v      tltltltvtaw z           z            
  t  it     t               zkzktl         l            
      l                ji   ljaj jltlti                 
                        z     zvzi    tltlt             
                        it    v  tltltltltvxvj          
                        tktltlz   j                     
                         tl  tltlti                     
                          z  v                          
                          v  z                          
                     vtijiz jv                          
                       jljlxkj                          
                           vz                           
                           xv                           
                           a                            
                           x                            
                    z     tk                            
                   zij    vz                            
                   v itltlxktl                          
        l          z     jaj                            
     v it          v    jkxkxltltltlj                   
     jlz           z jltlzv aj      it                  
      tk           vtv   vt tk                          
       xv          xltltlx   jl                         
        xlj        v    ja   iz                         
      itlzvtltltltldvtltkxlj t                          
   izlj             zi itvtltlzi                        
  it                vjldlz                              
                    jvti v                              
                     zv  z                    i         
                jl  jkx  v                   it         
               jvtltajit z z                 z          
           l   kt  l ltltk v                jv          
           tl vdlzlti   ld z                kj          
            z zktltljvj  vxat              vjitltl      
   ji       ixlzlzltltlzkwmwmtlt          lt     jlj    
    tltlzkxvzkdmdltltlxkzkwktvt          vt    it  i    
         xvtltlxitltlt jlzvz   tltlt   jljitltlj        
        di   ltvwv   lzvtizv        tltltlj             
     j titkzvtltlzvtvzvj  vt                            
     idmzl    jltltlj     z                             
  ltlt z tltltl           v                             
       v                  ti                            
        v                  z    l                       
                      jltltktltl                        
                           z                            
                           vj                           
                            v                           
                            z                           
                            v                           
                            jv                          
               ti            z                          
                zi        j  v                          
           j     xi   itlti  jl                         
           lj     z jvt       z                         
            v     vzkt        v                         
            jl    dvtktltltlj z                         
             zi  ti  z   t  ijv                         
              z tl  zv   izl  z                         
            ltlzv ltazk   itv v                         
           kj  ix   z xl  z jkzltl                      
     tl   i     lz  itvzktktltmj                        
      di         ixljltlxlzl  xv                        
       zv       ltvz     jitltvz                        
        zatljltl    zi   itltlxatlti                    
          kzi        tv       vz                        
        zlj           jvj     dv                        
      izi               lzi   az                        
     lz                   tvj wv                        
     j                    itkwmzlj                      
                             kwl                        
                              mjltlti                   
                              xv    tltlj               
                              v vt      itltl           
                             it  itlj       jvxv        
                        ltltlxltlti itltltltlt          
                             v                          
                             z                          
                             v                          
                             z                          
                            z                           
                            v                           
                            z                           
                           jv                           
                           v                            
                           z                            
                          jv                            
                          v                             
                          z                             
                          v ijl                         
                         lj  vzv                        
                         z    lzv                       
        j                vt    izv          jlj         
      ltati i          tvwltltltvxv    jvxkxlj     jl   
       idi  z        itixl      tkxi vdl         izl    
        i   v          zv      ti vxaz          vz      
            jkjitlti  ziz          az         tvj       
            itvt   jltk v          tk       itl         
           it       tlxlxltltlj     d     tvt           
                      v v           k   lzkj            
                      z z           zltvj  vj           
                      v v         ltvj      v           
                      zvz     jltlj         j           
                       wajlzlti                         
                    jlzmwkti                            
                       zatlj                            
                       vdl izlti                        
                       zvtl v  jltlt                    
                       v  jlxi      tltlti              
                   ji  z   tizltltltitltlxv             
                    tltktltkti     ij                   
                       z   z                            
                       v   v                            
                       jl vj                            
                        z z                             
                        v v                             
                        z z tltlt                       
                        ktkt                            
                        z z                             
                        v it                            
                        ti v                            
                         z z                            
                         v v                            
                         jljl                           
                          z z                           
                          vjvt     j                    
                          jktaxltlti                    
            v     lj       z zv                         
          tvwlj jlj        lj dl      jv                
            l  tl           v idl  tlzvzvtlj            
              tkt     jltltlxltatvxltlzvxi i            
  itltlj     jl it          v  xat    izvtlt            
  tvdltlzltl v              jl v k    jlz               
  i ixi    jvz               z z jv  jk v               
   l  zl     v               a v  jkjv  t               
   z   tvj   z ti            dlj   jv    ti             
   ixl ltkti vx              kx           jvj   t       
    kzl    tvxl              xv             vjixi       
  jvtl        tltlj     tvtvwmdltvt          kt         
  l  tvt          itltltlzltvwmzi          tvj          
       ij                    awvzkxl    jvzltvt         
                             zkdijltvxkdvj    izl    ti 
                             vtlxaj    itvzkzvtlzltlti  
                             j zvjvdltltltltix          
                               vz  itlj      it         
                               wi     ixltl   v         
                               v   i    z jlxvxltl      
                         jltltvwltlj  itktlt zi         
                              zv        z   jv          
                              vz        v  tl           
                              zv   ij ziz jl            
                           jltkxltlj  vwi               
                              zv  jltltl                
                              vz ti   i                 
                              zv                        
                              vz                        
                              xl                        
                              a                         
                              d                         
                             tkj                        
                            jatktltlti                  
                 t      i    z z          i             
                 v      z   jl lt       jlxl            
                 jv     v   v   k         v             
                  jv    zltiz   tl                      
             tltltlzvt  v  jv    z                      
                     itlzl it    iz                     
                       jlxlxltltltlj                    
                         vjv i     kj                   
                          kz z      k                   
                          jk v       i                  
                           xiz                          
                          tldaz            l            
                         tktawmxkt         jl      ji   
                          z  v   ltltltltltlxltltltl    
                          k  z    i     iz   ti         
                          z  v   lt      v    x         
                          v  t  iz       z    it        
                      tlt xi    z      izm     v        
                        itvjltlzl  tltvzvx     z        
                          z    k   ltlt zi  jvzv        
                          v   it       tktvti vj        
                          z   z              iz         
                          v   v              j          
                          z  lt                         
                          vtlxltltlt                    
                          z  v                          
                          v  z                          
                          z  v                          
                          v  z                          
                          zi v                          
                           z z         jvtl             
                           v v        zl   v            
                           ziz  ij   ti    z            
                           izktljitvzv    jl            
                           jkzazkdmt jlt  v             
                           lxlz   jkz  izlxi    ji      
                         jvjljv   v ix   xltvz  v       
                             vjl     it zitl itvj       
                             z z      vtl  ti vj        
                             v lt     zl    zkj         
        ldl    t        i   ixijati  tl    tv           
         vjkzizvj tl    jltljlzijv  zl    tl            
   tltltlzlzazk  zl           v  tlzi   vt              
         kj tixlxi         i  z  vd  itlj               
         zi  xkti          z  vtlj tlt   j              
       l  x   xv           vjvdltlti     v              
   ji  jltlzi iwl       ltmwmxmj   jlt  izl             
    jltltltvzltldvtltvzvzvtkxiz      izlx               
           xvtltltlt       z jkt      lz   j            
         it                l  zlzltltkzltlti            
  izlji vt                    vz      izv               
     itat                     tv        jkj             
  l itvx                 tltltaxltlj      mj            
  jlj  v                      zv         ltv            
       j                      vz         z z            
                             ltv        ji              
                           j zvzltlj                    
                           itkz                         
                             zv                         
                             vz                         
                             zv                         
                             vz                         
                             tk                         
                              x j tlt                   
                           jlzatlti                     
                             vz                         
                             zit                        
                             v v                        
                            lt ti                       
                            z   z                       
                            v   lj   jlj                
                            z jltktltl                  
                       jltltktltltv                     
                            z     ti                    
                           ti      zi  jl    tlt        
                           v        zi   ltlz           
                           z         zi   lxlj          
                           k          zltljvt           
                           z   z      ltitlzkz  lj      
                           v   k      j    vtaxvtlj     
                       j   z  lwk       itlxkjv         
                       itltktvdmwmdkzltlj    aj jltvt   
                           zizldltvxvxkdltltlxvxvtl     
                          tkt  vx    ltvdvtmxl          
             jlj      ltlzvx   jizi     kjlzktvj    iz  
               itlzkxl     k      tlti  xktlxkxkwvtlj   
                  vxl      d         tlzvtltaz jvzi     
                  zk       aj          v   izizkj xi    
                  vxi      zv         ij   z  ljltlz    
                  xvtltvtltkdltlti        zi            
                  vzltltlt zv                           
                  jvj      vz                           
                   zi      zv                           
                    j tltltld                           
                            atl                         
                            d                           
                           ja                           
                           vz                           
                           zit                          
                          jv v                          
                          v  z                          
                          z  v                          
                   ti    zi  z                          
                    jltltktl v                          
                        vj   z                          
                       it    v                          
                      idlj  iz                          
                      z  itltktltl                      
                     xi      z                          
                    zi       v                          
         z         zi        z                          
        jl        zi     i   v                          
        v        ti      z   z           ti      j      
        zi               v   v            tv    ti      
    ltltlz             jlxi vj             jl  tl       
  tkzi   lt          ltkwmxvdltlti          tltl        
     tltltlt      itltvzmxvzk                dkxltltlj  
         itltktltlt    k v  xlj            izi ij    ij 
             z      k kj z  v ltl         vz            
            zi      jkj  l  z   jlzl   itlj             
            v       kzi    tl       ltkz                
            z     jv  z    v          zitltlj           
          i vt   tv   vj   z        itl     itltltlj    
          jljazlzv   ijv   v        t              ij   
             jazktaxl lxltlxltlt                        
            zljvz tltltlxlx                             
         jlti   lt      v v                             
       ltl       kj     z z                             
     tvj          k     vzi                             
                   kj    a                              
                  izvt   z                              
                 lzlzltizv                              
               tlt tltldaxlt                            
           itlti        zv                              
                        vz                              
                        zl                              
                        a                               
                        d                               
                        a                               
                  tltltlxlt                             
                       zv                               
                      jvz                               
                      v v                               
               l     it z    ij                         
       jltlt  vj   jlxltktltlj                          
            zkz     ti  z  i                            
           jizi    jl   v  z                            
             v          x  v                            
             z          v  z                            
    ji       v         ixldmzlti                        
     tlzi    jl         ldmwk           i               
        jltltlxltltltltvza kdvtlj       z               
      ltlj          itlt z zvxi itlti  jktlj            
         ltltltlzltkj    v v lxv    jlxkxi lz           
               zi  z     zij   taxijltl  tltvj          
               v   v i    xltltv  tvxkzvtltl            
               x   z  ltltv          jkjltlt            
        ji   itv   lt     z         jvtl                
         jltltixi izk     lj           z                
            tkxldlt  kj    v           a                
         tlti    t    vj   z     jltltlz                
                       l   vj          kt               
                            v          zlzl             
                            z         ti  jltlti        
                            lj                          
                             v                          
                             z                          
                              z                         
                              v                         
                         i    xi                        
     ji             itltlj  ixk     i                   
      xi         izvtltl   iwiz     z   j               
       x       tlt     jvt zi v     v   v               
       ix     zltlzi     izatiz     z   z               
         zi iz     tvj  ltkxmtv    jl   v               
          zlz  itl   lt   xl idktlzk   v                
     tlzltlxljlt      ixizi   vtkzkxvtlj                
   lti v    jaj         jv  tlxltkxvtkdvtl              
       z      vz         xvxltkj jaxvdizk lj            
       v       izl       lt   zitkzlxktlzvzlj           
            ij   jlt      v   v itiz zi   vjit          
           lz      izl    ti vxizvz   z    v            
   tltlti it         jlti  z zvz      v    t            
       ixvx             jlzlxkd       j                 
       j jv               lzmwati                       
         it          ltltvxvxvxl                        
          v   v  tltljitlj tlzvjvt                      
          zi  xvti izlt  izl vt  vzvti            ji    
           xvtktltlj   tvt   z  lt   xltltltltltltl     
       ltlzvxaxltltltltij    v  z    lt                 
  itltlj    vj          ltltlxlxlt    v                 
           it                vjl      z                 
           z                 zv    zixvz                
           v               ixlxltltlzk itltltlj         
        itvxi               vzi    jv                   
  jltltlt  vtltltltlj       zv   itl                    
        ltlz              itkdltlxlj                    
           v               vjl                          
           tl              zv                           
            t              vz                           
                          vjv                           
                          z z                           
                          v v                           
                          z z                           
                         ti v                           
                         v  ti                          
                         zitlxltltlj                    
                        jv   v                          
                l       id   z                          
                 v       v   it                         
                 z   tltlxltltkj                        
                jlx     jatl  tl          j             
               jl lt  lxlz     z          v             
                   lj x  v     kz  i      z     t       
                    kzi  zl     kxizltltltkzkt  v       
                     vj  vzltltlzadaj    izltkdvxi      
                      lt zv       vxltlzizvj   wvj      
                       izaz       di   lwvjltlzatltlj   
                     jltlwmzltlj tkjltvdltlj  k     lt  
                     itlzawmdkzvzkzvx        vj         
                         zatlxvt    v       lt          
                         izvj jvtvzlj      vt           
                          v vzv    jvzvxvtvtltltlti     
                          z   dlt       jltlti          
                          v  tl itltltltltlti           
                          z  v                          
                          v  z                          
                      tltlzvtktlt                       
                           z zijltlj                    
                          jktkti                        
                           z z                          
                           ljv                          
                            vz                          
                            zv                          
                            vx                          
                             mj    lj                   `;

export const SIGIL_RIGHT = `          i      zktitltlxkti                           
          z       taj    vz                             
          v        zv   id                              
          z        vt   zv                              
          v     itldltljvz                              
          jl ltlj      ktk               i              
    itlzlj xvj  ij    itvj             tvxlj            
  tltidl itk     ltlzldlxi              zk              
 ji iz     jvjltlt  lxltktltlti          j              
    z       zl      ti  z           x                   
    i        z     tl   v          tl                   
              z   tv    z         jv                    
              izitv    ti     lt jv                     
                xv     v        xv                      
                ljv    z      izl                       
           lt     jvt  k    jvzltltktl                  
        ljvj  i     izvwltvti      zi vz                
        zv izlj    ltvdmwkzvti      z  izi              
        idlz        ltld            v    j              
         ixi      tvj  a            t                   
          vtltitlti    d                                
          zltlti       k                                
      itltlj           z                                
    jlj                v                                
                       z                                
                   lt  vt   ji                          
                    itlxitlti                           
                       v                                
                       z                                
                       lt                               
                        v                               
                        z                               
                        v                               
                        z                               
                        vj                              
                         v                              
                         z                              
                         iz                             
                          v                             
                          ti                            
                           z                            
                           v                            
                           zi iti                       
                      jltltlxlt           tl            
                            v             v             
                            z        itljlj             
                            lt          lxljl i         
                            tv            ziz zizltlti  
   j                        vz             xvzkj  i     
   lzi                      zv            jlwk  tvj     
     zvj                    vz             jmxvzvtltl   
       lzl              tltkwmxltlj       jadktltltlti  
    i itltvtlti        jlzkxawaxktltltltltat z          
    tkzi      zktltltlti    zld  ltltl izkt  v          
   tl  zvt  lzi             v kt z    lzldltlzltltlt    
  ti       vt               z zlzv       v   iz         
          kj                  v kz      iz  vz          
         vj                   zltizvj  ixltlj           
        izaj                  lx   zvtltlt              
        z jktltlti            jv   ijlzi lj             
        i  jvt           jltltaxltl  tvxvtv             
             lj               zv   lzl v idlt           
                              vz       z  i  tltlti     
                              zv   l  jl                
                           tlxlxltlj  a                 
                             v v     vtl                
                             z z    ltltv               
                             v v   vt tvjvj             
                             ziz  ij   jvt              
                             lx                         
                              a    j jlj                
                             lz    iz  lz      v        
                             zv     vj  iz     jv       
                       v    tadltltltv    z     z       
           j           z    itvz     z    v  jltktltlj  
         ltkti         lj   z ja     v    xltltkd       
           z          ltktljv  xv    z jvdltltlzazi     
    tl i   i        jljitltvdvtkxktltkzv         lzvj   
     jvtlt  l   it         ti lxiz   xl            zvz  
       vjlzlt x  v         v   v vj jl              z   
     jltkzvd zi   v        z   z  v v                j  
         vxvxvj jltkzlj    v i v  jaj                   
         tvjvzmxi  jvj     z z z  lzv                   
         v kwaxkti   vz   ti vtl vj j                   
         zltvd z jl   itljv  zktvj                      
    tltltktlzvtij     ti ldvxmxl                        
   jlzi  tl kxi        tltawmwatlj                      
      jltldlzvx     jltltlxvjmxktltlt                   
       zlt  itkxltlti   ltk  zvtlt  itltl               
     izi      zlz     tlj z  v ltltlt   jlzlj           
     j         tizljvzi   v  t   jvtlzltlti ltl  jltl   
                jvzl      z          itltldazltlti      
            lzvti        jv               idi           
   ltltltltltl           v                t x           
  ij       zi        jltlxlt  ij            iz          
          tl             v itlt              vt         
         ja              z                  izvtltltl   
         vjvj            v                 lz z         
      lj z  vti          jl              tlj  v         
       ldk    jltlj       z            iti    z         
        vjv               v                   i         
        z jvt             z                             
        i   izlti         v                             
                          z                             
                          vj                            
                           v                            
                           z                            
                           v                            
                            v                           
                     it     z                           
                     jkzl   v                           
                     v  tl ixvt ti                      
                     z zkzmdlxlt                        
                     vtlxmtvtv                          
                     z tv lzix      i    jvj            
                     ljv   iza      jl izi              
                      mj    vx tlti  tlz                
                      tl     lj   tvtid                 
                       tl v   v      tk                 
                        tvzi  z       z                 
                        lxmwvtatltl  tljv               
                          xvzkdlt   jv lz     jltltl    
                          v   vtlzktktlxvtltltl         
                          j   zl  jlxvtkt               
                             jvz    vz  itltltltltlti   
                             iwi    ja                  
                              mt    ld                  
                             idizltvxk                  
                             zvtljkxaj                  
                         ltltaxltltkz                   
                             zv  jvj                    
                             vz jl                      
                             zv   lj                    
                          jltkxltlj                     
                             zv                         
                             vz                         
                             zv                         
                             vj                         
                             zv                         
                             vz                         
                             zv                         
                            zijl                        
                            v  zitltlt                  
                     v      zltlz                       
                     z      v   v                       
                j    it     z   jv                      
                v    ja    zi    ti                     
                x     di   v      z                     
           z    k     vz   z       z        it          
            zktlwmdaxldmdltktltlti iz jvtltltv  tlj     
             jvza kzkzkxmzlz   t  itvxlzk   ixlzi       
             vt zlzvtazldltk   v  j  iz tvt  vt         
             j  vz   z   dvx   z      i  z   z     ti   
                zk   v    taxi v         v  jv itlti    
           jvtlj tl  z     zlxawv       vtltvtlj        
               itlzltktltltazkwmdvzvtltlti              
                    v      z   x                        
                    jl     v   v                        
                           z   z                        
                           v   l                        
                      itljlxl  jl                       
                         ijv lti                        
                           z                            
                           v                            
                           z                            
                           v                            
                           z                            
                           v                            
                           z                            
                           iz                           
                            v                           
                            z                           
                            v                           
                            z                           
           j                v                           
           v  z             ti                          
           z tijltltl        z                          
      ji  jktazvtltvt        v                          
       di  zvj      ij       z                          
   i   vx  lx                v                          
   z jlzvdi a                z                          
   kzkt   dvdi               v                          
    az     zax               z                          
  tlzlxktltlxkt        ltltltv   i                      
      vz     jaz            lzltlj                      
      zl       vz           z                           
      vz   tltl izv     i   v                           
       ktlti      tkz   z   z                           
       zi           lxvjk   k                           
        z             tmwmtiz                           
        vj          itvdmzatkti             lti         
         kj     tltljlz w jlx jltltltltvzltlj           
          vjltlt  izl  xl  jvtl        ja               
    tl   lzkt tltvj  lzi   v   ltl     izk              
      ltltvtkxvxltltvj     z     jltvt   jl   izv       
              z      itltltktltl     itltvxvxvtltlt     
              ix           z             zv             
               kxvtlj     tl             vz             
               jl   iti   v     i        zv             
                jv        z     jltltltlzlj             
                 ji       v            ja               
                         vj           tljlt             
                         z          izi   itltl         
                         v                              
                        lj                              
                        x                               
                       jl                               
                       v                                
                       z                                
                  jv   v                                
                izk    z jlt                            
                  xvj  vtv                              
                  v vtidi  jltlj      l                 
                  z  vdktlti   ij   jlxl                
          l       v  xlz              l                 
          z       z tl v                                
          iz      itv  z                                
           lz  itltkz  v     i                          
            itizltlxktlzvtltlj                    vj    
           ixkj     ti  z                       tvj     
          vtvtl      zi v                     izl    j  
        jv  z         tlx  v                jvt     tl  
        l   v          jaj z             jltltltljlzl   
            z           xkdatl       ltltlzi     axl    
            v           v mdlzltltltl      z     tvjvj  
            t         tlxvxv               l     lj  l  
                 jltlti idit   ji                t      
             ltltl    jvzv     v                        
          izkzltltltltl  z    lj                        
                     i   vtltlxl                        
                     jltltl  tl                         
                          z  v                          
                          v  z                          
                          zi vjijlz                     
                          ixktiti                       
                           vz                           
                           zk                           
                            d                           
                            k                           
                            xl     v                    
                            vz    ijv                   
                          tlxktltlj z                   
                            idi     v          t        
                   itltltltkxkxi    z          lj z     
                  lj      id zvtlti v           vti     
                          xl lz   zlz           xl      
                         ti   ktltltk          zk       
                         vj   di    z        itk        
                          l itkxltlzatltltltlzvtlj      
                        jvtltlzlj jv             itvj   
                              vtatiz                lj  
                              z jlzi                    
         j                    v  zv                     
         lj                   z  kxi  ti                
          v                 v v ljidltlzi               
          zi                z xltlt t  lx   t           
          ix                v at   jltvtaz tl           
      tltljiz              ldkz  izitltlxv v            
    iti     lt          ltlwmwmxvtltltvtvtkj       ji   
    j  lj    lz          lzlxmxvxktltltawaxvzkxvtltl    
        itltljiti   ltltl   vzvti ltltljktltlzk         
             itltltl        zvjlzvt   zmzlt   ja        
                            lz  izvzlzvtltlzvxljl i     
                             v     itltlti    tvwaj     
                             z           tltltl v ltlt  
                            jl                  z       
                       t    v                  z        
                        tltlxltlti                      
                            v                           
                           iz                           
                           z                            
                           v                            
                           z                            
                          zi                            
                          v            jl               
                          z  i        jv                
                         ti  jltlj   jk     i           
                         v       lzi v     it           
                         z        lxvz     z            
                         v itltltlxlza    ti            
                         zij  l   v  jl  jv             
                         v  tvj   zv  tl v              
                         z zlj   xvdlt zvtlt            
                      tltvxi v  tk v   kj  ix           
                        iwltlxlxvzlj  vt     j   tl     
                        zk  tvtktltitkj         ja      
                        vzltlji     vzlt       zv       
                    jltldktltlj   jv    tltitldv        
                        vz       zl        jvx          
                        za     izi           itv        
                        vd   jvt               jvj      
                        zm izl                   vt     
                      itvwmxlj                    i     
                        tmx                             
                   jltltiw                              
               itltl    zk                              
           tltlj      lz z                              
        zkzi       itlj  lj                             
          ltltltltlj jltltktltlt                        
                          z                             
                          v                             
                          z                             
                          v                             
                           v                            
                           z                            
                           v                            
                           zi                           
                            z                           
                            v                           
                            zi                          
                             z                          
                             v                          
                         tij z                          
                        zvz  it                         
                       zvt    v                         
         iti          zvj    lz                i        
   ti     itkxkzi    zkzltltltmzl          j jldlt      
    tvj         taz jkxl      tkjlj        v  jaj       
      vz          vdkz jl      zv          z   j        
       izl         vd          vjv  jltljixi            
         tlj       xl          z xlti   lzlj            
           lzl     a     itltltktktl       lj           
            ixvt   x           z z                      
           iz  izltv           v v                      
           z      izlt         z z                      
           i         itlti     vzv                      
                         jltvtidm                       
                            jlxmwvti                    
                            itldv                       
                        jltvj taz                       
                    ltlti  z tlzv                       
              jltltl      jkti  z                       
             zktltljltltltvjl   v  ji                   
                   ij     jlxltlxltl                    
                            v   v                       
                            z   z                       
                            iz ti                       
                             v v                        
                             z z                        
                       ltltl v v                        
                            lxlx                        
                             v v                        
                            lj z                        
                            z jl                        
                            v v                         
                            z z                         
                           titi                         
                           v v                          
                    i     lziz                          
                    jltltkdlxi                          
                         zv v       it     z            
                zi      ta it        iti itmzl          
            itlzvzvtl  taj z           tl  t            
            j jkzvtltkzldltktltlti     lxl              
            ltlzvj    ldk  z          lj ti     itltlj  
               vti    x z ti              z tltvtltazl  
               z xi  zi v v               vzi    jkj j  
               l  zixi  z d               z     tv  t   
             jl    zi   ita            jl v   izl   v   
       l   izi           kx              kz jlxlt tkj   
       jkjiz             zk              tkzl    tvx    
         lx          lzltawmzlzl     itltl        tlzi  
          izl          jvwmzltvtltltlj          lzl  t  
         lzltvzi    tkxvzmd                    ij       
 jl    tvj    izaxkzltijaxv                             
  jltltvtlzvxvzlj    idktlz                             
          kjltltltltazizv i                             
         lj      itlj  vz                               
         z   tltkj     jm                               
      tltkzkti v    j   z                               
         jv ltlxlj  itltmzltlti                         
          zi   v        zv                              
           tl  z        vz                              
            ti vjv ij   zv                              
               jmz  itltkxlti                           
                tltlti  zv                              
                 j   jl vz                              
                        zv                              
                        vz                              
                        tk                              
                         d                              
                         a                              
                        ixl                             
                  jltltlxldi                            
             j          v v    j      l                 
            tkti       lt ti   v      z                 
             z         x   z   z     zi                 
                      tl   vjltv    zi                  
                      v    zi  z  lzvtltltl             
                     vj    lj tvtlj                     
                    itltltltktkti                       
                   ix     j ziz                         
                   x      v vx                          
                  j       z xi                          
                          vjk                           
            t            vdatl                          
   ji      ti         lxkwmdlxl                         
    tltltltktltltltltlt   z  v                          
         jl   vj     j    v  x                          
         k    z      lt   z  v                          
        lj    v       vj  l  z                          
        z     wvj      v    jk ltl                      
        v     kzvzltl  tvtltizlj                        
        zvzi  jv ltlt   x    v                          
        iz jlzlxl       lj   z                          
         vj              v   v                          
          i              z   z                          
                         lt  v                          
                    ltltltktlz                          
                          z  v                          
                          v  z                          
                          z  v                          
                          v  z                          
                          z jv                          
             tlzi         v v                           
            z   tv        z z                           
            v    jl   ij  vjv                           
            ti    zvzljitlxvj                           
             z  lti lwaxvdvxi                           
      ji    jktvj  vxi   vtkt                           
       z  vzltk   kj z   zitizi                         
       izlj tljv lj     tiz                             
        iz jl  tlz      v v                             
         ixv    tv     lt z                             
           zl    tl  jldijkj   j        l    tat        
            tl    tv  zijvtitlti    tl izvjvxiz         
              lz   jvtl  z           tv  xvdvtvtltltl   
               itlj  az  v  j         jktkjl ix         
              i   ltl itlz  v          jlxk  jv         
              z     jltltaziz           zk   k  t       
             tvj  lti   iwkwmwlt       tmj jvtlti  ji   
               ktvj      vjkxlzvzvzltlzatltvzltltlti    
            i   vt      lxi v       ltltltlzk           
            jltltvxltltvtv  t                lj         
               zvj      vz                    lz jitvj  
             ixi        zl                     ldlj     
            iw      itltkdltltl                 kzlj t  
            zlt         zv                      z  iti  
            v v         vz                      i       
              ji        zlt                             
                    itltvzv i                           
                         vxlj                           
                         zv                             
                         vz                             
                         zv                             
                         vz                             
                         xl                             
                   ltl i k                              
                     jltldvti                           
                         vz                             
                        ljv                             
                        z z                             
                       jl lt                            
                       v   v                            
                iti   it   z                            
                  tltlxlti v                            
                     zltltlxltlti                       
                    jl     v                            
        ltl    ti  jv      jl                           
           vtlt   jv        z                           
          itkt   jv         v                           
           lzitltv          x                           
      it  vxvtljlt      v   v                           
     itlzkdlz    i      x   z                           
         zixktlj       xmt  v   i                       
   lzlti id    itltvxawmwazlxltlj                       
     tlzkzktltltaxkzkzltatvjv                           
          tkwlzazlt    kz  lxl                          
  vj    izlxvtix     jvji   kzvtlt      iti             
   itlzmxkxktlxk  jltl      x     tkxvtlj               
     jvzi vdltlzvtl         a      tkz                  
    jk ixvjvj   z          id       xv                  
    vtltit  v   ij         zv      jkz                  
            jv        jltltaxltlzltlzk                  
                           zv ltltltvz                  
                           vz      izi                  
                           zv      jv                   
                           atltltl i                    
                         tld                            
                           a                            
                           di                           
                           vz                           
                          ljv                           
                          z zi                          
                          v  z                          
                          z  v                          
                          v  jv    jl                   
                          z tlxltlti                    
                          v   iz                        
                          z    lj                       
                          vj  itaj                      
                      tltlxltlj  v                      
                          v      jk                     
                          z       jv                    
                          v        jv         v         
                          z   j     jv        ti        
      i      jl           v   v      jl        z        
      jl    zl            z   z               jv        
       tl  ti             iz jkti             vtltlt    
        tltl          jltltazkwmxlt          lt   jvxl  
  itltltkxa                xvzkwvzltlj      ltltltl     
 ij    ij jvj            itk  z x    ltltlxltlj         
            vz         tlt z  v ix x      v             
             itlj   tvti   v  t  ixi      jv            
                vxlt       tl    jvx       z            
           itltljv          z    v  zi     v            
    itltltlj     tlj        v   iz   zl   lz j          
   ij              l        z   zij   zvtvditi          
                        ltltktltkt tkdlxvdi             
                             ktktltltl vzitv            
                             z z      lt   jlti         
                             v v     ix       tlt       
                             jvz     x          izl     
                              d    ix                   
                              v   lzvj                  
                              zvjltvtvt                 
                            ltkdatltl ltl               
                              zv        jltlj           
                              vz                        
                              tv                        
                               d                        
                               a                        
                               d                        
                             ltktltltl                  
                               zv                       
                               vzi                      
                               z z                      
                         ij    v lj     t               
                          itltlxltkti   iz  ltlti       
                            j  v  jl     vxv            
                            v  z   ti    jvji           
                            z  k          z             
                            v  z          v             
                        jltvwatkj         z       ji    
               j           xmwat         ti    jvtl     
               v       itlzax dvzltltltltktltlti        
            itlxi  jltlj jkzv v ltlj          itlt      
           vt jkxkti    zkt z z    ixltvtltltlt         
          izltl  tltijkdl   ijv     v  jv               
            tltlzvxkzl  zltltk    j z   z               
            ltltixi          zltlt  v   k               
                tlzi         v     lt   zlj   ji        
                v           it     xvj jkjltlti         
                d           z    ix  ltatkxl            
                vtltlti     v   iz    l    jltl         
               lx          iz   t                       
             tvtv          z                            
        jltlti  jl         v                            
                          it                            
                          z                             
                          v                             
                         v                              
                         z                              
                        jk    j                         
                   j     xkj  itltlj             ji     
               i   v     vjmj   tltlzvj         jk      
               z   z     z jv lzi     ltl       k       
               v   v     vjldvj     jvtltv     kj       
               z   ti    zlwkxlt  izl     vj jv         
                z   xvtlxaj tk   lt   tlj  vtv          
                itlzkxvxlz   jvjkj      ltitktltvtl     
              tlzaxlzkxltktl  zi         idi    z jlt   
            it xvjazkdi ixltkzk         vz      v       
           itvzvtlxktvxljv   lt       tvj       z       
          ljiz   jv vjlj z   z      lti   ij            
            z    v   vzvjkz jl    tvj      vt           
            l    z      vzv v  jlti         lj jltltl   
                 i       axktvti             kzkj       
                       jldmwvt               zi i       
                        tkzkzkzltlt          lj         
                      lzizvtl itljitltl  z   z          
    ji            jlzvz  lz tvj  ltvj jlzk  jv          
     tltltltltltltk   lt  v   lzl   itltlxlzk           
                 lt    v  z    ijltltltltkdkzvtlt       
                 z    ltktktltlt          iz    itltlj  
                 v      tiz                lj           
                vzkjv    zv                 v           
         itltltlj xvtltltktkj               z           
                   zi    jvz               jkzlj        
                    tlj   zv       itltltltlz  ltltlti  
                    itktltaxlj              vtlt        
                          tiz               z           
                           zv              tl           
                           vz              l            
                           ziz                          
                           v v                          
                           z z                          
                           v v                          
                           z jl                         
                          jl  z                         
                    itltltktljv                         
                          z   zi                        
                          v   aj       t                
                         lj   z       z                 
                        ixltltktltl   v                 
             i          tl  tldi     kti                
             z          v     vtkt  lt ti               
       l     v      j  vx     z  k it                   
       z  lxvxltltltvjkx     tv  jvx                    
      jkzaxltvj    idadvtltltvz  iz                     
      izm   izvjvtltkz       zv lt                      
   itltldvtltizmt   ja       vdvj                       
  lt     x  itltazltixl itltvwmtlti                     
         iz        kzvxvzvxawmdvtlj                     
          lt       z    lzktldv                         
           lz      itvzlzi izvj                         
     jltltltlzlzkzvzi    zvz z                          
          jltlti       lta   v                          
           jltltltltltlj tl  z                          
                          z  v                          
                          v  z                          
                       ltlxlzvtltl                      
                    itltijv v                           
                        jlxlxi                          
                          v v                           
                          zit                           
                          vz                            
                          zv                            
                          kz                            
                   it    iw                             `;
